### ISSUE TITLE
How to disable sql query logs?

### ISSUE THREAD

**Issue by mkarganov** [hanami/hanami#1000]
Hi, is there any possibility to disable query logs  in stdout on INFO level like:
[bookshelf] [INFO] [2017-02-11 15:42:48 +0100] (0.000381s) SELECT "id", "title", "created_at", "updated_at" FROM "books" WHERE ("book"."id" = '1') ORDER BY "books"."id"

**Comment by jodosha** [comment]
@mkarganov 👋 Hello, there isn't a way to disable SQL logging right now. If this is important to you, please consider to contribute with a PR that introduces this enhancement. Thanks!

**Comment by mkarganov** [comment]
Thanks @jodosha, I can try, is this about this line? https://github.com/hanami/hanami/blob/master/lib/hanami/components/components.rb#L90

**Comment by jpaulgs** [comment]
Just in case anyone else lands here, you can make the sql logger quiet as long as your using the sequel rubygem. Something alone the lines of:

```ruby
Hanami.configure do
  model do
    adapter :sql, "postgresql://..."

    gateway do |g|
      g.connection.sql_log_level = :debug
    end
  end

  logger level: :info
end
```
