### ISSUE TITLE
Confusing output after SQLite migration.

### ISSUE THREAD

**Issue by papergliff** [hanami/hanami#1002]
When running migration: `hanami db migrate` with SQLite here comes confusing output:
```
...
[hanami] [ERROR] SQLite3::SQLException: no such table: schema_migrations: SELECT NULL AS 'nil' FROM `schema_migrations` LIMIT 1
[hanami] [INFO] (0.002509s) CREATE TABLE `schema_migrations` (`filename` varchar(255) NOT NULL PRIMARY KEY)
[hanami] [ERROR] SQLite3::SQLException: no such table: schema_info: SELECT NULL AS 'nil' FROM `schema_info` LIMIT 1
...
[hanami] [INFO] Finished applying migration 20190605074443_create_uses.rb, direction: up, took 0.003523 seconds
```
Output is confusing for me because it seems like it's not an error, but some kind of warning.

After verifying, it came to me all the migrations did in fact succeed. 
But It seems like there is no schema_info table.

**Comment by jodosha** [comment]
@papergliff I'm sorry about the confusing output of this log.

Why would you expect `schema_info` table? We use `sequel` gem to run the migrations. According to their documentation:

> The migrator automatically creates a table (schema_info for integer migrations and schema_migrations for timestamped migrations).

https://sequel.jeremyevans.net/rdoc/classes/Sequel/Migrator.html

Given we used timestamped migrations, only the `schema_migrations` table is expected to be created.
