### ISSUE TITLE
Support default dotenv rails files

### ISSUE THREAD

**Issue by gmanley** [hanami/hanami#1003]
The dotenv integration with Rails supports [a number of default files](https://github.com/bkeepers/dotenv/blob/master/lib/dotenv/rails.rb#L58) that the Hanami integration does not. Specifically the .env.local style files. I like to use the .env.local files as a place to store things I don't want to commit (I have it in the .gitignore). If I make a PR adding this functionality is that a contribution you all would be willing to accept? From what I can tell it will be a change to [this method](https://github.com/hanami/hanami/blob/master/lib/hanami/environment.rb#L489). I just wanted to check in before implementing it in case this was intentional or there is an opinion to keep the one default file pattern of .env.development.

Thanks!

**Comment by davydovanton** [comment]
hey, thanks for report

Not sure that it can be helpful but I use `.env.development.sample` in my projects for commiting env file to the git repository and `.env.development` for working locally. You can [check my example](https://github.com/davydovanton/rubyjobs.dev) if you want.

@jodosha WDYT about this?

**Comment by jodosha** [comment]
@davydovanton I think @gmanley is telling something slightly different.

Is the proposal to make create the following hierarchy from the lower to the higher priority?

  1. Parse `.env`
  1. Parse `.env.development` (potentially override `.env`)
  1. Parse `.env.development.local`  (potentially override `.env` and/or `.env.development`)

The idea is to keep generating the first two with `hanami new`, but potentially supporting also the third case, if that file is present.

If this is the idea, @gmanley please proceed. 👍 

---

Sample files (e.g. `.env.sample`) should be designed better as another feature, which I think goes beyond this specific need.

**Comment by gmanley** [comment]
@jodosha That's correct. That is the intent. Thanks for laying it out so clearly. I'll start working on it this weekend. Thanks!

**Comment by gmanley** [comment]
@davydovanton I do use sample files as well but as @jodosha explained the idea here is to have hierarchy that can allow overrides locally. I appreciate the example, however.

**Comment by gmanley** [comment]
@jodosha @davydovanton https://github.com/hanami/hanami/pull/1004 here is my first pass to get some feedback.

**Comment by jodosha** [comment]
Implemented by https://github.com/hanami/hanami/pull/1004
