### ISSUE TITLE
Would it be useful to add generators for ROM?

### ISSUE THREAD

**Issue by wout** [hanami/hanami#1008]
First of all, I discovered Hanami a few days ago, and I am in ❤️. Currently, I'm converting a project I started in Rails 6 and the lightweight approach of Hanami is a relief.

I swapped our `hanami-model` for ROM 5 and I see quite a few people doing the same. So I was thinking, it would be great to be able to create a new Hanami app with ROM configured as model. Something like:

```
hanami new bookshelf --model=rom
```

This setting can be stored in `.hanamirc`, along with the other specifics:

```
project=my_project
test=rspec
template=erb
model=rom
```

Then we could test for that value, and use it in generators for models and migrations.

Would you accept a pull request for such an implementation on the Hanami core? Or do you prefer such functionality to be a plugin?

I know Hanami 2.0 is on the way, but I need to get started now. Another project that is coming up, is a complete rewrite of a legacy Rails 3.2 app, with over 120 tables. This will be reduced to about 80 tables, but it gives you an idea of the number of models and migrations I have to create. I'd prefer to do it with generators. 😄

**Comment by jodosha** [comment]
@wout Thanks for your enthusiasm! ❤️ 

Regarding the idea of having generators for ROM is 👎 for me.
We're not adding new features to Hanami 1.x as we're building 2.0. Aside from that, supporting more than one database backend is overkilling.

`hanami-model` (which is powered by ROM) is the default, direct usage of ROM or any other database lib is up to you.
