### ISSUE TITLE
application middleware: body == []

### ISSUE THREAD

**Issue by glaszig** [hanami/hanami#1012]
i want to use a rack middleware application-level to inject things into the response.

```rb
# apps/web/application.rb
      middleware.use(Class.new do
        def initialize app
          @app = app
        end

        def call env
          status, headers, body = @app.call env
          byebug
          [ status, headers, body ]
        end
      end)
```

but `body` is empty (`[]`). why is that? what am i doing wrong?

it works on project-level, btw.

**Comment by jodosha** [comment]
@glaszig I can't reproduce the bug. I just tried locally with your code and it works. Can you please create a dummy app to reproduce it? Thanks.
