### ISSUE TITLE
set version capybara 

### ISSUE THREAD

**Issue by ilyario** [hanami/hanami#1018]
Default Gemfile have gem capybara. Capybara supports ruby 2.4 after gems version 3.16

![image](https://user-images.githubusercontent.com/945905/67630163-000f7b00-f8be-11e9-85a3-cd8937cbdf3a.png)

source version capybara: https://github.com/teamcapybara/capybara/issues/2175

**Comment by jodosha** [comment]
@ilyario Thanks for reporting this.

Are you suggesting to pin `capybara` in generated `Gemfile` if version of Ruby is less than `2.4`?

**Comment by ilyario** [comment]
Yes or remove support 2.3 from readme.
