### ISSUE TITLE
EOFError raised with hanami s

### ISSUE THREAD

**Issue by rokkit** [hanami/hanami#1024]
If I run hanami server on MacOS Catalina 10.15.1, I have this exception:
```
objc[94059]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[94059]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
EOFError: end of file reached
	/Users/indmaksim/.rvm/gems/ruby-2.6.3/gems/shotgun-0.9.2/lib/shotgun/loader.rb:41:in `load'
	/Users/indmaksim/.rvm/gems/ruby-2.6.3/gems/shotgun-0.9.2/lib/shotgun/loader.rb:41:in `proceed_as_parent'
	/Users/indmaksim/.rvm/gems/ruby-2.6.3/gems/shotgun-0.9.2/lib/shotgun/loader.rb:28:in `call!'
	/Users/indmaksim/.rvm/gems/ruby-2.6.3/gems/shotgun-0.9.2/lib/shotgun/loader.rb:18:in `call'
	/Users/indmaksim/.rvm/gems/ruby-2.6.3/gems/hanami-1.3.3/lib/hanami/assets/static.rb:49:in `call'
	/Users/indmaksim/.rvm/gems/ruby-2.6.3/gems/rack-2.0.8/lib/rack/lint.rb:49:in `_call'
	/Users/indmaksim/.rvm/gems/ruby-2.6.3/gems/rack-2.0.8/lib/rack/lint.rb:37:in `call'
	/Users/indmaksim/.rvm/gems/ruby-2.6.3/gems/rack-2.0.8/lib/rack/show_exceptions.rb:23:in `call'
	/Users/indmaksim/.rvm/gems/ruby-2.6.3/gems/puma-4.3.1/lib/puma/configuration.rb:228:in `call'
	/Users/indmaksim/.rvm/gems/ruby-2.6.3/gems/puma-4.3.1/lib/puma/server.rb:681:in `handle_request'
	/Users/indmaksim/.rvm/gems/ruby-2.6.3/gems/puma-4.3.1/lib/puma/server.rb:472:in `process_client'
	/Users/indmaksim/.rvm/gems/ruby-2.6.3/gems/puma-4.3.1/lib/puma/server.rb:328:in `block in run'
	/Users/indmaksim/.rvm/gems/ruby-2.6.3/gems/puma-4.3.1/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```
There is only way to run server by using env variable like this:

`OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES bundle exec hanami server`

**Comment by kaikuchn** [comment]
Have you added any gems to you Gemfile, or is this behaviour observed on a fresh `hanami new [project name]`?
If the former, what gems have you added? And please see [here](https://blog.phusion.nl/2017/10/13/why-ruby-app-servers-break-on-macos-high-sierra-and-what-can-be-done-about-it/) for a good explanation on what's going on.

Also, what version of Hanami are you using?

**Comment by cllns** [comment]
I also reproduced this, on Catalina. I found fix and a workaround.

### "Fix", reinstall macOS development tools

I found a comment on an issue in the [shotgun repo] that helped me fix this.
1. `xcode-select --install` (I also did `sudo xcodebuild -license`, not sure if it was necessary)
2. Open Xcode, to install more stuff.
3. Restart your computer

### Workaround, use `hanami-reloader`
`shotgun` has caused a lot of problems, and it's not maintained anymore. To address those problems, @jodosha wrote `hanami-reloader`, which we'll use as the code reloading tool for Hanami 2.0. 

You can use it now though, too, for Hanami 1.3 apps. Follow steps 2 and 3 on the README, https://github.com/hanami/reloader#2-prepare-gemfile except that:

```ruby
group :plugins do
  gem "hanami-reloader", "~> 0.3"
end
```

should be:

```ruby
group :plugins do
  gem "hanami-reloader", "~> 0.3", github: "hanami/reloader"
end
```
