### ISSUE TITLE
How to set up primary DB and replica DB in Hanami DB config?

### ISSUE THREAD

**Issue by tosiooooooo** [hanami/hanami#1028]
How do I set both the primary DB and replica DB (read only) connections in the Hanami.configure?

I want to set up the following site.

https://github.com/jeremyevans/sequel/blob/master/doc/sharding.rdoc

**Comment by tak1n** [comment]
From what I can tell this doesn't seem to be possible currently, I could very well be wrong here. But AFAIS in https://github.com/rom-rb/rom-sql/blob/v3.5.0/lib/rom/sql/gateway.rb#L50 someone could pass in extended options to the sequel connection through `rom-sql` which `hanami-model` uses. This means one could pass in something like:
```ruby
ROM.container(:sql, 'postgres://localhost/db_name', servers: { read_only: { host: 'replica_server' } })
```

In https://github.com/hanami/model/blob/main/lib/hanami/model/configurator.rb#L55 only the `backend` and `url` is allowed to be passed in, this is also stated in the README:
```ruby
Hanami::Model.configure do
  adapter :sql, 'postgres://username:password@localhost/bookshelf'
end.load!
```

Which leads to a `ROM.container()` call in https://github.com/hanami/model/blob/main/lib/hanami/model/configuration.rb#L159 which only sets `backend` and `url` through a `ROM::Configuration` object returned in https://github.com/hanami/model/blob/main/lib/hanami/model/configuration.rb#L140.

Furthermore in a full blown Hanami application this looks like:
```ruby
Hanami.configure do
  mount Web::Application, at: '/'

  model do
    ##
    # Database adapter
    #
    # Available options:
    #
    #  * SQL adapter
    #    adapter :sql, 'sqlite://db/test_app_development.sqlite3'
    #    adapter :sql, 'postgresql://localhost/test_app_development'
    #    adapter :sql, 'mysql://localhost/test_app_development'
    #
    adapter :sql, ENV.fetch('DATABASE_URL')

    ##
    # Migrations
    #
    migrations 'db/migrations'
    schema     'db/schema.sql'
  end
```

Changing this in hanami v1.3.x probably does not make sense anymore as the hanami model layer will most likely be completely revamped for hanami 2.
