### ISSUE TITLE
The '+' parameter becomes blank space in Hanami.

### ISSUE THREAD

**Issue by tosiooooooo** [hanami/hanami#1042]
For example, when registering email.

- Form

```html
<form method='post' action='/register'>
<input type='text' name='email' value='hoge+abc@gmail.com' />
</form>
```

- Hanami log
```
[INFO] HTTP/1.1 POST 201 127.0.0.1 /register {"email"=>"hoge abc@gmail.com"}
```

'+' is URL decoded and it become blank space in Hanami.

`hoge+abc@gmail.com`'-> `hoge abc@gmail.com`

If enter "`hoge%2Babc@gmail.com`", it becomes "`hoge+abc@gmail.com`" in Hanami".

I want to receive the contents enterd in form as it is.

**Comment by jodosha** [comment]
@tosiooooooo Sorry for this problem. One of us will have a look. Thanks for reporting.

**Comment by davydovanton** [comment]
@tosiooooooo hey, sorry for the problem. Could you say what hanami version do you use in your project?

**Comment by kaikuchn** [comment]
Hey @tosiooooooo I tried to quickly reproduce the issue using Hanami 1.3.3 but as of yet I did not manage to provoke that behaviour. Are you using a different version?
Also, is this happening in a brand new Hanami project or have you customised some things? E.g., maybe inserted any middleware into the stack that may interfere here?

Can you maybe provide a minimal runnable example for me to see the issue in effect?

Thank you very much in advance!

**Comment by davydovanton** [comment]
+1 to @kaikuchn. @tosiooooooo could you provide a better explanation of the problem or example app?

I tested it with my application (`v1.3.3`, I put `test+test@gmail.com` in to form and see it in my DB without any blank spaces) and also, I tested hanami-helpers (it's a form rendering) and when I use `text_field :email, value: 'test+abc@gmail.com'` I got the normal HTML string.

**Comment by tosiooooooo** [comment]
Thank everyone.

Hanami version is v1.3.3.

I explained in the case of form for simplicity of explanetion, but since it is used as api, I verified it with Postman.
Actually the api is used in smartphone apps(React Native), the apps is having this issue.

**Comment by kaikuchn** [comment]
> [...] I verified it with Postman.
> Actually the api is used in smartphone apps(React Native), the apps is having this issue.

Can you show us that instead? I'm beginning to suspect that the issue is with how the client transmits the data..?

**Comment by tosiooooooo** [comment]
I'm sorry, it's my mistake.I was using the postman wrong.
If set correctly, this issue didn't occur.

This issue seems to be a problem with how to use axios.
If I run following code on the web, the problem doesn't occur.
However the problem occur when running with the mobile app written in Reace Native.

```axiospost.js
const params = new URLSearchParams();
params.append('email', 'hoge+abc@gmail.com');
await axios.post(`http://xxxxxxxx/`, params);
```

I found out about axios.
Thanks to everyone for their cooperation.

**Comment by tosiooooooo** [comment]
This has been resolved, so I'll share the solution.
As for axios...

I put 'application/x-www-form-urlencoded' request header, the parameters were url encoded successfully.

```
const params = new URLSearchParams();
params.append('email', 'hoge+abc@gmail.com');
await axios.post(`http://xxxxxxxx/`, params,
                {headers: {'Content-type': 'application/x-www-form-urlencoded'});
```
