### ISSUE TITLE
Gem::Exception: can't find executable hanami for gem hanami. 

### ISSUE THREAD

**Issue by nolyoi** [hanami/hanami#1051]
So, I am new to Hanami and while trying to set up my first project I am getting this error. I haven't been able to find the solution and this is happening on a fresh install.

I'm running PopOS(deb/ubuntu). Anyone else ever come across this error?

```
~/code/projects/gecko_api on  master
> hanami new moonship
bundler: failed to load command: hanami (/home/noly/.rbenv/versions/2.6.1/bin/hanami)
Gem::Exception: can't find executable hanami for gem hanami. hanami is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
  /home/noly/.rbenv/versions/2.6.1/lib/ruby/2.6.0/bundler/rubygems_integration.rb:462:in `block in replace_bin_path'
  /home/noly/.rbenv/versions/2.6.1/lib/ruby/2.6.0/bundler/rubygems_integration.rb:482:in `block in replace_bin_path'
  /home/noly/.rbenv/versions/2.6.1/bin/hanami:23:in `<top (required)>'
```

**Comment by cllns** [comment]
Hi, sorry you're having trouble! Hm, it seems like it might be a Ruby / gems environment issue, rather than a bug with Hanami. Maybe you ran `gem install hanami` with one ruby version, then moving into the `~/code/projects/gecko_api` folder changed it to a different one?

Can you make sure you run `ruby -v` (or even `which ruby`) before you install `gem install hanami`, then again before running this command?

**Comment by nolyoi** [comment]
> Hi, sorry you're having trouble! Hm, it seems like it might be a Ruby / gems environment issue, rather than a bug with Hanami. Maybe you ran `gem install hanami` with one ruby version, then moving into the `~/code/projects/gecko_api` folder changed it to a different one?
> 
> Can you make sure you run `ruby -v` (or even `which ruby`) before you install `gem install hanami`, then again before running this command?

So, it turns out I'm a complete idiot. I was in the wrong folder. xD

My apologies! Thank you!

**Comment by cllns** [comment]
No worries. Hope you have a great experience with Hanami! 🌸
