### ISSUE TITLE
How to output Hanami::Action::Rack#request_id in reqest log

### ISSUE THREAD

**Issue by tosiooooooo** [hanami/hanami#1057]
I want to output Hanami::Action::Rack#request_id  in reqest log. Because it is to combine multiple logs in one request.

Is there a way to do that ?

**Comment by davydovanton** [comment]
Hey!

I'm using `semantic_logger` gem with tag functionality + simple rack middleware for wrapping all logger calls inside request to `request_id` tag:
https://github.com/davydovanton/rubyjobs.dev/blob/master/config/initializers/request_id.rb#L21-L27
