### ISSUE TITLE
Slow Response in API Sever

### ISSUE THREAD

**Issue by yamad07** [hanami/hanami#1072]
I use hanami framework for the production api server.
however, i think this application response is very slow.

for example, very simple code as below(the other codes are from the initial one.)
```
get '/api/health', to: ->(env) { [200, {}, ['Hello from Hanami!']] }
```

and i check response time using postman. a result is below

<img width="1144" alt="スクリーンショット 2020-08-27 12 18 50" src="https://user-images.githubusercontent.com/20740529/91380239-8179c600-e85f-11ea-87bb-1038d15a2fa0.png">

i think it's very long time.

my machine spec is below.
- Mac Book Pro (13-inch, 2017, Two Thunderbolt 3 ports)
- Processor 2.3 GHz Intel Core i5
- Memory: 16 GB 2133 MHz LPDDR3

the version is below.
```
    hanami (1.3.3)
      bundler (>= 1.6, < 3)
      concurrent-ruby (~> 1.0)
      hanami-assets (~> 1.3)
      hanami-cli (~> 0.3)
      hanami-controller (~> 1.3)
      hanami-helpers (~> 1.3)
      hanami-mailer (~> 1.3)
      hanami-router (~> 1.3)
      hanami-utils (~> 1.3)
      hanami-validations (>= 1.3, < 3)
      hanami-view (~> 1.3)
    hanami-assets (1.3.4)
      hanami-helpers (~> 1.3)
      hanami-utils (~> 1.3)
      tilt (~> 2.0, >= 2.0.2)
    hanami-cli (0.3.1)
      concurrent-ruby (~> 1.0)
      hanami-utils (~> 1.3)
    hanami-controller (1.3.3)
      hanami-utils (~> 1.3)
      rack (~> 2.0)
    hanami-helpers (1.3.3)
      hanami-utils (~> 1.3)
    hanami-mailer (1.3.2)
      hanami-utils (~> 1.3)
      mail (~> 2.6)
      tilt (~> 2.0, >= 2.0.1)
    hanami-model (1.3.2)
      concurrent-ruby (~> 1.0)
      dry-logic (~> 0.4.2, < 0.5)
      dry-types (~> 0.11.0)
      hanami-utils (~> 1.3)
      rom (~> 3.3, >= 3.3.3)
      rom-repository (~> 1.4)
      rom-sql (~> 1.3, >= 1.3.5)
    hanami-router (1.3.2)
      hanami-utils (~> 1.3)
      http_router (= 0.11.2)
      rack (~> 2.0)
    hanami-utils (1.3.6)
      concurrent-ruby (~> 1.0)
      transproc (~> 1.0)
    hanami-validations (1.3.6)
      dry-logic (~> 0.4.2, < 0.5)
      dry-validation (~> 0.11, < 0.12)
      hanami-utils (~> 1.3)
    hanami-view (1.3.3)
      hanami-utils (~> 1.3)
      tilt (~> 2.0, >= 2.0.1)
    hanami-webconsole (0.1.0)
      better_errors (~> 2.4)
      binding_of_caller (~> 0.8)
    http_router (0.11.2)
      rack (>= 1.0.0)
      url_mount (~> 0.2.1)

```
how should i fix this bad performance?

**Comment by adam12** [comment]
Hi @yamad07

It's hard to say without more information (how are you running Hanami? what other gems do you have? any middleware? which application server are you using?), but I'm almost 100% sure it's because you're using `hanami server` and not providing `--no-code-reloading`.

I confirmed this by creating the exact same route and testing with the flag on and off. The result with code reloading enabled is almost exactly as long as yours.

```
$ bundle exec hanami server &
$ curl -w "@curl-format.txt" -o /dev/null -s http://localhost:2300
time_namelookup: 0.001489
time_connect: 0.001691
time_appconnect: 0.000000
time_pretransfer: 0.001786
time_redirect: 0.000000
time_starttransfer: 0.449956
———
time_total: 0.450021
```

```
$ bundle exec hanami server --no-code-reloading &
$ curl -w "@curl-format.txt" -o /dev/null -s http://localhost:2300
time_namelookup: 0.000724
time_connect: 0.000885
time_appconnect: 0.000000
time_pretransfer: 0.000921
time_redirect: 0.000000
time_starttransfer: 0.005682
———
time_total: 0.005769
```

Code reloading through Shotgun performs a `fork(2)` and then require. You're booting the app on every request.

If you're still having performance issues, please provide a reproducible example that I can look at.

**Comment by jodosha** [comment]
Please also remember that `hanami server` should be used only for dev purposes. Better to use `puma` (or equivalent web server commands) to deploy an app.
