### ISSUE TITLE
Drop `git` in gemspec

### ISSUE THREAD

**Issue by utkarsh2102** [hanami/hanami#1075]
Hello 👋🏻 

Thanks for your great work!

However, whilst maintaining this in Debian, we found that `hanami` relies on `git` to produce a list of file:
https://github.com/hanami/hanami/blob/df741d123a0a1774b21474d9a201b5387e5830d4/hanami.gemspec#L16

Using `git` in gemspec, in general, a bit troublesome and it's best if avoided.
The rationale about this can be found here: https://docs.rubocop.org/rubocop-packaging/cops_packaging.html#gemspec-git-rationale

I'll be happy to raise a PR if you'd agree!

**Comment by jodosha** [comment]
@utkarsh2102 Hey, thanks for raising this issue. I never considered that. Please open a PR if you want. Thank you. 👍

**Comment by masterT** [comment]
I think this can be closed. 🙂
