### ISSUE TITLE
Troubles to load rake task from gem

### ISSUE THREAD

**Issue by morissetcl** [hanami/hanami#1077]
Hi there,

First of all thx for the amazing work !

I'm trying to create a `traceroute` gem like for `Hanami`. 
I am facing an issue. It sounds that currently it's not possible to load `rake task` in a Hanami app from a gem. When I run `rake -T` I have just default `tasks` and also custom ones added in `rakelib`..but impossible to load `task` from gem.

I tried many things to fix it, like:
 
```ruby
# hanami/lib/hanami/rake_helper.rb
def self.install_tasks
  require 'hanami/environment'
  Hanami::Environment.new.require_project_environment
  new.install
end
```

```ruby
# hanami/lib/hanami/rake_helper.rb
require "hanami"
...

def self.install_tasks
  Hanami.root.join("config", "environment.rb")
  new.install
end
```

It does the job and I'm able to load my task but test fails....anyway.
What could be the good way to fix that ? Any advice or idea ?

If you want to reproduce the issue you can fork [hanami-traceroute](https://github.com/morissetcl/hanami-traceroute), add it to your gemfile locally and run `rake -T`.  The **expected behaviour** will be to have the following tasks printed:

```ruby
rake environment                                   # Load the full project
rake hanami_traceroute                             # Prints out unused routes and unreachable action methods
rake hanami_traceroute:unreachable_action_methods  # Prints out unreachable action methods
rake hanami_traceroute:unused_routes               # Prints out unused routes
rake spec                                          # Run RSpec code examples
```
Let me know if I am not clear.

Thanks a lot.

**Comment by adam12** [comment]
Hi @morissetcl 

Are you still having issues with this? Have you given any thought to [making a plugin](https://guides.hanamirb.org/command-line/plugins/) instead?

**Comment by adam12** [comment]
Closing for now. I think this would make for an interesting plugin if you wish to continue.
