### ISSUE TITLE
Hanami Generators are not generating expected files and directories.

### ISSUE THREAD

**Issue by prio101** [hanami/hanami#1084]
While creating new action with command,
` hanami generate action web home#index `
it gives output:
```
zsh: no matches found: home#index
```

I have changed the file permission and checked with `bundle exec` output is same.

```
   gem version: hanami-v1.3.3

   operating system:  Ubuntu 20.04 ( WSL )

```

**Comment by adam12** [comment]
ZSH globs on `#` (and other things, like `[]`).

Try quoting the value: `hanami generate action web "home#index"`

**Comment by prio101** [comment]
It works now... thanks @adam12

**Comment by cllns** [comment]
```
hanami generate action web home/index
```
Also works :)

We have a note about this in the "getting started" guide: https://guides.hanamirb.org/introduction/getting-started/#hanami-generators

Thanks for the help @adam12 🌸
