### ISSUE TITLE
Session values not passing between apps

### ISSUE THREAD

**Issue by sebastjan-hribar** [hanami/hanami#1099]
Hi,

I need to pass session values between apps, specifically info on logged in user. I haven't been able to get it to work as per the documentation so I'm opening an issue.

For example, I set a value in App A and I can't read it in App B.

As far as I gather this is by design, since each app has it's own session. Therefore, I might be doing something wrong, but I'm not sure.

I've prepared a test project [here](https://github.com/sebastjan-hribar/sessions_test) to reproduce the behavior.

Best, Sebastjan

**Comment by jodosha** [comment]
@sebastjan-hribar I can't reproduce the bug (see the GIF 👇 ).

![session-sharing](https://user-images.githubusercontent.com/5089/113258854-c15ccc00-92cc-11eb-82d4-2b5d7600366f.gif)

**Comment by jodosha** [comment]
PS: feel free to reopen and comment in case I'm missing something. 🙂

**Comment by sebastjan-hribar** [comment]
I was just asked in gitter if I use the same session secret and I really didn't know this. I tried using the same session secret and it works. Apologies for wasting your time.
Best, Sebastjan

**Comment by jodosha** [comment]
All good no worries 👍 🙂
