### ISSUE TITLE
warning: already initialized constant due to code reloading

### ISSUE THREAD

**Issue by hedselu** [hanami/hanami#1121]
Ahoy folks, 

I just have encountered situation when `requiring_relative` a dependent base class introduces `warning: already initialized constant`.

Consider this code snippets:

```ruby
# lib/tokens/auth_token.rb

require_relative './base_token'

class AuthToken < BaseToken; end
```

```ruby
# lib/tokens/base_token.rb

class BaseToken
  VERIFY = true
  HMAC_SECRET = ENV['HMAC_SECRET']
  HMAC_ALGORITHM = 'HS256'

  class << self
    def decode(token)
      JWT.decode(token, HMAC_SECRET, VERIFY, algorithm: HMAC_ALGORITHM)
    end
  end
end
```

This is due to code reloading preformed by hanami utils (I'm sorry if this is wrong place for reporting this issue, but seems right for me as integral part of hanami env)

https://github.com/hanami/utils/blob/v1.3.8/lib/hanami/utils.rb#L71

What happens:
1. `auth_token.rb` file requires `base_token.rb` which sets up constants.
2. `base_token.rb` is forcibly loaded again via `load` method which sets up constants once again.

**Comment by cllns** [comment]
Are you using `shotgun` or `hanami-reloader`? The former isn't maintained anymore, so we recommend the latter now

https://github.com/hanami/reloader
