### ISSUE TITLE
"accept :list, :of, :non-html, :types" in a controller can still return html if `default_request_format :html` in application.rb

### ISSUE THREAD

**Issue by jf** [hanami/hanami#1124]
given a new Hanami app (seen with v1.3.4), and `accept :json` in an action, with your standard curl request (which sends `Accept: */*`, fyi) hanami will still attempt to look for, and return the *HTML* template. I'm not sure this is the most intuitive, given that we already say that we are restricting things with `accept :json`. Right now, if you have `accept :json` in your action, you will also need to set `self.format = :json`.

In some sense, this isn't such a big deal, but I find it non-intuitive at some level. At least it required some investigation, and digging into how the `Accept` header is constructed to figure out why curl was giving me HTML output, whereas my browser was giving me JSON.

**Comment by jodosha** [comment]
@jf This was fixed in 2.0, it's hard to change it in 1.3 without introducing breaking changes.
