### ISSUE TITLE
`status 404, { error: "some message" }.to_json` does not return JSON as expected, even if we set `default_response_format :json` in application.rb

### ISSUE THREAD

**Issue by jf** [hanami/hanami#1125]
as per subject. The current way to get around this is to *explicitly* set `self.format = :json`, but this is unintuitive, especially if we already have `default_response_format :json` in application.rb, and our custom body is already JSON.

NOTE: related, but not exactly the same thing: https://github.com/hanami/hanami/issues/892

**Comment by jf** [comment]
it appears that the crux of the matter is how Hanami deals with the Accept header: in the case of your typical browser value (you can use `Accept: text/html;q=0.9,*/*` for an easy-to-type substitute), Hanami will choose to return HTML, instead of JSON. I don't know if you could call this the right behaviour, given that we already set `default_response_format :json` in application.rb. The current fix right now is to either whitelist / set `accept :json` in the Action class (https://guides.hanamirb.org/v1.3/actions/mime-types/#whitelisting)... or else *explicitly* (even though you have this as the default already) set `self.format = :json` in the Action's call method.

**Comment by jodosha** [comment]
@jf Same as #892
