### ISSUE TITLE
hanami console crashes with Hanami::Slice not symbol nor a string

### ISSUE THREAD

**Issue by stormmaster42** [hanami/hanami#1165]
**To reproduce:**
* install example application
* run console `bundle exec hanami console`

```
hanami-cli-2.0.0.alpha8/lib/hanami/console/plugins/slice_readers.rb:16:in `define_method': 
#<Hanami::SliceName:0x00007fe6beb453f0 @slice=Main::Slice, @inflector=#<Method: 
#<Class:Main::Slice>(Hanami::Slice::ClassMethods)#inflector()> is not a symbol nor a string (TypeError)
        from hanami-cli-2.0.0.alpha8/lib/hanami/console/plugins/slice_readers.rb:16:in `block in initialize'
```

Quick fix is to add to_s in hanami-cli-2.0.0.alpha8/lib/hanami/console/plugins/slice_readers.rb
          application.slices.each do |slice|
            define_method(slice.slice_name.**to_s**) do

**Comment by timriley** [comment]
Sorry for the error, @stormmaster42, but thank you for reporting this! TBH, it's just nice to know people are trying the alphas 😄 

I've fixed this now via an alpha8.1 release of Hanami-cli, and have also [updated the application template](https://github.com/hanami/hanami-2-application-template/commit/b1b8c73582f2221691ec09b3ed79c0cccba315a3) to use that release. Everything looks good now!
