### ISSUE TITLE
"Slices" should perhaps be called "Branches", no?

### ISSUE THREAD

**Issue by c4lliope** [hanami/hanami#1203]
I mean... "花見", no?

**Comment by cllns** [comment]
Haha, cute idea 🌸 .

I think we're committed to "slices" though. "Branches", while having the benefit of being related to trees, it's also a term in `git`, which is ubiquitous in our community. It's also has a meaning within programming of "code branches", and they're a special Hanami-specific concept that's distinct from that.

Will leave this open to let someone else chime in and close it, but I don't think we should consider this renaming.

**Comment by c4lliope** [comment]
One could argue "slices" is used in databases and string programming;
Rust sure has experienced success using such a name.

I see no big gap in comparing Hanami branches alongside programming language branches;
you could build success on encouraging such an analogy.

Rails has Engines. Hanami should include Branches.
I hope you can carry on your elegance in describing our programming challenges.

**Comment by timriley** [comment]
I always appreciate a good naming discussion!

We chose the slice name in part as a [subtle homage to Merb](https://www.slideshare.net/hassox/merb-slices-presentation), but I also think the name does an effective job at describing its function: slicing a larger application up into constituent parts. And the axis/number of the slices is up to the app author: they can be vertical slices (like cake) or horizontal slices (kinda like lasagne), or a mix of both.

From my work in the Hanami project so far, my take is that we've tried to keep our names clear and descriptive, and haven't opted for any puns or thematic links to Hanami as a concept (or Lotus as it was before). This makes me feel like there won't be any appetite for "branch" as a name here, particularly given the existing usages that @cllns identified.

Thanks for bringing up the idea though! I'll close this for now. 🌸

**Comment by waiting-for-dev** [comment]
I see slices as different DDD domains, so I might have chosen` Hanami::Domain`, although that's more opinionated and maybe would have contrived other usages. The truth is that slice is more agnostic.

**Comment by c4lliope** [comment]
Ah, I'm only sad your name choice makes your program sound more like a logging and lumber operation
than an homage to spring blooms.

**Comment by c4lliope** [comment]
And apologies, I'm only arguing based on a rough idea of your designs;
I see no guides released describing use cases, so I can only see your [code](https://github.com/hanami/hanami/tree/main/lib/hanami/slice) and [remarks](https://hanamirb.org/blog/2022/08/16/announcing-hanami-200beta2/#conditional-slice-loading).

I'm more or less dropping Rails and seeking libraries handling similar use cases,
so I am eager to learn the changes coming up in 2.0;
good library design ends up inspiring good program design, in the end.
Rails has succeeded in some measure, and been held back in many places,
because of applications and mis-applications of their library's analogies. I urge reconsideration.

**Comment by c4lliope** [comment]
Also see "Limb", "Bough", "Bud", and so on.
