### ISSUE TITLE
Incorrect module names when generating a new project

### ISSUE THREAD

**Issue by bhanuone** [hanami/hanami#1205]
I was trying Hanami 2.0.0 beta for my side project. When generating a new project, If the project name ends with a `s` it is being ignored by `hanami new` command.

Eg:
```ruby
bundle exec hanami new rubygems
```
And the generated module name is not consistent with the project name.
`lib/rubygems/types.rb`
```ruby
# frozen_string_literal: true

require "dry/types"

module Rubygem
  Types = Dry.Types

  module Types
    # Define your custom types here
  end
end
```

**Comment by timriley** [comment]
Thanks for testing Hanami and reporting this! I noticed it too just recently - we definitely need to fix this. 

In the meantime, sorry for the inconvenience! Hopefully you were able to do the manual renaming necessary to preserve your intended project name :)

**Comment by jodosha** [comment]
@bhanuone Thanks for reporting. I spotted the problem as well.

**Comment by cllns** [comment]
Fixed by @jodosha in https://github.com/hanami/cli/pull/38

Not released as a gem yet, but it will be soon.
