### ISSUE TITLE
Hanami 2.0 release schedule and Ruby 2.7 EOL

### ISSUE THREAD

**Issue by mtmtcode** [hanami/hanami#1210]
Hi, Hanami Team 🌸 
Thanks for your great work!

I am thinking of upgrading Hanami 1.3 to 2.0.
Could you tell me an estimate of when Hanami 2.0 will be officially released?
Since support for Ruby 2.7 will end in April 2023, I am interested in if Hanami 2.0 is released before then.

**Comment by cllns** [comment]
We can't give an estimate on when it'll be available. We're all volunteering our own time and are balancing other obligations. Thanks for bringing up the EOL of 2.7; that's a great point. I fully expect 2.0 will be released by then.

That said, we have Hanami 2.0.beta.2 out now, so I don't think it's too far away. Note that we'll be releasing Hanami 2.0 without a view or model layer, than release that with Hanami 2.1 soon after.

**Comment by mtmtcode** [comment]
@cllns Thank you for your reply!

I've understood that there is not a definite release schedule.
I know that this project is run by volunteers, and appreciate it very much.
I'm glad that you recognize EOL of Ruby 2.7. I'll try to contribute to this project if I can.
