### ISSUE TITLE
Hacktoberfest 2022

### ISSUE THREAD

**Issue by vcborsolan** [hanami/hanami#1211]
Hello folks, I'm opening this issue to discuss if this repository will participate in the 202 digital ocean [hacktoberfest](https://hacktoberfest.com/participation/#maintainers).

If so, let's review the issues and add the labels/tags for valid contributions.

**Comment by cllns** [comment]
We're not interested in participating in Hacktoberfest. We have a bit more work to do releasing Hanami 2.0 and 2.1 but it's all stuff that requires a lot of context and knowledge about how the various parts of Hanami and dry-rb fit together. There's not any obvious self-contained "low-hanging fruit" tasks right now. I'm afraid that attracting many beginner contributors would be more trouble than it's worth for us right now. 

(Our only previous experience with Hacktoberfest was useless spam, unfortunately: https://github.com/hanami/hanami/pull/1079)

**Comment by sreeram-venkitesh** [comment]
@cllns You mentioned that the tasks right now would require context about how Hanami works. Are there any resources that you'd recommend for new contributors to get involved? Are the documentation and the code the best place to start?

**Comment by cllns** [comment]
No, not currently. There will be plenty of opportunities to contribute once we release 2.0, but until then I'm afraid too much of the context is internal to specific team members for the parts they're specializing in. It'd simply require way too much time to document. Thanks for your interest though!

In the meantime, I'd recommend trying out the latest beta. There's not much documentation complete yet, but you can piece it together from searching on GitHub.

**Comment by sreeram-venkitesh** [comment]
@cllns Thank you!

**Comment by sreeram-venkitesh** [comment]
>There will be plenty of opportunities to contribute once we release 2.0
@cllns Hi! I'm interested in going into Hanami internals and possibly contribute to the project. Are there any opportunities where I can help now that Hanami 2.0 has been released?
