### ISSUE TITLE
hanami new with --hanami-head throws an error

### ISSUE THREAD

**Issue by gregmolnar** [hanami/hanami#1255]
I was trying to generate the sample app with head, but I am getting this error:

```
[~/git/hanami] +(main) bundle exec hanami new bookshelf --hanami-head

ERROR: "hanami new" was called with arguments "bookshelf --hanami-head"
```

**Comment by solnic** [comment]
Thanks for reporting this. Where did you find this option? Current app generator does not support this option.

**Comment by gregmolnar** [comment]
I got it from the Readme: https://github.com/hanami/hanami#how-to-use-hanami-head

**Comment by solnic** [comment]
@gregmolnar ah this is outdated, we'll be updating all README's prior releasing 2.0. I'm gonna close this.
