### ISSUE TITLE
Register rack events on notifications component before attaching middleware

### ISSUE THREAD

**Issue by timriley** [hanami/hanami#1262]
i.e. the same as this patch, but built in:

```ruby
require "dry/system"
require "hanami/providers/rack"

module Hanami
  module Providers
    class Rack < Dry::System::Provider::Source
      module Fixes
        def start
          notifications = target[:notifications]

          notifications.register_event(Dry::Monitor::Rack::Middleware::REQUEST_START)
          notifications.register_event(Dry::Monitor::Rack::Middleware::REQUEST_STOP)
          notifications.register_event(Dry::Monitor::Rack::Middleware::REQUEST_ERROR)

          super
        end
      end

      prepend Fixes
    end
  end
end
```

Will avoid an error like this:

```
     Dry::Events::InvalidSubscriberError:
       you are trying to subscribe to an event: `rack.request.stop` that has not been registered
```

**Comment by solnic** [comment]
Did you manage to figure out *when* this happens?

**Comment by timriley** [comment]
@solnic I haven't whittled it down to a bare bones reproduction, but you _can_ reproduce it inside https://github.com/decafsucks/decafsucks by doing the following:

1. Check out the repo, make sure it's setup, etc.
2. Run `rspec spec/slices/main/features/home_page_spec.rb` and make sure it passes
3. Comment out `require "ext/hanami/providers/rack"` from `config/app.rb`
4. Run `rspec spec/slices/main/features/home_page_spec.rb` again and witness this error:

```
Failures:

  1) Home page Visiting the home page
     Failure/Error: visit "/"

     Dry::Events::InvalidSubscriberError:
       you are trying to subscribe to an event: `rack.request.stop` that has not been registered
     # ./spec/slices/main/features/home_page_spec.rb:8:in `block (2 levels) in <top (required)>'
```

**Comment by timriley** [comment]
@solnic yep, that's exactly right. Given this I'm inclined to just make a fix and merge this, especially before 2.0.1, since I don't want anyone else to be bitten by this.

However, it'd be nice if we could get a test in place to cover this behaviour. It may possibly need to be a full isolation test, I'm not sure. Either way I'm going to get a PR up now and will try spending 30 minutes on figuring out a test.

**Comment by timriley** [comment]
I've discovered the source of the problem inside decafsucks.

It's to do with decafsucks' persistence provider, when it [sets up this rom plugin](https://github.com/decafsucks/decafsucks/blob/8729deada9b6b6706b0e9893f535a198781ba3d0/config/providers/persistence.rb#L14-L16):

```ruby
    rom_config.plugin(:sql, relations: :instrumentation) do |plugin_config|
      plugin_config.notifications = target["notifications"]
    end
```

In the `spec/slices/main/features/home_page_spec.rb` spec that we're running, it's tagged as a `:db` spec, which requires the `spec/support/db.rb` file, which in turn [starts the :persistence provider](https://github.com/decafsucks/decafsucks/blob/8729deada9b6b6706b0e9893f535a198781ba3d0/spec/support/db.rb#LL10).

Then, because this instrumentation plugin is configured, it calls `instrument` on our registered `notifications` object, which calls `Dry::Events::Publisher::InstanceMethods#process`, which creates a new internal `@__bus__` object for the notifications object. When this bus is created, it is done so like this:

```ruby
        def new_bus
          Bus.new(events: events.dup, listeners: listeners.dup)
        end
```

See how we're making dup'ed copies of the events and listeners?

This means that any class-level events registered on `Dry::Monitor::Notifications` _after_ this rom plugin is activated are completely ignored, because our _instance_ of that notifications class already has its bus in memory, and its too late to pass new registered events to it.

This is all due to the `persistence` provider being started _before_ the `rack` provider. (Which _should_ be completely safe to do, BTW, this kind of ordering issue should _not_ be as consequential as it is here).

To show that this is the case, if we:

1. Comment out the `require "ext/hanami/providers/rack"` in `config/app.rb` in decafsucks
2. _Also_ comment out the `rom_config.plugin(:sql, relations: :instrumentation)` line from `config/providers/persistence.rb`
3. Then run the same `spec/slices/main/features/home_page_spec.rb` test, **everything passes**

Given all of this, I think we still to update Hanami's built-in rack provider to register those every events on `notifications` if they're not already registered.

I think I now have enough information to make a failing test. Stand by!

**Comment by timriley** [comment]
PR to fix this along with a test: https://github.com/hanami/hanami/pull/1269
