### ISSUE TITLE
Tutorial quick start broken with Guard

### ISSUE THREAD

**Issue by oz123** [hanami/hanami#1277]
First, I have been watching Hanami for quite a while as it seems like a good entry for ruby ecosystem. 
I am a noob in ruby, so take my comments with a grain of salt, or not. If you care to attract people who are also new to ruby.

I followed the tutorial, on Linux. 
First, most commands on linux require : `bundle exec` prefixed to work.
Second, `bundle exec hanami server` crashes with:
```
 bundler exec hanami server 
22:24:30 - INFO - Bye bye...
22:24:30 - ERROR - No Guardfile exists at Guardfile.
...
```
To work around, I was able to pass the flag:
```
$ bundler exec hanami server --no-code-reloading
[934818] Puma starting in cluster mode...
[934818] * Puma version: 6.0.2 (ruby 3.1.3-p185) ("Sunflower")
[934818] *  Min threads: 5
[934818] *  Max threads: 5
[934818] *  Environment: development
[934818] *   Master PID: 934818
[934818] *      Workers: 2
[934818] *     Restarts: (✔) hot (✖) phased
[934818] * Preloading application
[934818] * Listening on http://0.0.0.0:2300
[934818] Use Ctrl-C to stop
[934818] - Worker 0 (PID: 934821) booted in 0.0s, phase: 0
[934818] - Worker 1 (PID: 934822) booted in 0.0s, phase: 0
...
```
Going to port 2300 in my broswer works.

I was able to create a minimal `Guardfile` and install the dependencies.
```
# cat Guardfile
guard :rubocop do
    watch(%r{.+\.rb$})
     watch(%r{(?:.+/)?\.rubocop(?:_todo)?\.yml$}) { |m| File.dirname(m[0]) }
end
```
Now, I can run `bundle exec hanami server`. However,  port 2300 is no longer accessible, some other random port is opened
but it seems that it isn't hanami server.

```
$ bundler exec hanami server 
22:33:34 - INFO - Using Guardfile at /home/oznt/Software/hanami-tutorial/bookshelf/Guardfile.
22:33:34 - INFO - Inspecting Ruby code style of all files
Inspecting 10 files
CCCCCCCC.C

...
10 files inspected, 40 offenses detected, 38 offenses autocorrectable
22:33:35 - INFO - Guard is now watching at '/home/oznt/Software/hanami-tutorial/bookshelf'
```
Puma isn't starting for some reason. 

I would appreciate some help.

**Comment by jodosha** [comment]
@oz123 Thanks for trying Hanami.

To ensure the app has the correct setup, run `bundle exec hanami install`. This command is automatically ran when you create a new app.
