### ISSUE TITLE
SliceConfigurable module detects wrong slice due to partial match

### ISSUE THREAD

**Issue by m-dwyer** [hanami/hanami#1299]
# Issue

If we create two similarly named slices, where one slice's name is the subset of another, then an action will be 'configured for' the wrong slice.  This causes issues elsewhere -- e.g. hanami-view, which will try to replace the slice name in the templates path to correctly load the correct template for a given view

# Replication

1. `hanami new bookshelf`
2. `cd bookshelf`
3. create our first slice with `hanami generate slice ExternalAPI`
4. create our second slice with `hanami generate slice API`
5. create a show action for the books controller within ExternalAPI slice: `hanami generate action books.show --slice=ExternalAPI`
6. create a show action for the coins controller within the API slice: `hanami generate action coins.show --slice=API`
7. Load the console with `hanami console`

Now, if we inspect `@configured_for_slices` on the books.show action, which belongs to the ExternalAPI slice, we see it shows the API slice:

```
bookshelf[development]> ExternalAPI::Actions::Books::Show.instance_variable_get(:@configured_for_slices)
=> [Bookshelf::App, API::Slice]
```

The issue appears to be here: https://github.com/hanami/hanami/blob/b73ad93534a2b5402d34dc365fe5fcbea52e8cbd/lib/hanami/slice_configurable.rb :

```
slices.detect { |slice| klass.name.include?(slice.namespace.to_s) }
```

Because klass name `ExternalAPI::Actions::Books::Show` contains `API`, which is a valid but separate slice, then the wrong slice is chosen.

**Comment by timriley** [comment]
Ah yes, nice find @m-dwyer! I can look into sorting this out, but I'd also be happy to take PRs if you're interested in working on a fix?
