### ISSUE TITLE
Setting instance variables durying request lifecycle

### ISSUE THREAD

**Issue by Drowze** [hanami/hanami#1300]
Hello :wave:

While working with Hanami 2 I've come across to something that I want to migrate to Hanami 2 and looks like following snippet:
```ruby
module AuthHelpers
  def authenticate_user!
    if Auth::User.call(params)
      @current_user = User.find(params[:user_id])
    else
      halt(401, { message: "Authorization fail!" })
    end
  end
end
```

And an action using the above module like this:
```ruby
module Api
  module Controllers
    class MyController
      include Api::Controller
      include AuthHelpers

      before :authenticate_user!

      def call
        # foo
      end
    end
  end
end
```

When migrating the above (which was in Hanami 1), I've initially came to something like the following:
```ruby
module AuthHelpers
  def authenticate_user!(request, _response)
    params = request.params
    if Auth::User.call(params)
      @current_user = User.find(params[:user_id])
    else
      halt(401, { message: "Authorization fail!" })
    end
  end
end

module API
  module Actions
    class MyAction < Action
      include AuthHelpers

      before :authenticate_user!

      def handle(request, response)
        # foo
      end
    end
  end
end
```

...but the above actually always raise an error (`FrozenError: can't modify frozen API::Actions::MyAction`.
Is there a recommended way for a method to define some state within the request lifecycle, so I can e.g. set `current_user` within an arbitrary method (other than `handle`)?

**Comment by wuarmin** [comment]
You can do something like this:

```ruby
class Show < Hanami::Action
  before { |req, res| res[:current_user] = User.find(req.params[:user_id]) }

  def call(*)
  end
end
```

**Comment by Drowze** [comment]
That's nice! I didn't see any mention to it on the official guide (for v2), but now I see it mentioned (and called _exposures_) right on the [hanami-controller README](https://github.com/hanami/controller#exposures)

I'm sure this will go on the official guide too once the views update is released - so no worries whatsoever :)

Closing this issue - thank you for bringing this to me @wuarmin 😄
