### ISSUE TITLE
Not found route returns 500 instead of 404

### ISSUE THREAD

**Issue by jodosha** [hanami/hanami#1327]
This is a bug.

```shell
⚡ curl -I http://localhost:2300/foo
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
Set-Cookie: BetterErrors-2.9.1-CSRF-Token=71b3287d-ea5a-4b9e-bdc2-75499809da59; path=/; HttpOnly; SameSite=Strict
Content-Length: 2455
```

When visiting in the browser, the web console indicates that the offending line is: https://github.com/hanami/hanami/blob/7cfdd344e1cba12bc7727cc0a69d5038b88c9cae/lib/hanami/slice.rb#L990

**Comment by mzishtiaq** [comment]
Hi @jodosha, I wanted to take a crack at it but I have been unable to reproduce the issue. My steps were the following:

```
gem install hanami
```
```
hanami new bookshelf
cd bookshelf && bundle
bundle exec hanami server
```
```
curl -I http://localhost:2300/foo 
  -H "Content-Type: text/plain; charsert=utf-8" 
```
I get the following response:
```
HTTP/1.1 404 Not Found
Content-Length: 9
```
Visiting `http://localhost:2300/foo` from the browser also simply returns `Not Found`. Please do let me know if I should be doing something else to reproduce the issue.

**Comment by timriley** [comment]
The issue here is with our new support in the main branch for rendering errors. I'm taking a look into it too.
