### ISSUE TITLE
Could not find gem 'hanami-router (~> 2.1.0.rc)'

### ISSUE THREAD

**Issue by LFDMCreations** [hanami/hanami#1363]
Installing and trying to run the RC that was release yesterday November 1, `bundle install` fails : 

`Could not find gem 'hanami-router (~> 2.1.0.rc)'`

**Comment by LFDMCreations** [comment]
@jodosha 
This is fixed, but now running into this:

```
❯ bundle exec hanami dev
/Users/thiebo/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/open3.rb:222:in `spawn': No such file or directory - bin/dev (Errno::ENOENT)
	from /Users/thiebo/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/open3.rb:222:in `popen_run'
	from /Users/thiebo/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/open3.rb:103:in `popen3'
	from /Users/thiebo/.rvm/gems/ruby-3.2.1/gems/hanami-cli-2.1.0.rc1/lib/hanami/cli/interactive_system_call.rb:26:in `block in call'
	from /Users/thiebo/.rvm/gems/ruby-3.2.1/gems/bundler-2.4.21/lib/bundler.rb:411:in `block in with_unbundled_env'
	from /Users/thiebo/.rvm/gems/ruby-3.2.1/gems/bundler-2.4.21/lib/bundler.rb:657:in `with_env'
	from /Users/thiebo/.rvm/gems/ruby-3.2.1/gems/bundler-2.4.21/lib/bundler.rb:411:in `with_unbundled_env'
	from /Users/thiebo/.rvm/gems/ruby-3.2.1/gems/hanami-cli-2.1.0.rc1/lib/hanami/cli/interactive_system_call.rb:21:in `call'
	from /Users/thiebo/.rvm/gems/ruby-3.2.1/gems/hanami-cli-2.1.0.rc1/lib/hanami/cli/commands/app/dev.rb:27:in `call'
	from /Users/thiebo/.rvm/gems/ruby-3.2.1/gems/hanami-cli-2.1.0.rc1/lib/hanami/cli/commands/app/command.rb:40:in `call'
	from /Users/thiebo/.rvm/gems/ruby-3.2.1/gems/dry-cli-1.0.0/lib/dry/cli.rb:116:in `perform_registry'
	from /Users/thiebo/.rvm/gems/ruby-3.2.1/gems/dry-cli-1.0.0/lib/dry/cli.rb:65:in `call'
	from /Users/thiebo/.rvm/gems/ruby-3.2.1/gems/hanami-cli-2.1.0.rc1/exe/hanami:11:in `<top (required)>'
	from /Users/thiebo/.rvm/gems/ruby-3.2.1/bin/hanami:25:in `load'
	from /Users/thiebo/.rvm/gems/ruby-3.2.1/bin/hanami:25:in `<main>'
	from /Users/thiebo/.rvm/gems/ruby-3.2.1/bin/ruby_executable_hooks:22:in `eval'
	from /Users/thiebo/.rvm/gems/ruby-3.2.1/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by jodosha** [comment]
@LFDMCreations Did you run `bundle exec hanami install`?

**Comment by swilgosz** [comment]
@LFDMCreations i guess it should be `bundle exec hanami server`?

By default it will start in dev environment.

**Comment by LFDMCreations** [comment]
> @LFDMCreations Did you run `bundle exec hanami install`?

yes I did

**Comment by LFDMCreations** [comment]
> @LFDMCreations i guess it should be `bundle exec hanami server`?
> 
> By default it will start in dev environment.

That was the trick. But [here](https://hanamirb.org/blog/2023/11/01/hanami-210rc1/#how-can-i-try-it-) is says `bundle exec hanami dev`

**Comment by timriley** [comment]
Hi @LFDMCreations! Thanks very much for testing Hanami and reporting your issues here, they're **extremely** helpful to us as we prepare for our stable release! ❤️ 

I'm glad we have the issue of the missing gems sorted for you, but I'd love to learn a bit more about what's causing your issue with running `hanami dev`.

I've tried to replicate this issue locally. I have:

1. Installed the latest Hanami gem: `gem install hanami --pre` (which brings down 2.1.0.rc1)
2. Generated a new app: `hanami new hrc1`
3. Fixed up an issue with our node package version: updating `package.json` to include `"hanami-assets": "^2.1.0-rc.1"` and then running `npm i` (we're already sorting out a fix for this) 
4. Then inside the app, run `bundle exec hanami dev`

At that point, everything works. Here's the output I get:

```
> bundle exec hanami dev

10:09:44 web.1    | started with pid 23273
10:09:44 assets.1 | started with pid 23274
10:09:45 assets.1 | [watch] build finished, watching for changes...
10:09:45 web.1    | 10:09:45 - INFO - Using Guardfile at /Users/tim/Source/scratch/hrc1/Guardfile.
10:09:45 web.1    | 10:09:45 - INFO - Puma starting on port 2300 in development environment.
10:09:45 web.1    | 10:09:45 - INFO - Guard is now watching at '/Users/tim/Source/scratch/hrc1'
10:09:45 web.1    | Puma starting in single mode...
10:09:45 web.1    | * Puma version: 6.4.0 (ruby 3.2.0-p0) ("The Eagle of Durango")
10:09:45 web.1    | *  Min threads: 5
10:09:45 web.1    | *  Max threads: 5
10:09:45 web.1    | *  Environment: development
10:09:45 web.1    | *          PID: 23300
10:09:45 web.1    | * Listening on http://0.0.0.0:2300
10:09:45 web.1    | * Starting control server on http://127.0.0.1:9293
10:09:45 web.1    | * Starting control server on http://[::1]:9293
10:09:45 web.1    | Use Ctrl-C to stop
```

So (aside from the bug I had to fix along the way), things are looking right for brand new generated Hanami 2.1.0 apps.

So this leads me to ask: are you _upgrading_ an existing app? If so, this could be the issue. The `bin/dev` file (and the corresponding change to `hanami dev`) was introduced in 2.1.0.rc1.

To fix this, create this `bin/dev` file and mark it as executable:

```
#!/usr/bin/env sh

if ! gem list foreman -i --silent; then
  echo "Installing foreman..."
  gem install foreman
fi

exec foreman start -f Procfile.dev "$@"
```

That should get you going again.

If you're working with assets, you'll probably also want to generate a `config/assets.mjs`:

```
import * as assets from "hanami-assets";

await assets.run();

// To provide additional esbuild (https://esbuild.github.io) options, use the following:
//
// await assets.run({
//   esbuildOptionsFn: (args, esbuildOptions) => {
//     // Add to esbuildOptions here. Use `args.watch` as a condition for different options for
//     // compile vs watch.
//
//     return esbuildOptions;
//   }
// });
```

And add this line in the scripts section of your `package.json`:

```
  "scripts": {
    "assets": "node config/assets.mjs"
  },
```

This should bring in all the pieces we introduced with rc1.

(FYI: we're also considering adjusting the file extension from `.mjs` to just plain `.js` before the final 2.1.0 release)

Sorry for the bumpiness of this, but I'm very grateful you're testing things, it helps a lot!

Could you please take a look at the above and see if it will fix your issue? I'm happy to keep working through this with you until everything's up and running properly.

**Comment by timriley** [comment]
>  http://localhost:2300still shows the "welcome to hanami" line on a bank page, not the new welcome page that is announced.

I forgot to address this. In the app I generated via the steps above, the welcome screen displayed as expected.

Can you share me your `config/routes.rb`? Here's mine:

```
module Hrc1
  class Routes < Hanami::Routes
    # Add your routes here. See https://guides.hanamirb.org/routing/overview/ for details.
  end
end
```

The welcome screen will only show when the routes are empty. If you're upgrading a previous app, you may still have the default root route with the plain welcome string that we used to generate. If you remove this, you should see the welcome screen.

**Comment by LFDMCreations** [comment]
I'm not upgrading, but installed from scratch following the hanamirb page. 
This is my `routes.rb`
```
# frozen_string_literal: true

module Playapp
  class Routes < Hanami::Routes
    root { "Hello from Hanami" }
  end
end
```
and with the `root`line commented out, I get the new welcome screen.

**Comment by timriley** [comment]
Thanks for this extra info, @LFDMCreations.

If you had a `config/routes.rb` generated with the "Welcome to Hanami" string, _and_ you were missing a `bin/dev` file and `config/assets.mjs` and so on, then this means you ran `hanami new` using 2.1.0.beta2, not 2.1.0.rc1.

If you uninstall your hanami gem and reinstall it via `gem install hanami --pre` and ensure it's 2.1.0.rc1 installed, then everything should be fine if you generate another app (though you'll need to do that `package.json` fix I did in my step 3 above).

**Comment by LFDMCreations** [comment]
@timriley, with pleasure :)

I uninstalled all hanami-related gems and all versions of it and then : 

```
❯ gem install hanami --pre
❯ hanami new hrc1
❯ cd hrc1
❯ bundle install
Fetching gem metadata from https://rubygems.org/...............
Resolving dependencies...
Installing puma 6.4.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
                     **_[cut for brievity]_**
An error occurred while installing puma (6.4.0), and Bundler cannot continue.

In Gemfile:
  puma
❯ bundle exec hanami install
Updated /Users/thiebo/Code/Ruby/play/hrc1/Gemfile
❯ bundle
❯ bundle exec hanami dev
```
At this point the output is :

```
16:13:06 web.1    | started with pid 3801
16:13:06 assets.1 | started with pid 3802
16:13:07 web.1    | 16:13:07 - INFO - Using Guardfile at /Users/thiebo/Code/Ruby/play/hrc1/Guardfile.
16:13:07 assets.1 | node:internal/modules/esm/resolve:844
16:13:07 assets.1 |   throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
16:13:07 assets.1 |         ^
16:13:07 assets.1 |
16:13:07 assets.1 | Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'hanami-assets' imported from /Users/thiebo/Code/Ruby/play/hrc1/config/assets.mjs
16:13:07 assets.1 |     at packageResolve (node:internal/modules/esm/resolve:844:9)
16:13:07 assets.1 |     at moduleResolve (node:internal/modules/esm/resolve:901:20)
16:13:07 assets.1 |     at defaultResolve (node:internal/modules/esm/resolve:1121:11)
16:13:07 assets.1 |     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
16:13:07 assets.1 |     at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
16:13:07 assets.1 |     at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
16:13:07 assets.1 |     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
16:13:07 assets.1 |     at link (node:internal/modules/esm/module_job:84:36) {
16:13:07 assets.1 |   code: 'ERR_MODULE_NOT_FOUND'
16:13:07 assets.1 | }
16:13:07 assets.1 |
16:13:07 assets.1 | Node.js v21.1.0
16:13:07 web.1    | 16:13:07 - INFO - Puma starting on port 2300 in development environment.
16:13:07 web.1    | 16:13:07 - INFO - Guard is now watching at '/Users/thiebo/Code/Ruby/play/hrc1'
16:13:07 web.1    | Puma starting in single mode...
16:13:07 web.1    | * Puma version: 6.3.0 (ruby 3.2.1-p31) ("Mugi No Toki Itaru")
16:13:07 web.1    | *  Min threads: 5
16:13:07 web.1    | *  Max threads: 5
16:13:07 web.1    | *  Environment: development
16:13:07 web.1    | *          PID: 3831
16:13:07 web.1    | * Listening on http://0.0.0.0:2300
16:13:07 web.1    | * Starting control server on http://127.0.0.1:9293
16:13:07 web.1    | * Starting control server on http://[::1]:9293
16:13:07 assets.1 | exited with code 1
16:13:07 system   | sending SIGTERM to all processes
16:13:07 web.1    | Use Ctrl-C to stop
16:13:07 web.1    | terminated by SIGTERM
```
`npm install` returns : 

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for hanami-assets@^2.1.0-rc1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in: /Users/thiebo/.npm/_logs/2023-11-05T15_20_32_909Z-debug-0.log
```

**Comment by jodosha** [comment]
@LFDMCreations As @timriley mentioned above:
> Fixed up an issue with our node package version: updating package.json to include "hanami-assets": "^2.1.0-rc.1" and then running npm i (we're already sorting out a fix for this)

We had a bug in `hanami-cli`: https://github.com/hanami/cli/pull/119
