### ISSUE TITLE
"no implicit conversion of Symbol into String" error when using `format :json` on fresh install of Hanami 2.1

### ISSUE THREAD

**Issue by Gwash3189** [hanami/hanami#1376]
Hi!

Thank you for all of your hard work on Hanami. 

In my initial fiddling with actions, I configured an action to always set the format to `:json`. However, in doing so I received a `no implicit conversion of Symbol into String` error. 

This happened on a fresh install of Hanami 2.1. 

Please see the attached screenshot for all of the moving parts in this example: 
![Screen Shot 2024-03-10 at 10 20 00 am](https://github.com/hanami/hanami/assets/3042264/78098b37-3826-4590-9ca2-af030024a61e)

**Comment by timriley** [comment]
Hi @Gwash3189, thanks for reporting this. I see you've also marked it as closed. Is this still an issue for you? Or something you managed to figure out?
