### ISSUE TITLE
[Documentation] FAQ + small snippets collection

### ISSUE THREAD

**Issue by rubyFeedback** [hanami/hanami#1378]
Hey there Tim,

Just read that you are now maintaining the Hanami stack.

If you feel motivated and have time, could you perhaps add/extend a FAQ (in regards to hanami),
as well add/extend a snippets collection?

I settled for sinatra years ago, largely because it is super-simple, and rails was too big to learn
(for me). I am quite happy with sinatra, but there are a LOT of things missing in sinatra too.

hanami is not quite "sinatra-spirited" either, I think, as it is more leaning towards a rails-like
approach, but hanami also seems easier and simpler, so perhaps there is hope it can sit
a bit in between sinatra and rails (in regards to complexity).

At any rate, perhaps you could divvy up some of your time in the coming months to add and
extend FAQ / snippet collection in regards to hanami. Really fairly simple things, that are common
in the web-ecosystem, aka "show these files", "send those files to the user", "how to add and
remove entries to a simple user database" and small tasks that relate to this. Not basic ruby
things, but basic things from hanami's use case. I did go through the hanami tutorial before,
but I learn most from FAQ + simple usage examples (as well as standalone .rb files to
poke and see how things work, ideally with a bit of documentation and examples). As my 
own attention span is one of a squirrel on a nut rush, my brain kind of zones out after 
a fairly short time (which is another reason why I was somewhat successful with regard
to sinatra - I could learn day by day in tiny steps, which helps a LOT).

Anyway, this is not a great issue request, as it may take time, so please do feel free to 
close it at any moment in time, just keeping in mind to also improve the documentation
whenever possible - we downstream folks need tons of useful documentation.

**Comment by timriley** [comment]
Thanks for the feedback, @rubyFeedback. We're always interested in improving our documentation, and we'll continue to do our best as the framework evolves.
