### ISSUE TITLE
Automatically adjust database URL in test mode

### ISSUE THREAD

**Issue by timriley** [hanami/hanami#1395]
See details at top of https://discourse.hanamirb.org/t/integrating-rom-into-hanami-2-2/971/2

**Comment by alassek** [comment]
@timriley I am running into a lot of trouble figuring out how to test this.

The unit tests were easy enough, but integration testing this is going to require adding all the supported databases to the test matrix. Is this something that you were planning on doing?

Running `#prepare` on the DB provider with a connection URL is going to require actually opening the connection when `ROM.setup` is called.

**Comment by timriley** [comment]
@alassek I don't think we should worry about testing all databases in CI. The unit tests over in hanami-db give us confidence that we cover the different URL schemes for the different databases we care about.

To test this in hanami/hanami, I think we just want one integration-style test that makes sure the framework is calling the database naming logic over in hanami-db. I think a test for a single SQLite-using app would be enough for now, just like we're doing for our other tests.

I do think we'll eventually want to add real working database servers into a test matrix (Before or after 2.2? I think this is open for debate!). In the meantime, if we can defer this for just a little while longer, it'll allow us to more quickly move through the rest of our work on establishing the database layer in the first place.

**Comment by timriley** [comment]
So while I think we can get away with just SQLite for testing this feature in hanami/hanami, I think I spoke too soon for our efforts more generally: I've just hit this same issue looking to test `db structure dump` in hanami/cli. And in that case I think it's important our tests actually exercise a real Postgres database. So I'm going to investigate getting a proper test setup over there.

(In the future I'd really like to merge hanami/cli and hanami/hanami somehow. It would help us avoid a lot of repetition in our testing, not to mention make it easier for the CLI and the core framework to evolve more gracefully together).
