### ISSUE TITLE
Expand default set of Sequel extensions

### ISSUE THREAD

**Issue by timriley** [hanami/hanami#1409]

**Comment by alassek** [comment]
@timriley What did you have in mind here? This definitely needs to be db-specific.

General extensions I use:
- `connection_validator` for our k8s readiness probes
- `error_sql` adds current SQL query to exceptions for diagnosis

PostgreSQL extensions:
- `pg_array` supports array types
- `pg_json` supports json/jsonb types

It also needs to be possible to add to this through configuration for app-specific things (I forget if this is already supported). I use `new_relic_instrumentation` for APM and `ksuid` for KSUID identifiers.

**Comment by alassek** [comment]
@cllns that is a good callout, although might relate more to #1389 or deserve its own issue.

The DIY approach ROM takes to timestamps is a poor user experience for something people take for granted coming from Rails. We should have turnkey support for this.

**Comment by timriley** [comment]
@alassek So yep, I think we'll want some way to provide a set of defaults that is specific (a) per adapter, and (b) in the case of sql, per database type.

Users should be able to add their own extensions to this default set in a simple way.

Users should also be able to _clear_ the default set for their given adapter/database type, if they want to exercise full control.

Is that enough for you to have a go at this? I think this is the kind of thing where the ideal solution will become clearer after having a few runs at it in code, so getting even _something_ down would be a good start for us :)

**Comment by dcr8898** [comment]
FWIW, is use the `uuid-ossp` extension for UUID generation, and the `pg_trgm` extension to provide trigram functions I use to improve full-text search.
