### ISSUE TITLE
Automatically include ROM extension for operations used inside Hanami apps

### ISSUE THREAD

**Issue by timriley** [hanami/hanami#1437]
Eliminate this little line of boilerplate, which we (temporarily) introduce in https://github.com/hanami/cli/pull/180.

```ruby
include Dry::Operation::Extensions::ROM
```

**Comment by krzykamil** [comment]
Not sure if I understand what this task means? We don't want this as it is included now, but in general we want the extension to be included? That means that every operation inside Hanami app (that has a database), includes this extension, but does not do it explicitly as in the linked code (co the include statement is hidden inside the base operation or something)?

**Comment by cllns** [comment]
Yes, the ROM extension (which provides `transaction do .. end` helper), should automatically be included in dry-operations, so we can remove that line of boilerplate

**Comment by timriley** [comment]
In practice, this will be added something to `lib/hanami/extensions/` to handle the extension of dry-operation classes.

This will be a fairly small thing to do, and I'm happy to take care of it.

**Comment by krzykamil** [comment]
Yea, given my lack of knowledge of the Hanami internals on this level and dry-operation it would probably take me more time just to figure out how to include it properly, than for you to start and finish it :)
