### ISSUE TITLE
Fix deprecation warnings that show when running a Hanami app on Ruby 3.3.5

### ISSUE THREAD

**Issue by timriley** [hanami/hanami#1454]
Generating a Hanami app on Ruby 3.3.5 and then running `bundle exec hanami dev` gives the following output:

```
23:19:54 web.1    | started with pid 1004
23:19:54 assets.1 | started with pid 1005
23:19:54 web.1    | /Users/tim/.local/share/mise/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/dry-core-1.0.1/lib/dry/core/deprecations.rb:3: warning: logger was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
23:19:54 assets.1 | /Users/tim/.local/share/mise/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/dry-core-1.0.1/lib/dry/core/deprecations.rb:3: warning: logger was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
23:19:54 web.1    | You can add logger to your Gemfile or gemspec to silence this warning.
23:19:54 assets.1 | You can add logger to your Gemfile or gemspec to silence this warning.
23:19:54 web.1    | /Users/tim/.local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/json/generic_object.rb:2: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
23:19:54 assets.1 | /Users/tim/.local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/json/generic_object.rb:2: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
23:19:54 web.1    | You can add ostruct to your Gemfile or gemspec to silence this warning.
23:19:54 assets.1 | You can add ostruct to your Gemfile or gemspec to silence this warning.
23:19:54 assets.1 | [sunday_beta] [watch] build finished, watching for changes...
23:19:55 web.1    | /Users/tim/.local/share/mise/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/guard-2.18.1/lib/guard.rb:2: warning: logger was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
23:19:55 web.1    | You can add logger to your Gemfile or gemspec to silence this warning.
23:19:55 web.1    | /Users/tim/.local/share/mise/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/guard-2.18.1/lib/guard/cli.rb:5: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
23:19:55 web.1    | You can add ostruct to your Gemfile or gemspec to silence this warning.
23:19:55 web.1    | 23:19:55 - INFO - Using Guardfile at /Users/tim/Source/scratch/sunday_beta/Guardfile.
23:19:55 web.1    | 23:19:55 - INFO - Puma starting on port 2300 in development environment.
23:19:55 web.1    | 23:19:55 - INFO - Guard is now watching at '/Users/tim/Source/scratch/sunday_beta'
23:19:55 web.1    | Puma starting in single mode...
23:19:55 web.1    | * Puma version: 6.4.2 (ruby 3.3.5-p100) ("The Eagle of Durango")
23:19:55 web.1    | *  Min threads: 5
23:19:55 web.1    | *  Max threads: 5
23:19:55 web.1    | *  Environment: development
23:19:55 web.1    | *          PID: 1013
23:19:55 web.1    | /Users/tim/.local/share/mise/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/dry-core-1.0.1/lib/dry/core/deprecations.rb:3: warning: logger was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
23:19:55 web.1    | You can add logger to your Gemfile or gemspec to silence this warning.
23:19:55 web.1    | /Users/tim/.local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/json/generic_object.rb:2: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
23:19:55 web.1    | You can add ostruct to your Gemfile or gemspec to silence this warning.
23:19:56 web.1    | * Listening on http://0.0.0.0:2300
23:19:56 web.1    | * Starting control server on http://127.0.0.1:9293
23:19:56 web.1    | * Starting control server on http://[::1]:9293
23:19:56 web.1    | Use Ctrl-C to stop
```

So many deprecation warnings! We'll need to hunt these down and address them all (some of these maybe changes directly in hanami or dry-rb gems; others may require changes or depending on newer versions of other gems).

**Comment by cmattson** [comment]
Currently working on this; I'll have a PR in once I've verified it against older Rubies.

**Comment by timriley** [comment]
Thank you, @cmattson! How've you been going with this?

**Comment by cmattson** [comment]
Working through some GitHub auth issues, but otherwise it seems to be nailed down! Details (hopefully) incoming shortly.

**Comment by timriley** [comment]
Hi @cmattson — I'm glad to hear you've been able to address the warnings! I'm sorry to bother you again so soon, but is there any chance you might be able to share the changes? If you're having GitHub issues, I'd be more than happy to do something creative here, like you email me zips of the git repos directly (or something else).

Reason I'm following up again is because we're on a fairly tight timeline for getting 2.2 out. We're aiming for a 2.2.0.rc1 release Tuesday next week, and the final release the week after. I'd like it if we could get these deprecation warnings sorted before rc1.

Thank you again! ❤

**Comment by timriley** [comment]
I've started tracking these down.

The issue with guard has been fixed, but not released. [Left a request](https://github.com/guard/guard/pull/994#issuecomment-2441396515) on the related PR about whether a release might be possible.

**Comment by timriley** [comment]
Related dry-core fix: https://github.com/dry-rb/dry-core/pull/82

**Comment by timriley** [comment]
What's left is the warnings from within the json gem. The only way I think we can solve them is by putting this into the generated `Gemfile`:

```
gem "json"
```

After doing this and running `bundle update`, we get a version of the json gem with the ostruct usage fixed (looks like [this was done in 2.7.2](https://github.com/ruby/json/blob/844a6633ab7718eb228ca0b2ce3445709cefc292/CHANGES.md#2024-04-04-272)).

_Without_ this line, we get the version of json bundled with Ruby 3.3.x, [which is 2.7.1](https://stdgems.org/json/#gem-version), the version _before_ the fix was introduced.

What we _could_ choose to do is check the RUBY_VERSION inside the `hanami new` generator and _only_ add `gem "json"` to the `Gemfile` if the user is on a version of Ruby that's printing the warnings. We can add a comment explaining why the line is there, too.

This way the user gets the best first impression, and its clear that they can remove the line from the `Gemfile` once they get to Ruby 3.4.0.

Thoughts? @cllns, @alassek?

**Comment by alassek** [comment]
@timriley I agree that we should detect whether it's necessary to inject the gem line, but I think we should use `Gem.loaded_specs` instead of `RUBY_VERSION`.

```ruby
Gem.loaded_specs.key?("json") && Gem.loaded_specs["json"].version <= Gem::Version.new("2.7.1")
```

**Comment by cllns** [comment]
Could we add `ostruct` (any version) instead of a specific version of `json`? It seems like that's what the other PR's that reference https://github.com/ruby/json/pull/565 have done

**Comment by timriley** [comment]
Released dry-core 1.0.2 with https://github.com/dry-rb/dry-core/pull/82 incorporated.

**Comment by timriley** [comment]
And we also have [a new release of guard out](https://github.com/guard/guard/pull/994#issuecomment-2442600418), just for us!

**Comment by timriley** [comment]
> Could we add `ostruct` (any version) instead of a specific version of `json`? It seems like that's what the other PR's that reference [ruby/json#565](https://github.com/ruby/json/pull/565) have done

@cllns This would certainly make sense if we actually used ostruct, somewhere, but were depending implicitly on the json gem to load it for us, which it will soon stop doing. See e.g. https://github.com/ruby-grape/grape-swagger-rails/pull/116 as an example of one of the PRs linked from https://github.com/ruby/json/pull/565 doing just that.

We have a different situation. We don't use ostruct anywhere, so we don't require it. Instead, we (or one of our dependencies) does a `require "json"` as part of the Hanami app booting, and the version of JSON bundled with Ruby 3.3 does a `require "ostruct"` without ostruct explicitly being part of its gemspec. As of Ruby 3.3.5, this prints a warning. This is a bug in the json gem, which is why they've fixed it. But because it's a bundled gem, we'll need to be explicit about using a newer version, via the line in the `Gemfile`.

This is what will help us avoid the warning and give our users the best first impression of Hanami. Having an extra line in the Gemfile (and an explanatory comment) feels like a fair tradeoff for this. Plus, that line can be removed once on Ruby 3.4.0.

_thinks for a minute_ 🤔 

Actually, this thought just struck me — could we ensure the right version of JSON is used by including json as a gemspec dependency in whichever of our own gems requires it? It would be for [one or all of these gems with a require "json" in its lib/ dir](https://github.com/search?q=%22require+%5C%22json%5C%22%22+org%3Ahanami+path%3Alib&type=Code&ref=advsearch&l=&l=). Since we use it in hanami/hanami, maybe that's a good place as any to start...

**Comment by timriley** [comment]
I also noticed that pry is a source of one of these warnings:

```
23:11:05 web.1    | /Users/tim/.local/share/mise/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/pry-0.14.2/lib/pry.rb:31: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
```

They have an open issue about it: https://github.com/pry/pry/issues/2328

And here's the PR where the ostruct usage was removed: https://github.com/pry/pry/pull/2307

And here's another PR where the maintainer promises a release soon: https://github.com/pry/pry/pull/2319

Since pry is a transitive dependency of ours (through guard), I'm a little reluctant to pile on in that PR. I'll give it another couple of weeks.

**Comment by timriley** [comment]
With https://github.com/hanami/reloader/pull/30 and https://github.com/hanami/hanami/pull/1469 merged and dry-core released with https://github.com/dry-rb/dry-core/pull/82 incorporated, we've done everything in our control to eliminate these warnings.

All that's left is for pry to make a release.

I'm going to mark this issue as closed now.

**Comment by andrehjr** [comment]
@timriley Just released a new version of pry!
