### ISSUE TITLE
Fix DB provider unused gateway variable warning

### ISSUE THREAD

**Issue by bkuhlmann** [hanami/hanami#1455]
## Why

Hello. :wave: I'm getting the following Ruby warning when running Hanami, Beta 2 locally:

``` 
/frum/versions/3.3.5/lib/ruby/gems/3.3.0/gems/hanami-2.2.0.beta2/lib/hanami/providers/db.rb:206: warning: assigned but unused variable - gateway
```

## How

The issue is with this [line](https://github.com/hanami/hanami/blob/main/lib/hanami/providers/db.rb#L206) because `gateway` is being set as a local variable but never used. To fix, you'd only need to delete the local variable.

## Notes

:bulb: Using the following RSpec configuration would help catch these warnings sooner:

``` ruby
RSpec.configure do |config|
  config.warnings = true
end
```

**Comment by timriley** [comment]
Thanks @bkuhlmann, addressed now.
