### ISSUE TITLE
Copy gateway config from parent slice DB provider

### ISSUE THREAD

**Issue by timriley** [hanami/hanami#1457]

**Comment by alassek** [comment]
@timriley Another aspect of this that I didn't resolve in hanami/hanami#1450 is: do we care about parsing the query params out of the URL? Currently, I think they are all combined in the Sequel gateway and options set in Ruby should take precedence, so leaving it like that is an option.

It might be nice to see these options explicitly exposed in `Gateway#options` though.

**Comment by timriley** [comment]
> Do we care about parsing the query params out of the URL? Currently, I think they are all combined in the Sequel gateway and options set in Ruby should take precedence, so leaving it like that is an option.

@alassek Thanks for bringing this up! I think that leaving the options where they originated (i.e. do not try and translate them from a URL string into a hash) is the right way to start. It:

- Keep things easier to understand: the database URL remains the exact string they supply
- By preserving the URL and not attempting to translate its options to a hash, we keep things simpler internally, and decrease our risk of bugs

I think it's a good idea to think about for the future, though. Maybe once we have more apps using 2.2 which can help with testing of subsequent improvements.
