### ISSUE TITLE
new hanami executable on windows

### ISSUE THREAD

**Issue by dsisnero** [hanami/hanami#1466]
I removed all my hanami gems and reinstalled with gem install hanami --pre.  For some reason - it doesn't have the windows hanami executable

```
C:\windows_home\src\dsisnero\ruby_repos>gem install hanami --pre
Successfully installed hanami-2.2.0.rc1
Done installing documentation for hanami after 0 seconds
1 gem installed

C:\windows_home\src\dsisnero\ruby_repos>hanami new bookshelf
'hanami' is not recognized as an internal or external command,
operable program or batch file.

C:\windows_home\src\dsisnero\ruby_repos>gem list hanami

*** LOCAL GEMS ***

hanami (2.2.0.rc1)
hanami-cli (2.2.0.rc1)
hanami-utils (2.2.0.rc1)

C:\windows_home\src\dsisnero\ruby_repos>
```

**Comment by timriley** [comment]
Hi @dsisnero, thanks for your help with Windows testing 💚

In this case, it looks like hanami installed but not hanami-cli? It's actually hanami-cli that provides the hanami executable. 

It is a dependency of the hanami gem, so it _should_ install when you run `gem install hanami`. Would you mind checking if it's installed?

**Comment by dsisnero** [comment]
uninstalled all hanami* and tried again- got it working. 

`bundle exec dev` 
still not working
`bundle exec server`
works
