### ISSUE TITLE
`hanami new app` results in constant conflicts

### ISSUE THREAD

**Issue by KieranP** [hanami/hanami#1472]
Using `app` as the application name results in constant conflicts:

Default from `hanami generate repo users`:

```ruby
module App
  module Repos
    class UserRepo < App::DB::Repo
    end
  end
end
```

Conflict:

```
/home/kieran/app/app/repos/user_repo.rb:5:in `<module:Repos>': uninitialized constant App::App::DB (NameError)
    class UserRepo < App::DB::Repo
                        ^^^^
```

Reason:

App::DB::Repo will search for nearest parent App, which in this case is App::App. So it tries to user `App::App::DB::Repo` which doesn't exist.

Fix:

Either:
1) Block any of Hanami's modules/class names from being used as an application name
or
2) Change default migrations to start search from top level using :: , e.g.

```ruby
module App
  module Repos
    class UserRepo < ::App::DB::Repo
      # Add this:    ^^
    end
  end
end
```

**Comment by cllns** [comment]
Ah, yea that makes sense.

I think **1.** is the better option. Using `App` as the name of your application would get confusing down the line anyway. 

Would you be interested in opening a PR for this? If so, you can just prohibit `App` and we can extend it for other words later (e.g. `Hanami` and `Slice`)
