### ISSUE TITLE
[Documentation / FAQ] Main differences between rails and hanami?

### ISSUE THREAD

**Issue by rubyFeedback** [hanami/hanami#1473]
Hey there hanami folks,

Could a FAQ be added? Could be in a separate subdirectory, or the wiki on github, and then linked in from the main README.

Anyway - the question I have had recently, since reading some hanami-related news, is the main differences between rails and hanami. Not asking for a huge article, something that can just pin-point the main differences, in one or two regular sentences or so, give or take. I hope that's not too much time investment. (Reason I suggest a FAQ is because I think this helps provide an early intro to some user questions.)

I have a few more questions, such as "How is the tutorial situation for hanami?" Hopefully I am not too annoying here; I kind of need useful documentation as well as working (and starting with simple) examples. I am totally willing to try out new software and learn it properly too, but I kind of need a bootstrap "helper" (which is why I love up-to-date tutorials and working examples; I learned ruby-gtk that way, try-and-error, and the rest I could read up on the world wide web). Either way thank you for reading this issue request.

**Comment by timriley** [comment]
Hi @rubyFeedback, our best tutorial right now is our official [getting started guide](https://guides.hanamirb.org/v2.2/introduction/getting-started/). See also https://hanamimastery.com for a wide range of content.

I'm planning for a website overhaul in the near future. I'll think about whether a FAQ makes sense to include there.
