### ISSUE TITLE
Add documentation for Repos in 2.2

### ISSUE THREAD

**Issue by vladimirtcats** [hanami/hanami#1479]
Hi everyone. I am newbie in hanami)
I have several questions.

In version 1.3 repositories is used to create records in database
https://guides.hanamirb.org/v1.3/repositories/overview/

But in version 2.0, as I see, relations(Hanami::DB::Relation) is used to create record via insert
https://guides.hanamirb.org/v2.2/database/relations/

What is correct way to create records?

Also I don't find actual documentation for hanami-db. Could you please send the link?

I found that for creating record repository has 

```ruby
class UserRepo < ROM::Repository[:users]
  commands :create
end
```

But I can't use such syntax in Hanami::DB::Repo

**Comment by cllns** [comment]
Ah, sorry about that. That's definitely confusing.

We also use Repos (shortened name) in Hanami 2.2 but the docs aren't complete yet. They will be soon.

In the meantime, you can check out [the repository section of the overview](https://guides.hanamirb.org/v2.2/database/overview/#repositories), and you can combine that with [the ROM docs](https://rom-rb.org/learn/repository/5.2/) to learn more details.

**Comment by vladimirtcats** [comment]
Could you please send example how to correctly create record via repos. I onyl

**Comment by cllns** [comment]
If you read through [the Getting Started Guide](https://guides.hanamirb.org/v2.2/introduction/building-a-web-app/) (available for both full-stack web apps and an API-only app), you can see `book_repo.create` and how that's defined in the `BookRepo` class.

**Comment by vladimirtcats** [comment]
thanks)
