### ISSUE TITLE
Generation data for specs

### ISSUE THREAD

**Issue by vladimirtcats** [hanami/hanami#1480]
Hi everyone

Could you give me links related to generation data for specs? It will be awesome if hanami support chat exists
I use factory_bot for ActiveRecord, but it is not suitable for rom. Also, as I see, rom-factory it's not compatible with Hamami relations

I found only this link to gist

https://gist.github.com/rafaels88/8437edababcf38ee193b2ba0265e78b9

**Comment by wuarmin** [comment]
Hi,
Checkout https://github.com/rom-rb/rom-factory?tab=readme-ov-file.
It works great!

**Comment by vladimirtcats** [comment]
I tried to config but I got error
```ruby
Hanami.app.register_provider :persistence, namespace: true do
  prepare do
    require ‘rom-changeset’
    require ‘rom/core’
    require ‘rom/sql’
    
    config =
      ROM::Configuration.new(
        :sql, target['settings'].database_url
      )
    
    register 'config', config
    register 'db', config.gateways[:default].connection
  end

  start do
    config = target[‘persistence.config’]
    
    config.auto_registration(
      target.root.join('relations'),
      namespace: 'MyApp::Relations'
    )
    
    register 'rom', ROM.container(config)
  end
end
```

also I configure factory
```ruby
require “rom-factory”

require “faker”

Factory = ROM::Factory.configure do |config|
config.rom = MyApp::Container[“persistence.rom”]
end

Dir[File.dirname(FILE) + “/factories/*.rb”].each { |file| require file }
```

and created factory

```ruby
Factory.define(:users) do |f|
  f.sequence(:name) { |n| “name #{n}” }
end
```

but I got error

```
ROM::ElementNotFoundError:
:diplomas doesn’t exist in ROM::RelationRegistry registry
```
Could you give me information how to config rom-factory correctly?

**Comment by vladimirtcats** [comment]
It can be closed

https://discourse.rom-rb.org/t/is-rom-factory-compatible-with-hamami/663/5

**Comment by cllns** [comment]
Glad you figured it out!
