### ISSUE TITLE
Should operation be placed in `app/operations` folder?

### ISSUE THREAD

**Issue by stephannv** [hanami/hanami#1486]
I generated an operation on my project and it was generated in `/app` folder. I ran `hanami g operation books.create` and it created `app/books/create.rb` operation. I think when the application starts to grow, our app will be crowded with dozens of folders like `app/books`, `app/users`, `app/comments`, etc. Does it make sense to generate operations inside `app/operations`? I can try to resolve it in a PR if that is what we want.

**Comment by cllns** [comment]
Thanks for opening this issue. We always welcome feedback like this.

I originally implemented the generator as you describe, but [we decided to switch it](https://github.com/hanami/cli/pull/171/files/663abc6193fccdfa0e3bbfd424644bb16fcbd1e6#r1646304706) to the current behavior to be more flexible.

If you'd like the operations to be nested in a folder like that, you can do `hanami generate operations.books.create`. Does that work for you?

**Comment by stephannv** [comment]
Thanks @cllns. I think `hanami generate operations.books.create` will solve my issue.
