### ISSUE TITLE
Enhance Lotus::Logger

### ISSUE THREAD

**Issue by joneslee85** [hanami/hanami#356]
Firstly, thanks to @huydx for the initial logging support with Lotus. It works but there are room for improvements. I want to open this ticket to start a new discussion on how we could make Logging better.

Based on my exp, I really dig the format of one-line like lograge gem. It's succinct and easy to get parsed with log aggregator like splunk, logstash, etc. What do you think about adopting this format for Lotus::Logger?

**Comment by huydx** [comment]
I have some ideas for improvement includes:
- [ ] make it better for rack logging
- [ ] colorize 
- [ ] add more options

how do you think about that @joneslee85

**Comment by joneslee85** [comment]
> colorizre
not a big fan of colorize on production env as it obscures the correct data, but it's worthy on dev env.

> add more options
anything on your mind?

**Comment by rogerleite** [comment]
Hi @joneslee85! Really like the idea of one-line format.

It would be great to support tags. On our apps, we have a tricky Logger middleware to log on all web requests a `request_uuid` and some other informations.

**Comment by joneslee85** [comment]
@rogerleite I like tagging feature, I would find it's extremely useful for our container arch too. I've added your idea in the check list created by @huydx

**Comment by huydx** [comment]
@joneslee85 the word options is quite ambiguous. I'm thinking of an richer log with java's log4j like feature like appender, multiple logging, error-only logging ... but it's seem to be too much for a embedded logger. I recently not playing with lotus enough to get better ideas, so i leave it to your hand guys @joneslee85 @jodosha @AlfonsoUceda

**Comment by klebervirgilio** [comment]
Hi there! nice discussion. Was just wondering, would _one-line_ log format be something configurable?
I mean, I think we can find good information in a _multiple-line_ log format. 

Like, views being rendered, time spent on each view and so on... I even like to see the SQL performed as well as query explained.

```
Started GET "/" for 127.0.0.1 at 2012-03-10 14:28:14 +0100
Processing by HomeController#index as HTML
  Rendered text template within layouts/application (0.0ms)
  Rendered layouts/_assets.html.erb (2.0ms)
  Rendered layouts/_top.html.erb (2.6ms)
  Rendered layouts/_about.html.erb (0.3ms)
  Rendered layouts/_google_analytics.html.erb (0.4ms)
Completed 200 OK in 79ms (Views: 78.8ms | ActiveRecord: 0.0ms)
```
vs
```
method=GET path=/jobs/833552.json format=json controller=jobs action=show status=200 duration=58.33 view=40.43 db=15.26
```

**Comment by jodosha** [comment]
@klebervirgilio Yes, but not yet :wink: - That informations require code instrumentation, which is missing in Lotus. It isn't a priority right now.

**Comment by jpruetting** [comment]
I work with Rails in a large enterprise environment and have modified Rails logging to work better with logging services (we use Splunk). The following changes have made a huge difference:

- Use some sort of notification framework to instrument "events" within your application
- Subscribe to those events to create log entries
- Use a single-line JSON format for log entries and give every entry a "type"
- Make pretty formatting and color configurable per environment

In the end, you end up with something like this in Splunk or Logstash:
```json
{  
   "timestamp":"2016-02-10T16:02:38Z",
   "severity":"INFO",
   "type":"application.request",
   "request_id":"c15e-4a2b-9d4c-a359eb8fb8a1-c2ad38b1",
   "method":"GET",
   "status":200,
   "user_agent":"Apache-HttpClient/4.8.1 (java 1.7)",
   "referrer":null,
   "forwarded_for":"123.45.216.10",
   "url_scheme":"https",
   "url_host":"bookshelf.example.com",
   "url_port":"443",
   "url_path":"/books/45",
   "url_query":null,
   "rails_controller":"books",
   "rails_action":"show",
   "clean_path":"/books/:id",
   "remote_ip":"123.99.23.105",
   "remote_host":null,
   "duration":"40.52",
   "message":"OK",
   "session_id":"fe88076b8032593d520e77cce5147c6d"
},
{  
   "timestamp":"2016-02-10T15:49:31Z",
   "severity":"FATAL",
   "type":"exception",
   "message":"No route matches [GET] \"/books.xml\": vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'",
   "exception_id":"818bf8ea2facffad3f18af6f1f7ed84ed1b1db54",
   "backtrace":[  
      "vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'",
      "vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'",
      "vendor/bundle/ruby/2.2.0/gems/example-logging-0.4.0/lib/example/logging/middleware.rb:22:in `block in call'",
      "vendor/bundle/ruby/2.2.0/gems/example-logging-0.4.0/lib/example/logging/middleware.rb:33:in `block in instrument'",
      "vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'",
      "vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'",
      "vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'",
      "vendor/bundle/ruby/2.2.0/gems/example-logging-0.4.0/lib/example/logging/middleware.rb:33:in `instrument'",
      "vendor/bundle/ruby/2.2.0/gems/example-logging-0.4.0/lib/example/logging/middleware.rb:19:in `call'",
      "vendor/bundle/ruby/2.2.0/gems/request_store-1.2.0/lib/request_store/middleware.rb:8:in `call'",
      "vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/request_id.rb:21:in `call'",
      "vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'",
      "vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'",
      "vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'",
      "vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'",
      "vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/ssl.rb:24:in `call'",
      "vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/engine.rb:518:in `call'",
      "vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:165:in `call'",
      "passenger (5.0.18) lib/phusion_passenger/rack/thread_handler_extension.rb:94:in `process_request'",
      "passenger (5.0.18) lib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'",
      "passenger (5.0.18) lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'",
      "passenger (5.0.18) lib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'",
      "passenger (5.0.18) lib/phusion_passenger/utils.rb:112:in `block in create_thread_and_abort_on_exception'"
   ]
}
```

I formatted it for viewing here, but in production they would be single lines.

The JSON format gets parsed automatically in Splunk and displays with nice formatting and colors.

**Comment by joneslee85** [comment]
I am going to close this ticket as it does not serve its original intention as a placeholder for discussion on this topic anymore.
