### ISSUE TITLE
Destroy command: action route doesn't get removed

### ISSUE THREAD

**Issue by jodosha** [hanami/hanami#451]
It affects `v0.6.0`

Steps to reproduce:

```shell
➜ lotus new bookshelf && cd bookshelf && bundle
➜ bundle exec lotus generate action web home#index --url=/
➜ bundle exec lotus destroy action web home#index
➜ cat apps/web/config/routes.rb
get '/', to: 'home#index' # THIS SUPPOSED TO BE REMOVED
# ...
```

---
Ref: #357 
/cc @t4deu

**Comment by t4deu** [comment]
Hi @jodosha, sorry for my absence, I will take care of this

**Comment by jodosha** [comment]
@t4deu Thank you.

**Comment by davydovanton** [comment]
@t4deu if you want I can work on this

**Comment by t4deu** [comment]
Yes please @davydovanton, thanks, you can check on:
```
lib/lotus/commands/generate/action.rb
```

**Comment by davydovanton** [comment]
I found that if you call `destroy` command with `--url=/` option you see that all works correct.

Screencast:
https://asciinema.org/a/cpahd5jx1ssefzrdlqig6n6zz

**Comment by joneslee85** [comment]
@davydovanton how are you going with this issue? Do you want let others take over?

**Comment by jodosha** [comment]
@davydovanton 
> I found that if you call `destroy` command with `--url=/` option you see that all works correct.

Yes, but that is unexpected, we should stick with `hanami destroy action web home#index`, **without** the `--url` argument.

Please let the somebody else to take care of this. Please focus on logger. Thank you :+1:
