### ISSUE TITLE
Write test for `lotus console` console engine option

### ISSUE THREAD

**Issue by joneslee85** [hanami/hanami#463]
To avoid regression with `lotus console` like in https://github.com/lotus/lotus/pull/461, an integration test is needed

**Comment by kubenstein** [comment]
hi,
recently im getting more and more interested in hanami framework. Im happy to see alternative to rails, alternative that match my personal view at how web framework should be built (and it is still in ruby ^^).

i follow guide from website but even with nearly empty app i cant start console, i get error:
```
bundle exec hanami console
/Users/kuba/.rvm/gems/ruby-2.0.0-p645/gems/hanami-0.7.0/lib/hanami/commands/console.rb:74:in `block in load_engine': Unknown console engine: i (ArgumentError)
	from /Users/kuba/.rvm/gems/ruby-2.0.0-p645/gems/hanami-0.7.0/lib/hanami/commands/console.rb:73:in `fetch'
	from /Users/kuba/.rvm/gems/ruby-2.0.0-p645/gems/hanami-0.7.0/lib/hanami/commands/console.rb:73:in `load_engine'
	from /Users/kuba/.rvm/gems/ruby-2.0.0-p645/gems/hanami-0.7.0/lib/hanami/commands/console.rb:55:in `engine'
	from /Users/kuba/.rvm/gems/ruby-2.0.0-p645/gems/hanami-0.7.0/lib/hanami/commands/console.rb:49:in `start'
	from /Users/kuba/.rvm/gems/ruby-2.0.0-p645/gems/hanami-0.7.0/lib/hanami/cli.rb:60:in `console'
	from /Users/kuba/.rvm/gems/ruby-2.0.0-p645/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/kuba/.rvm/gems/ruby-2.0.0-p645/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/kuba/.rvm/gems/ruby-2.0.0-p645/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/kuba/.rvm/gems/ruby-2.0.0-p645/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/kuba/.rvm/gems/ruby-2.0.0-p645/gems/hanami-0.7.0/bin/hanami:5:in `<top (required)>'
	from /Users/kuba/.rvm/gems/ruby-2.0.0-p645/bin/hanami:23:in `load'
	from /Users/kuba/.rvm/gems/ruby-2.0.0-p645/bin/hanami:23:in `<main>'
	from /Users/kuba/.rvm/gems/ruby-2.0.0-p645/bin/ruby_executable_hooks:15:in `eval'
	from /Users/kuba/.rvm/gems/ruby-2.0.0-p645/bin/ruby_executable_hooks:15:in `<main>'
```

I would love to contribute but im still super newbe in hanami so at this stage im not sure how can i help besides reporting the issue.

**Comment by joneslee85** [comment]
that issue is known and there is already a fix. please stay tuned

**Comment by jodosha** [comment]
@kubenstein Hello and sorry about that problem. The fix for it was shipped with `0.7.1`, please make sure to update your app. Thank you :+1:

**Comment by kubenstein** [comment]
@jodosha hi i saw on release notes on twitter, will double check and let you know. thank you for all hard work you put in this project. Keep it up!

**Comment by jodosha** [comment]
CLI needs serious testing. Closing this in favor of a testing improvement after 1.0.
