### ISSUE TITLE
Param errors exposed to views and templates

### ISSUE THREAD

**Issue by nomanurrehman** [hanami/hanami#465]
I have found that when there are validation errors in case of params, the variable "errors" is automatically exposed to views and templates.

I started out with my controller like this:

```ruby

module Web::Controllers::Users
  class Create
    include Web::Action

    params do
      param :data do
        param :user do
          param :first_name, presence: true, size: 5..25
          param :last_name, presence: true, size: 5..25
          param :username, presence: true, size: 5..25
          param :password, presence: true, size: 8..64
          param :date_of_birth
        end
      end
    end

    expose :user, :errors

    def call(params)
      if params.valid?
        create_user(params)
      else
        @errors = params.errors
      end
    end

    private

    def create_user(params)
      @user = UserRepository.create(User.new(
        first_name: params.get('data.user.first_name'),
        last_name: params.get('data.user.last_name'),
        username: params.get('data.user.username'),
        password: params.get('data.user.password'),
        date_of_birth: params.get('data.user.date_of_birth')
      ))
    end

  end
end
```

Going with the framework's "explicit" approach, this is more natural and explains the code a bit better to someone who is looking at it for the first time.

Moreover, in case there are no validation errors, an empty hash `{}` is still exposed to the view and templates.

The problem arose for me when I tried to set a custom error in case, say the database is down. The errors variable is still an empty hash `{}` in that case.

I think exposing the errors should be made explicit as compared to implicitly being passed to views and templates.

Also, I did not find this mentioned in the documentation anywhere or did I miss it?

Thoughts?

**Comment by nomanurrehman** [comment]
@jodosha Any thoughts on this?

**Comment by jodosha** [comment]
@nomanurrehman Extreme explicitness is verbose. That's why errors are passed over by default. We can document this to explain the reason.

> The problem arose for me when I tried to set a custom error in case, say the database is down. The errors variable is still an empty hash {} in that case.

Can you please show me some code? Thank you :smile:

**Comment by nomanurrehman** [comment]
Basically, if you set the `@errors` variable to any value when all params are valid, an empty `error` hash is passed to the view.

```ruby
expose :errors

def call(params)
  # errors in view will still be empty hash
  @errors = 'Some very long error message'
end
```

**Comment by jodosha** [comment]
I'm closing this because we want to implement a different way to pass errors to the views.
