### ISSUE TITLE
LOTUS_ENV is not picked up correctly

### ISSUE THREAD

**Issue by joneslee85** [hanami/hanami#476]
Today I find that only `RACK_ENV` is taken into consideration, not `LOTUS_ENV`, here is a simple test:

```
$ LOTUS_ENV=test bundle exec hanami console
irb(main):002:0> Hanami::Environment.new.environment
=> "development"
```

It seems to be a regression

**Comment by taoza** [comment]
Have you tried HANAMI_ENV? ;)

**Comment by joneslee85** [comment]
@taoza you are right :+-:
