### ISSUE TITLE
Automatic Logging

### ISSUE THREAD

**Issue by jodosha** [hanami/hanami#484]
We want to offer automatic logging of default events like:
- `Action#call` elapsed time (including callbacks)
- `View#render` elapsed time (we should report which template was rendered or if a custom `#render` implementation was provided
- Layout rendering elapsed time (we should report which template was used)
- Partial rendering elapsed time
- SQL queries from repositories, query and commands objects

Please see #483 as a reference for the format that we want to use.

---

/cc @hanami/core-team

**Comment by lucasallan** [comment]
@davydovanton are you working on this?

**Comment by davydovanton** [comment]
@lucasallan hello,
Yep, I'm working on this issue, you can find my code here https://github.com/hanami/hanami/pull/589
Thanks for worrying 🎉
