### ISSUE TITLE
Could not use UUID as primary_key

### ISSUE THREAD

**Issue by bolshakov** [hanami/hanami#485]
Hi, I have the following configuration:

```ruby
# db/migrations/20160125223305_create_books.rb
Hanami::Model.migration do
  change do
    create_table :books do
      primary_key :id, :uuid

      column :name, String, null: false
    end
  end
end
```

```ruby
# lib/config/mapping.rb
collection :books do
  entity Book
  repository BooksRepository

  attribute :id, String
  attribute :name, String
end
```

```ruby
class Books
    include Hanami::Entity
    attributes :name
end
```

This is simple model with UUID `primary_key` (instead of integer). Then, I'm trying to perform the following test:

```ruby
book = Book.new(name: 'Tom Sawyer')
BooksRepository.create(book)
```

And it fails with error:

```
Hanami::Model::Error: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, Tom Sawyer).
```

If I change uuid to id, it works just fine. Could you help me?

**Comment by bolshakov** [comment]
I've sorted out with the problem. I made some wrong considerations.

First of all, I need to enable "uuid-ossp" extension explicitly:

```ruby
Hanami::Model.migration do
  change do
    run 'CREATE EXTENSION "uuid-ossp"'
    # ...
```

Then, I have to specify default value for primary key:

```ruby
create_table :books do
   primary_key :id, :uuid, default:  Sequel.function(:uuid_generate_v4)
end
```

Now it works as expected.

**Comment by joneslee85** [comment]
it is seems to be a common case, would be able to submit a PR for our Getting Started guide?

**Comment by jodosha** [comment]
@bolshakov Hello and thank you both for reporting your problem and posting a solution. As @joneslee85 said, it would be **really** helpful if you can add it here: https://github.com/hanami/hanami.github.io/blob/build/source/guides/models/overview.md Thank you very much.

**Comment by bolshakov** [comment]
Sure, I'll take a look later

**Comment by bolshakov** [comment]
Done https://github.com/hanami/hanami.github.io/pull/130

**Comment by jodosha** [comment]
@bolshakov Thank you again! :+1:
