### ISSUE TITLE
'Method not allowed' when posting to a url

### ISSUE THREAD

**Issue by sebabouche** [hanami/hanami#488]
Wether the url is 
```
post '/books', to: 'books#create'
```
or
```
resources :books
```
I get a __`Method Not Allowed`__ when submitting from:
```
<form action="/books" method="POST" accept-charset="utf-8" id="book-form">
    <div class="input">
        <label for="book-title">Title</label>
        <input type="text" name="book[title]" id="book-title" value="">
    </div>
    <div class="input">
        <label for="book-author">Author</label>
        <input type="text" name="book[author]" id="book-author" value="">
    </div>
    <div class="controls">
        <button type="submit">Create Book</button>
    </div>
</form>
```
(I'm following the Getting Started tutorial, only difference is installing `gem 'minitest_reporters'`).

**Comment by joneslee85** [comment]
@sebabouche would you be able to push your app codes to a repo for my investigation?

**Comment by sebabouche** [comment]
Sure! It's __[there](https://github.com/sebabouche/bookshelf)__.

**Comment by vbyno** [comment]
I'm having the same issue. Looks like it is related to [this one](https://github.com/hanami/hanami/issues/480). Because it works well after changing `form_for :book, '/books'` to `form_for :book, '/books/'` (with a slash) if the template

**Comment by kristho91** [comment]
Same problem here.
But even after the "fix" that vbyno suggest the tests won't pass. It works if using it in the browser though.
The tests will fail on current_path.must_equal('/books/') no matter, if it has a trailing slash or not.

Im om ruby 2.2.4p230 on Fedora 23

**Comment by joneslee85** [comment]
We have found the problems and now working on a patch.

Closed this ticket because it is duplicated of #480
