### ISSUE TITLE
hanami generate action #create does not create a post route

### ISSUE THREAD

**Issue by sebabouche** [hanami/hanami#489]
```
hanami generate action web books#create
```
doesn't generate (as mentionned in the book):
```
post '/books', to: 'books#create'
```
but
```
get '/books', to: 'books#create'
```

**Comment by davydovanton** [comment]
Hello! For generate action with specific method you need to use `--method` key. For example:
```
$ hanami generate action web books#create --method=post
```

**Comment by sebabouche** [comment]
That makes sense. Much better than the framework guessing. So the __getting started__ on that matter is misleading.

**Comment by davydovanton** [comment]
@sebabouche I updated getting start guide too.

**Comment by jodosha** [comment]
@sebabouche @davydovanton Thank you all :+1:
