### ISSUE TITLE
Different in behavior of 'hanami new' and 'hanami generate model'

### ISSUE THREAD

**Issue by zakuro9715** [hanami/hanami#490]
I found difference in behavior of `hanami new` and `hanami generate model` when appname includes capital letters.

For example,  `MyProject/lib` directory is as following after I ran `hanami new MyProject`

```
MyProject/lib/
  - config/
  - myproject/
  - myproject.rb
```

And it is as following after I ran `hanami generate model model`

```
MyProject/lib/
  - config/
  - myproject/
  - MyProject/
      - repositories/model.rb
      - entities/model.rb
  - myproject.rb
```

There is `Dir["#{ __dir__ }/investgate/**/*.rb"].each { |file| require_relative file }` in `myproject.rb`. So, Model won't loaded.

**Comment by davydovanton** [comment]
@zakuro9715 hello, thanks for bug report :+1:

**Comment by klebervirgilio** [comment]
is there anyone working on this feature? I can help.

**Comment by davydovanton** [comment]
@klebervirgilio hello :wave:
You can find the PR here:
https://github.com/hanami/hanami/pull/491
