### ISSUE TITLE
Container: remove per application Rack::MethodOverride in favor of one at the level of Container middleware stack

### ISSUE THREAD

**Issue by jodosha** [hanami/hanami#494]
## Actual

If we have two applications `web` and `admin`, they both use `Rack::MethodOverride` in their internal middleware stack.

## Proposed

As of v0.6.0 `Hanami::Container` has its own middleware stack which wraps all the applications within a project. We can mount `Rack::MethodOverride` here instead.

**Comment by klebervirgilio** [comment]
What tests would need to be done in order to make sure that's happing?
