### ISSUE TITLE
Introduce --template for hanami new

### ISSUE THREAD

**Issue by jodosha** [hanami/hanami#507]
This is the second part of #473 

## Proposal

```shell
➜ hanami new bookshelf --template=haml
```

Accepted values are: `erb`, `haml`, `slim`. If that option is omitted, `erb` is the default.

The command above should:

  * Add `gem 'haml'` to `Gemfile`
  * In case of `erb`, no gems must be added to `Gemfile`
  * Add `template=haml` to `.hanamirc`
  * Generate `apps/web/templates/application.html.haml` (see #473)

---

/cc @hanami/contributors

**Comment by davydovanton** [comment]
@jodosha we have a PR with this changes (https://github.com/hanami/hanami/pull/379). May be is better to reopen this?

**Comment by jodosha** [comment]
@davydovanton Yes, but it still references Lotus. If we're going to rework it we should credit @aderyabin for the idea and implementation.

**Comment by aderyabin** [comment]
@davydovanton let's talk about it in podcast :)

**Comment by davydovanton** [comment]
@aderyabin okay :)

**Comment by aderyabin** [comment]
@jodosha, I am in!

**Comment by jodosha** [comment]
@aderyabin Can you please open a PR here? Thank you :+1:
