### ISSUE TITLE
Modify rendering policy to permit template rendering for HTTP status other than 200 & 201

### ISSUE THREAD

**Issue by accuser** [hanami/hanami#509]
# Actual

The current rendering policy will only permit the template associated with an action to be rendered if the action is deemed successful:

```
#hanami/lib/hanami/rendering_policy.rb
SUCCESSFUL_STATUSES = (200..201).freeze
    
def _render_action(action, response)
  if successful?(response)
    view_for(action, response).render(action.exposures)
  end
end

def successful?(response)
  SUCCESSFUL_STATUSES.include?(response[STATUS])
end
```

When returning an HTTP status other than 200 or 201, a [custom error page](http://hanamirb.org/guides/views/custom-error-pages/) is used in its place, but is specific to the app and not the current action. These templates represent more of an unrecoverable error situation, similar to an exception. Thus the custom error pages can be likened to default exception handlers.

# Proposed

Allow the template associated with the action to be rendered and respond with the HTTP status code set by the action. For example:

```
module Web::Controllers::Session
  class Create
    include Hanami::Action

  params do
    param :email, presence: true
    param :password, presence: true
  end

  def call(params)
    if params.invalid?
      self.status = 400 # or 422
    elsif self.current_user = AuthenticateUser.call(params) 
      redirect_to routes.user_path(id: current_user.id)
    else
      self.status = 404
    end
  end
end
```

In the above example, if the parameters are invalid, or the user cannot be authenticated, the action can simply render the login form, but the HTTP status will be respected and returned to the client browser or application.

When the developer wants to indicate an exception condition, this can be achieved through the use of `halt`:

```
module Web::Controllers::Users
  class Show
    include Hanami::Action

  params do
    param :id, presence: true
  end

  def call(params)
    if params.invalid?
      halt 400
    elsif @user = FindUser.call(params) 
      # do nothing; the associated template will be rendered
    else
      halt 404
    end
  end
end
```

Thus using `halt` in this way is similar to `raise`, i.e. an exception has occurred. In this case, the appropriate custom error page will be rendered.

**Comment by accuser** [comment]
In addition to the above, and in line with the way Hanami currently works, a response with an HTTP status that does not include a body should not render a body.

**Comment by joneslee85** [comment]
can't you explicitly set status then render a template?

and have you look into controller callback? you could write a callback that check the caller and exception and then render template accordingly

**Comment by accuser** [comment]
@joneslee85 that might be the intention, but it doesn't seem to work like that at present. One can explicitly set the HTTP status in an action, but the rendering policy won't render the associated template if the HTTP status isn't 200 or 201.

**Comment by joneslee85** [comment]
cc @hanami/core-team

**Comment by jodosha** [comment]
@accuser I see what you mean and agree with the need. I'm not sold about the proposed semantic of `#halt` and `#status=`. We need to be more careful with it.

**Comment by accuser** [comment]
@jodosha not too worried about the use in practice, but definitely needed. I proposed `#halt` and `#status=` simply because they are already there. My own personal preference would be to avoid using `#halt` since it is essentially throwing an exception (although, technically this is happening in the framework).

**Comment by joneslee85** [comment]
@accuser do you have a list of HTTP status code that allows empty / non-empty body?

**Comment by accuser** [comment]
@joneslee85 from `Hanami::Action::Head`:

```ruby
HTTP_STATUSES_WITHOUT_BODY = Set.new((100..199).to_a << 204 << 205 << 304).freeze
```

and `Hanami::Action::Glue`:

```ruby
 ADDITIONAL_HTTP_STATUSES_WITHOUT_BODY = Set.new([301, 302]).freeze
```

**Comment by jodosha** [comment]
Related: https://github.com/hanami/hanami/issues/592

**Comment by fidothe** [comment]
We've been running into this issue as well recently, so I thought I would outline our particular problem and offer a slightly different approach. If there's any enthusiasm I'll work up a PR.

We have to render a particular template, with some dynamic data, for a set of legacy URLs. Because these are different-app legacy URLs there's no easy way (or desire) to route these, so we have a middleware that intercepts 404s, checks the URL and renders one of several templates depending on URL and context.

The middlware looks like this: (simplified by removing the dynamic-template-picking for ease of reading)

```ruby
class View404
  include Hanami::View
end

class Middleware
  def initialize(app)
    @app = app
  end
  
  def call(env)
    status, headers, response = @app.call(env)

    if status == 404
      view = View404.new(template, {})
      return response(view)
    end

    [status, headers, response]
  end

  def template
    Hanami::View::Template.new('/path/to/404_template.html.erb')
  end

  def response(view)
    response = Rack::Response.new([], 404, {})
    response.write(view.render)
    response['Content-Type'] = 'text/html'
    response.finish
  end
end
```

Even though this returns a complete response, Hanami still rewrites the response body. In order to prevent this we have to make the `call` method look like this:

```ruby
  def call(env)
    status, headers, response = @app.call(env)

    if status == 404
      view = View404.new(template, {})
      env.delete('hanami.action')
      return response(view)
    end

    [status, headers, response]
  end
```

Which is pretty grim.

My proposed solution would be for `Hanami::RenderingPolicy` to check if the response is a full response (i.e. has status code, non-empty body, and a `Content-Type` header plus either `Content-Length` or `Transfer-Encoding: chunked`) and bypass the rendering mechanism if it is. Should be a fairly uninvasive change and would enable all the behaviours mentioned so far, AFAICT.

**Comment by jodosha** [comment]
@fidothe I'm writing a description for a PR in this exact moment. Would you mind to review it 30 mins? Thanks!

**Comment by fidothe** [comment]
@jodosha of course!

**Comment by jodosha** [comment]
@accuser @joneslee85 @fidothe Please have a look at https://github.com/hanami/hanami/pull/599
