### ISSUE TITLE
Change security.content_security_policy API

### ISSUE THREAD

**Issue by joneslee85** [hanami/hanami#510]
## Actual

CSP header can be set via `#content_security_policy` helper.

```
security.content_security_policy "base-uri 'self'; default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self'; font-src 'self'; object-src 'self'; child-src 'self'; media-src 'self'"
```

The method takes in a long string of directives and IMO it is not very appealing. Firstly it is not easy on eyes. Secondly it falls short of configurability in the scenario that user want to change one directive. Lastly it is not easy to test individual directive.

## Proposed

Refactor `#content_security_policy` to return a 1st-class citizen class instead. I am not going into conclusion on how the public interface should be like, but here are few drafted ideas:

```
security.content_security_policy #=> instance of ContentSecurityPolicyHeader class
security.content_security_policy.set('image-src', [:self, 'http://google.com'])
```

The `ContentSecurityPolicyHeader#set` takes in array of values. It overrides the existing values.

To return aggregated header value, I am thinking of introducing `ContentSecurityPolicyHeader#to_s` method:

```
security.content_security_policy.to_s
#=> "base-uri 'self'; default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self'; font-src 'self'; object-src 'self'; child-src 'self'; media-src 'self"
```

Thoughts?

**Comment by jodosha** [comment]
@joneslee85 That is a nice to have, but what about performances? The initial idea of having a huge string is to send **as it is**.

What if `#content_security_policy` is able to accept a multiline string and store it internally as a single line?

```ruby
      security.content_security_policy %{
        default-src 'none';
        script-src 'self' https://oss.maxcdn.com;
        connect-src 'self';
        img-src 'self';
        style-src 'self' https://fonts.googleapis.com;
        font-src 'self' https://fonts.gstatic.com;
      }
```

This has the advantage of readability and it eliminates the need to compute the string for each request or eventually cache it.

**Comment by joneslee85** [comment]
@jodosha I like your suggestion. :+1:  It looks very clean.

Part of the proposal is to improve the configurability of the framework, I am foreseeing that eventually JS frameworks would have problems with the default settings and thus in needs for way to change existing directives. Having said that, I am aware that CSP can be declared many times so users could declare a new CSP header to override the 1st but it comes with the cost of perf.

I think I might be optimised too immaturely at this stage, till then I go with your suggestion.
