### ISSUE TITLE
Introduce db seed command

### ISSUE THREAD

**Issue by davydovanton** [hanami/hanami#511]
## Actual
At the moment hanami doesn't support standart way for generation data sets.

## Proposed
By introducing a new `db seed` command, we could create a standard way of generating default data sets.

**Comment by joneslee85** [comment]
I am not a big fan of Rails `rake db:seed` tasks, to me it always fall short on the real world scenario. 

In most of the cases, users tend to extend the scope of this raketask to perform more than seeding db, for eg asking for inputs interactively, change configurations and other complex calculation. For such cases, a custom rake task OR the #447 feature seem to be more fitting.

I also think that `hanami CLI` should be those that are frequently used. DB seeding would be likely a one-off task and having one infrequently sub-command would add more work for core team and the community.

Just my 5 cent.

Thoughts?

**Comment by jodosha** [comment]
@davydovanton Hello and thank you for this proposal, but this isn't a priority for now. Devs can easily implement their own solution.

**Comment by davydovanton** [comment]
@joneslee85 thank you for your opinion :+1:

@jodosha I understood, thanks for explanation. What do you think may be is better to create "How to seed you db" guide in documentation?

**Comment by joneslee85** [comment]
@davydovanton I like a section in the doc on how to write custom rake task, please go for it

**Comment by jodosha** [comment]
@davydovanton @joneslee85 FYI http://hanamirb.org/guides/applications/rake/ :wink:
