### ISSUE TITLE
lib/hanami/static.rb#_fresh? does not detect change to Sass @import

### ISSUE THREAD

**Issue by jackturnbull** [hanami/hanami#513]
Hello! I was debating putting this in hanami-assets but since the code in question sits in this repo it feels like the best place to put it. Feel free to close and direct me away if that's the case.

#### Description

I've been seeing unexpected behaviour with lazy reloading of stylesheet assets when using Sass partials as the complete CSS structure for a project. All CSS rules are contained in `apps/web/assets/stylesheets/partials` with my main.css.scss containing only the `@import` directives.

When I change the content of a partial, the main file itself is not recognised as fresh causing the already compiled version to be served statically meaning changes to Sass partials cannot trigger a precompile of the parent Sass file.

#### Expected behaviour

Changing Sass partials will also trigger a precompile, causing it to be rewritten in the `public/assets` directory.

#### Actual behaviour

Since the parent file is unmodified, [lib/hanami/static.rb#_fresh?](https://github.com/hanami/hanami/blob/0fc96af7659afa75c573140975b9b79c17811a0a/lib/hanami/static.rb#L60-L61) does not detect a new modified time for the parent Sass file causing the pre-existing compiled file to be served statically.

#### Reproduction steps

* Create a new project and route with `hanami new` and `bundle exec hanami generate action web home#index --url=/` and add `gem 'sass'` to the Gemfile
* Create a parent Sass file, and partial Sass file at `stylesheets/application.css.scss` and `stylesheets/partials/_base.scss` and import this within application.css.scss
* Add a `<h1>` to the home/index template with some content.
* Add a style for the h1 in the partial and reload the page, the style does not change.
* Add a style for the h1 in the parent and reload the page, the style changes.

#### Current workaround

Remove `@import` statements, making each partial their own parent file required with the `<% stylesheet %>` helper

**Comment by jodosha** [comment]
@jackturnbull Thanks for reporting this issue. I was already aware of it and can confirm the problem.

**Comment by accuser** [comment]
@jodosha I was looking at this today with regards my changes to `Hanami::Assets`. I think that I can build a list of dependencies (via `@import`) on the fly during compilation, and then check for freshness of all dependencies when checking the compiled asset.

**Comment by jodosha** [comment]
@accuser :+1:

**Comment by accuser** [comment]
I've had a week of meetings, so no PR yet. However, I have solved this issue and have a constructed compiler that provides a list of dependencies via the `@import` directive of SCSS. :smile:

**Comment by jodosha** [comment]
@accuser Great to hear :+1: We're waiting for your PR, then :smile:
