### ISSUE TITLE
Application.rb Template has incorrect digest URL

### ISSUE THREAD

**Issue by daneb** [hanami/hanami#521]
When you generate a new application with Hanami, the application.rb contains the following snippet of comment:

```
# Use digest file name for asset paths
#
# See: http://hanamirb.org/guides/assets/digest
 digest  true
```

The request URL for the digest does not exist and I assume the correct location is
 http://hanamirb.org/guides/assets/overview

If this is correct I can go ahead and make the change?

**Comment by jodosha** [comment]
@daneb Please do :+1: Thanks!
