### ISSUE TITLE
Let rendering errors to be reported to exception notification services

### ISSUE THREAD

**Issue by jodosha** [hanami/hanami#528]
Right now exceptions that happen in actions are referenced in Rack env. See https://github.com/hanami/controller/pull/134

[This doesn't happen for views and templates](https://github.com/hanami/hanami/pull/370) and we should address to this problem.

We should catch exceptions in `Hanami::RenderingPolicy` and reference them in Rack env.

I created [a code spike](https://github.com/hanami/hanami/commit/4c1b6e1024756f29d3c9c9207a99fd55a3c41bd0) to demonstrate to show how to implement a solution.

**Comment by karimmtarek** [comment]
@jodosha I'll pick this one up, if it's still available.

**Comment by jodosha** [comment]
Fixed by #564
