### ISSUE TITLE
Logger: Support Application Architecture

### ISSUE THREAD

**Issue by jodosha** [hanami/hanami#531]
We introduced new logger features with #517 and #530 .
These PR were merged, but they only ship with generators that support Container Architecture. Application Architecture was left behind.

We should address this disparity of features.

**Comment by joneslee85** [comment]
@jodosha I'll take this

**Comment by jodosha** [comment]
@joneslee85 Can you please take care of finalize the tickets and PR that you've opened instead? Please leave it to @davydovanton .

**Comment by joneslee85** [comment]
@jodosha surely
