### ISSUE TITLE
Remove lib/config/mapping.rb, make it the default, or add comments

### ISSUE THREAD

**Issue by jbodah** [hanami/hanami#535]
I lost about an hour because of this (and some confusion with another bug which had been resolved in 0.8.x). I would recommend either removing this file, making it the default, or adding comments saying that the file is meant to be loaded from `lib/my_project.rb` to avoid confusion. Personally I prefer either of the first two options to avoid having a dead file in the project

**Comment by jodosha** [comment]
@jbodah I'm sorry about your lost time. This has been source of confusion for other people too. I think it's fair to not generate it anymore.

BTW, we're going to remove the need to of database mapping. See https://github.com/hanami/model/issues/292 for reference.

**Comment by jbodah** [comment]
Awesome thanks for the link!
