### ISSUE TITLE
Resourceful routes - always GET

### ISSUE THREAD

**Issue by cllns** [hanami/hanami#539]
#414 isn't working as desired, with version 0.7.2.

Running `hanami generate action web books/destroy` should generate this route:
```
delete '/books/:id', to: 'books#destroy'
```

but it generates this instead:
```
get '/books/:id', to: 'books#destroy'
```

So the URL suffix is working properly, but the HTTP action (verb) is not. It just uses GET for everything (unless you pass in `--method`).

This is true for all of the commands, so this is an issue for `create` and `update` too, since they're the other non-GET resourceful routes.

It's weird because there's [a test for this](https://github.com/hanami/hanami/blob/master/test/commands/generate/action_test.rb#L162). I'm not sure why that test is not catching this.

**Comment by CollinGraves** [comment]
Have we verified this, all? I can get a fix in progress.

**Comment by jodosha** [comment]
@CollinGraves @cllns Sorry for the late reply. I'm back part-time on Hanami now.

I can confirm that this doesn't work with `HEAD` as well. Can you folks please check the problem and write a fix for this? Thank you :+1:

**Comment by cllns** [comment]
The problem was the `default` option in Thor's `method_option`. Thor was adding `{'method' => 'GET'}` to the `options` param in the initializer.
This explains why the test wasn't failing, since the test creates the Action object directly, with an empty options hash.

We don't currently have integration tests for generating an action. I can add some, if we want them.
