### ISSUE TITLE
AdapterNotFound:  Cannot find Hanami::Model adapter FileSystemAdapter

### ISSUE THREAD

**Issue by cllns** [hanami/hanami#556]
```bash
hanami new --hanami-head bookshelf && cd bookshelf && bundle && bundle exec hanami server
```
Triggers this error. It doesn't happen with 0.7.2.

Not sure if the problem is here, or in `hanami/model`.

Here's the relevant part of the stacktrace
```
bundler: failed to load command: hanami (/Users/sean/.gem/ruby/2.3.0/bin/hanami)
Hanami::Model::Config::AdapterNotFound: Cannot find Hanami::Model adapter FileSystemAdapter
  /Users/sean/.gem/ruby/2.3.0/bundler/gems/model-3e99c5682c45/lib/hanami/model/config/adapter.rb:107:in `rescue in instantiate_adapter'
  /Users/sean/.gem/ruby/2.3.0/bundler/gems/model-3e99c5682c45/lib/hanami/model/config/adapter.rb:103:in `instantiate_adapter'
  /Users/sean/.gem/ruby/2.3.0/bundler/gems/model-3e99c5682c45/lib/hanami/model/config/adapter.rb:89:in `build'
  /Users/sean/.gem/ruby/2.3.0/bundler/gems/model-3e99c5682c45/lib/hanami/model/configuration.rb:256:in `_build_adapter'
  /Users/sean/.gem/ruby/2.3.0/bundler/gems/model-3e99c5682c45/lib/hanami/model/configuration.rb:76:in `load!'
  /Users/sean/.gem/ruby/2.3.0/bundler/gems/model-3e99c5682c45/lib/hanami/model.rb:60:in `load!'
  /Users/sean/dev/bookshelf/lib/bookshelf.rb:41:in `<top (required)>'
  /Users/sean/dev/bookshelf/config/environment.rb:4:in `require_relative'
  /Users/sean/dev/bookshelf/config/environment.rb:4:in `<top (required)>'
...
```

**Comment by jodosha** [comment]
@cllns Thanks for opening this issue. I've experienced the same error since a while. Possible related is: https://github.com/hanami/hanami/pull/536

@cllns @joneslee85 can you please verify? Thanks!

**Comment by jodosha** [comment]
@cllns Welcome to the contributors team! :wink: Can you please take care of this? Thanks!

**Comment by cllns** [comment]
Thanks @jodosha :D 
Sure thing!

**Comment by cllns** [comment]
Quick fix is to add the following to your Gemfile:
```
group :test, :development do
  gem 'dotenv'
end
``` 

A few things here:
#### 1. Error handling
The error name isn't correct. The issue isn't that `FileSystemAdapter` cannot be found, but rather that the initializer for that adapter tries to call `sub` on `nil`, when it expects a String. The [error handling code] (https://github.com/hanami/model/blob/master/lib/hanami/model/config/adapter.rb#L106) here catches a `NameError`, which is the superclass of `NoMethodError`. In this case, we'd rather have the original error, I think.

#### 2. Environment variable
The `uri` param is `nil` [coming in to the FileSystemAdapter](https://github.com/hanami/model/blob/master/lib/hanami/model/config/adapter.rb#L105). This is because the Environment variables for the Database URI aren't being correctly loaded.

#518 made `dotenv` a soft dependency. 
The issue is that `dotenv` isn't in the generated Gemfile. This is because running `hanami new`, even with `--hanami-head`, uses the current installed version, which my case is 0.7.2. That version has `dotenv` in the gemspec, but on HEAD `dotenv` is expected to be in the generated Gemfile instead since `dotenv` is no longer in the `gemspec`. 

I recommend reverting that commit and leaving it on a branch until `0.8.0` can be released.
Or, we can just wait until `0.8.0` is released and this problem goes away. It only affects people using `hanami-head`, who are willing to tolerate some instability.

#### 3. Assert `uri` is a String
Inside of FileSystemAdapter, we can cast `uri.to_s` to get an empty string, if `uri` is `nil`, but then you still get a confusing error for trying to create a directory that's an empty string: `Cannot instantiate adapter of Hanami::Model::Adapters::FileSystemAdapter (No such file or directory @ dir_s_mkdir - ) (RuntimeError)` so maybe we should just assert that URI can receive `to_s` and has a length greater than 0. This can probably go inside `AbstractAdapter`, since they all need real `URIs`, except MemoryAdapter. Or, it's probably fine in FileSystemAdapter, since the SQL Adapters will blow up in other ways when they get an invalid URI.


I know `hanami` is focused on minimizing dependencies, but the [`envforcer`](https://github.com/mojotech/envforcer) is really neat and could be useful, to ensure you know about missing ENV variables *before* they become a problem.

**Comment by jodosha** [comment]
> This is because running hanami new, even with --hanami-head, uses the current installed version, which my case is 0.7.2.

True. Generating a new project requires `hanami`. It's a combination of generators, shipped with the gem, it's hard to package `hanami/hanami` repository on the fly and use it to create a new project.

---

Indeed, I use that flag (`--hanami-head`) within the local repository of hanami.

```shell
➜ pwd
/Users/luca/Code/hanami/hanami
➜ bundle exec hanami new bookshelf --hanami-head=true
# ...
```

---

@cllns Thanks for the really good research job. I think we can close this now.

**Comment by mooreniemi** [comment]
Sorry to ask this here, but I've just encountered this error, and I don't see anywhere documented how to actually deal with it.  I want to run a hanami app _without a database_. Is this not possible? I expected using `hanami new <app_name>` would create an immediately runnable app via `hanami server` but instead I reached this error.

**Comment by cllns** [comment]
@mooreniemi what version of `hanami` are you using? Head on over to the [Hanami chat](https://gitter.im/hanami/chat) and ping me, if you want, and we can figure this out :)

**Comment by cllns** [comment]
@mooreniemi Ah, so this hasn't been released as a gem yet. The issue is that the `DATABASE_URL` environment variable is missing. 

It *should* be in `.env.development` as something like  `DATABASE_URL="file:///db/bookshelf_development"`. 
Note that you need to have `dotenv` required from your project, like: 
```
group :test, :development do
  gem 'dotenv'
end
```

**Comment by mooreniemi** [comment]
Thanks, I will try that! Might want to offer an option for `--no-persistence` at some point. :)
