### ISSUE TITLE
cjsx?

### ISSUE THREAD

**Issue by nbolt** [hanami/hanami#558]
is there any way to use the cjsx preprocessor in hanami or use multiple asset engines?

**Comment by jodosha** [comment]
@nbolt Hello. :smile: 

We support all the preprocessors that Tilt supports. Are you using `ruby-coffee-react`? I think it could be a good chance for the maintainers to offer Tilt support. Not for Hanami, but for compatibility with the entire Ruby ecosystem.

In the meantime, a file like this can do the trick for you:

```ruby
# hanami_coffee_react.rb
begin
  require 'tilt'
  require 'tilt/template'
  require 'coffee_react'
rescue LoadError
  puts "Please install `tilt' or `ruby-coffee-react' gem"
  exit 1
end

unless defined?(Tilt::CoffeReactTemplate)
  module Tilt
    class CoffeReactTemplate < Template
      def prepare
        options[:filename] ||= file
      end

      def evaluate(scope, locals, &block)
        @output ||= CoffeeReact.transform(data)
      end
    end
  end

  Tilt.register(Tilt::CoffeeReactTemplate, 'cjsx')
end
```

Remember to use it with files with the proper extension: `foo.js.cjsx`.

---

Speaking of multiple assets engines, no we don't support them. We want to keep it simple at fast at the deploy.. until there isn't the proof that we need that feature.

---

Closing this ticket, have a nice day. :dog:
