### ISSUE TITLE
Namespace issue with generated files

### ISSUE THREAD

**Issue by fidothe** [hanami/hanami#561]
I just ran into this problem with a container app.

We had a container called `events`, so the generated `ApplicationLayout` class looked like:

```ruby
module Events
  module Views
    class ApplicationLayout
      include Events::Layout
    end
  end
end
```

Then we also created an `Events` view for that app, at `Events::Views::Events`

On the original developer's machine everything works, and the app is fine. On another developer's machine, because of what I am assuming are file system semantics related to the order in which directory entries are returned, the code defining `Events::Views::Events` gets loaded before the layout. When the layout file is loaded Ruby's namespace lookup goes hunting for `Events::Layout` and finds `Events::Views::Events`, then looking for `Events::Views::Events::Layout`, which doesn't exist. That raises an error bringing everything to a crashing halt.

Obviously, there's a sound argument to be made that naming the view the same as the app is silly, but because debugging this just took me a couple of hours, I think some help from the framework here would be good. 

My question is whether this should be limited to a warning in the documentation (which I will be happy to write and submit a PR for), or to change the generator so that `include ::AppName::Layout` is used instead of `include AppName::Layout` (which I would also be happy to supply a PR for). I haven't been able to come up with a reason why `include ::AppName::Layout` is a bad default, but I haven't searched widely enough to figure out where such a generator change would also need to be made to remain consistent, and if that might in itself become a bigger headache... 

Thoughts?

**Comment by jodosha** [comment]
@fidothe Thanks for reporting this. 👍 
I won't worry too much about this issue because it's an edge case **and** this is the way that Ruby works.

Documenting this warning (like you said), should be enough. Would you mind to submit a PR for the guides? Thanks!
