### ISSUE TITLE
Can't get access to bash environments

### ISSUE THREAD

**Issue by valexl** [hanami/hanami#576]
I try to load some bash environments and found strange behavior. When I try to load this variable via console everything works fine -
```bash
#~/.bashrc
export TTT="hello"
```

```bash
$ hanami console
2.2.1 :001 > ENV['TTT']
 => "hello"
```

But when after reloading web-server I tried to do it via byebug it didn't work

```bash
#apps/web/application.rb
83:         byebug
(byebug) ENV['TTT']
nil
```
PS I've reloaded web-server.

**Comment by joneslee85** [comment]
How do you do `reloading server`?

**Comment by valexl** [comment]
I don't know what it was. Now it works fine. I'll close the issue. Thanks.
