### ISSUE TITLE
Problems with app generation

### ISSUE THREAD

**Issue by rafaels88** [hanami/hanami#577]
So, I created these issues just to inform about 2 problems that I found when I followed the getting started instructions. 

1) Following the instructions here (http://hanamirb.org/) I got this error after `bundle install && bundle exec hanami server`: `Class: Hanami::Model::Config::AdapterNotFound`

I figured that I should specify the database adapter with `--database` as argument when generating my app. So, this problem was resolved, despite this is missing in the instructions above.

2) After trying with `--database` argument when generating, I got this error: `RuntimeError: Cannot instantiate adapter of Hanami::Model::Adapters::SqlAdapter`. I figured I should resolve this:

```
Hanami::Model.configure do
  adapter type: :sql, uri: ENV['WEB_DATABASE_URL']
```

Since I did not have any value in this env variable, I was having the problem above. So, I created a `.env` file and set a value for this.

All of this was easy to resolve, but I was not able to find any reference for this errors in forums or Hanami official documentation. So, maybe could be nice put these instructions when someone get those errors.

Does it make sense?

**Comment by rafaels88** [comment]
Just figured that I have made a tremendous mistake when generate my app. Please, I am sorry e if it is possibly, remove this issue =)

**Comment by jodosha** [comment]
@rafaels88 No worries :)
