### ISSUE TITLE
Entr failing if too many files in project

### ISSUE THREAD

**Issue by onemanstartup** [hanami/hanami#591]
```
bundle exec hanami server

entr: Too many files listed; the hard limit for your login class is 7168. Please consult http://entrproject.org/limits.html
```
I have a node_modules folder in project and hanami failing to start. 
I cound managed find in source code how to run with globbing `find ./**/*.rb | entr -r bundle exec hanami rackserver` but I think this is not good.

**Comment by jodosha** [comment]
Oh Node.. 😢 

@onemanstartup Thanks for reporting this. My suggestion is to enable `shotgun` from your `Gemfile`, if it's there, `hanami server` will bypass `entr`. Please let us to know if there are other issues. Thanks!

**Comment by onemanstartup** [comment]
@jodosha I'm ok actually with globbing, but there is one more problem with entr. Byebug hangs after displaying information. You can't type anything and can't quit.

**Comment by jodosha** [comment]
@onemanstartup Thanks for this extra report too. 👍
