### ISSUE TITLE
problems when user creates hanami app with - in name

### ISSUE THREAD

**Issue by vasspilka** [hanami/hanami#593]
I noticed that if someone creates an app with an - in the name, for example, `hanami new my-hanami-app`.
It will create an app in the following folder `my-hanami-app` as expected.

This results to the following problems however. When someone wants to generate a model for example
with `hanami g model user` it will look at the project folder name and then will create the model in `lib/my-hanami-app` however the app will look for entities and repositories in `my_hanami_app` resulting in not finding any of the generated models.

**Comment by vasspilka** [comment]
This should be considered in https://github.com/hanami/hanami/issues/500

**Comment by sebastjan-hribar** [comment]
I confirm this behavior. I've just created a test app with `hanami new hanami-bookshelf --database=postgres` to distinguish from the old lotus app and then in my `lib` folder there were both `hanami-bookshelf` and `hanami_bookshelf` folders.

**Comment by jodosha** [comment]
@vasspilka @sebastjan-hribar This should be now fixed in master. Can you please give it a try? https://github.com/hanami/hanami#how-to-use-hanami-head

**Comment by sebastjan-hribar** [comment]
I've tested it and it works as expected. Dashes are replaced with underscores and there are no more duplicated folders like before.

**Comment by vasspilka** [comment]
Perfect I'm closing then.
