### ISSUE TITLE
Problem using routes helper in views

### ISSUE THREAD

**Issue by mdamaceno** [hanami/hanami#596]
I read in the documentation about using routes helper, but it seems it does not work. Example: the code ``<%= link_to group.name, routes.group_path(id: group.slug) %>`` returns 

```
Hanami::Routing::InvalidRouteException: No route (path) could be generated for :group - please check given arguments
```

``hanami routes`` lists on console:

```
WARN: Unresolved specs during Gem::Specification.reset:
      tilt (>= 2.0.1, >= 2.0.2, ~> 2.0)
      mail (~> 2.5)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
                Name Method     Path                           Action                        

              groups GET, HEAD  /groups                        Web::Controllers::Groups::Index
           new_group GET, HEAD  /groups/new                    Web::Controllers::Groups::New 
              groups POST       /groups                        Web::Controllers::Groups::Create
               group GET, HEAD  /groups/:id                    Web::Controllers::Groups::Show
          edit_group GET, HEAD  /groups/:id/edit               Web::Controllers::Groups::Edit
               group PATCH      /groups/:id                    Web::Controllers::Groups::Update
               group DELETE     /groups/:id                    Web::Controllers::Groups::Destroy
```

I resolved this with ``<%= link_to group.name, "/groups/#{group.slug}" %>``. I know it is not a good code, but I can't do it another way.

**Comment by jodosha** [comment]
@mdamaceno Hey, I'm sorry about your problem.

I can't reproduce it locally, for this reason I've created a sample project: https://github.com/jodosha/issue-596. Can you please have a look over there and try if that works for you? Thanks!

**Comment by mdamaceno** [comment]
Hi, @jodosha. Sorry for the long period without an answer. I haven't had time to test it in the last days. I will try it soon as possible.

**Comment by jodosha** [comment]
@mdamaceno Ping 😄

**Comment by theCrab** [comment]
@jodosha I can confirm this is not working. But resolves properly when using the method he shows.

**Comment by bruz** [comment]
I saw this error, but in my case rightfully so because the `id` value I was passing in was nil. @mdamaceno and @theCrab, can you post a minimal example project that reproduces the problem, or can you tell what's different between your code and the example @jodosha posted?

**Comment by jodosha** [comment]
@mdamaceno @theCrab PING again 😉

**Comment by joneslee85** [comment]
@mdamaceno @theCrab can you please provide sample code (ideally based on the upstream hanami version)? If you two are not able to work on a fix, I gladly take this on. (cc @duykhoa if you are keen on contribution to Hanami, this issue seems to be a good one)

**Comment by theCrab** [comment]
@jodosha @joneslee85 I have had a look at this from the upstream hanami version and all works. I have also updated my app and removed the *string* path. And all is working well. So I think this issue is fixed somehow with the updates.

**Comment by jodosha** [comment]
@theCrab Thank you for the feedback!! 👍

**Comment by mdamaceno** [comment]
I confirm all is working well.
