### ISSUE TITLE
On testing handle_exception code

### ISSUE THREAD

**Issue by mereghost** [hanami/hanami#597]
Not sure if it's better to open this issue here or on controller.

To the code:
```ruby
class NotEnoughAwesomeness < StandardError
end

module Web::Controllers::Awesomeness
  class Index
    handle_exception NotEnoughAwesomeness => :handle_lameness
    def handle_lameness(exception)
      halt 400, exception.message
     end
    def call(params)
      raise NotEnoughAwesomeness, 'too lame'
    end
  end
end
```

How can this be tested? Exceptions are not handled in test environment (which is good) so the `handle_exception` code is not triggered.

If I test the handler method, `:halt` is thrown and never caught which leads me to an `UncaughtThrowError`.

If I change the `halt` call to `status` I can't test the status code while testing the handler method because it returns the string (that it assigned to self.body), while testing the whole action leads to the problem above.

[Gemfile.lock](https://gist.github.com/mereghost/de8e8500e6090a9eeb65689b506fdaaa)
Edit: premature enter syndrome.

**Comment by jodosha** [comment]
@mereghost What I do in cases like this is:

```ruby
before do
  described_class.configuration.handle_exceptions true
end

after do
  described_class.configuration.handle_exceptions false
end

# specs here...
```

---

Please ask future questions in chat or over https://discuss.hanamirb.org/ Thanks!
