### ISSUE TITLE
Hanami errors when a custom 404 page has been rendered by a middleware

### ISSUE THREAD

**Issue by fidothe** [hanami/hanami#602]
Following on from the discussion on #509 and #599, I created a minimal app to see what happens with the new non-200 status rendering code with my 404-page-rendered-by-middleware use case.

Unfortunately Hanami now 500's (before it would escape the rendered HTML and render the standard default page with the custom HTML rendered as source, effectively). The minimal app is at https://github.com/fidothe/middleware_404.
## Expected behaviour

Custom 404 page rendered by middleware is displayed when 404 encountered
## Actual behaviour

Hanami returns 500 status code
## Reproduction steps

Run the specs in the demonstrator app, or run `hanami server` and visit any page except `/`
(See https://github.com/fidothe/middleware_404/blob/master/README.md for instructions on reproduction and workaround)

**Comment by fidothe** [comment]
I haven't had a chance to figure what's broken here (it's different to what happened before #599). I'll do that and if possible (i.e. if it doesn't look like a massive architectural change) I'll work up a PR as soon as I can (should be this week)

**Comment by jodosha** [comment]
@fidothe Sorry for the delay. I was able to make your test project to work, by applying the fix shipped with #609

**Comment by jodosha** [comment]
@fidothe I'm sorry, but #609 isn't a viable solution for this problem.

**Comment by jodosha** [comment]
This is an edge case that would require too much changes. I'm not keen to act on it because time pressure (upcoming 1.0).

**Comment by fidothe** [comment]
No worries
