### ISSUE TITLE
Be able to rollback migrations

### ISSUE THREAD

**Issue by greggilbert** [hanami/hanami#603]
So we have `hanami db migrate`. It'd be great if we could do `hanami db rollback` to rollback the most recent migration. I think right now you have to invoke Sequel directly to do any sort of rollbacks (or write a Rake script to do that), so having this would be a huge convenience.

**Comment by jodosha** [comment]
@greggilbert This feature is already implemented: if you provide a version number, it "migrates down" to that version. Please have a look here: http://hanamirb.org/guides/command-line/database/#migrate

**Comment by cllns** [comment]
Ah, thanks Luca! I searched and found nothing in `hanami/hanami` and `hanami/model` but not the guides. I'd still be in favor of `hanami db rollback` command, but I don't think it comes up often enough to be very important.

**Comment by katafrakt** [comment]
Still no chance for `rollback` command? I keep forgetting it's not there and missing it during casual development.

**Comment by cllns** [comment]
@katafrakt I'm in favor of adding `rollback`. 

What do others think @hanami/core?

**Comment by b264** [comment]
To be clear, this is just syntactic sugar on for "db migrate (max minus one)", right?  Why not go all-in and use git-inspired `bundle exec rake db migrate HEAD~1`

**Comment by AlfonsoUceda** [comment]
I think we could support it 👍

**Comment by b264** [comment]
There is a distinct concept of `HEAD`: the latest migration.  It may not be called that, but the concept is very present.  In a chain of migrations, there is a newest one

 Also, what is the desired behaviour if there are new migrations that have never been run?  Say I wrote 3 new migrations that weren't ran, then executed `bundle exec hanami db rollback 2`  What is the outcome?  Does it migrate forward one (MAX-2 aka CURRENT+1) or does it migrate backward two (MAX-5 aka CURRENT-2)?  The latter seems more appropriate, I think

**Comment by cllns** [comment]
True, the concept exists but the name doesn't.

I agree `bundle exec hanami db rollback 2` should do CURRENT-2 (so MAX-5)

**Comment by jodosha** [comment]
We have a concept of `HEAD`, it's `hanami db version`.

**Comment by AlfonsoUceda** [comment]
@jodosha if you don't mind, I'm working on this feature.

**Comment by jodosha** [comment]
Implemented by https://github.com/hanami/hanami/pull/822
