### ISSUE TITLE
Code reloading not happening with Hanami HEAD

### ISSUE THREAD

**Issue by bruz** [hanami/hanami#619]
Here's a minimal example to reproduce what I'm seeing:

Create a new app as [described in the README](https://github.com/hanami/hanami#how-to-use-hanami-head) and start it up:

```bash
git clone https://github.com/hanami/hanami.git
cd hanami
bundle
bundle exec hanami new --hanami-head=true bookshelf
cd bookshelf
sed -i.bak "s/gem 'hanami'.*/gem\ 'hanami',\ path:\ '..'/" Gemfile
bundle
bundle exec hanami generate action web books#new
bundle exec hanami server
```

Then, in another terminal window, update the template and see that the updated content isn't in the response:

```bash
echo "UPDATED CONTENT" >> apps/web/templates/books/new.html.erb
curl http://localhost:2300/books/new
```

Output:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Web</title>
    <link href="/assets/favicon.ico" rel="shortcut icon" type="image/x-icon">
  </head>
  <body>

  </body>
</html>
```

I threw a quick logging statement in `Hanami::Commands::Server#start` and see that `@strategy` is set as `shotgun`, so I'm not sure what's going wrong.

**Comment by cllns** [comment]
Thanks for reporting this!

Is `shotgun` in your Gemfile? It should be, but I just want to make sure. It's not a dependency of `hanami` because it doesn't work on all systems, so we put it in the default Gemfile instead.
