### ISSUE TITLE
const_defined? should be scoped in loader

### ISSUE THREAD

**Issue by pascalbetz** [hanami/hanami#631]
Otherwise classes like ```Web::Routes``` will not get defined if a const called ```Routes``` already exists.

Same goes for ```Logger```, ```View```, ```Controller```, ```Assets```, ```Model```.

Reproduce the problem:

* hanami new sample
* create a (empty) class ```Routes``` and make sure it is required before ```Loader```
* bundle exec hanami console
* Web::Routes #> will lead to an exception
```
NameError: uninitialized constant Web::Routes
Did you mean?  Routes 
```

This is because ```const_defined?``` automatically checks the parent namespace for existence of the constant if constant was not found incurrent namespace. 

So lines like ```unless application_module.const_defined?('Routes')``` should actually be 
```unless application_module.const_defined?('Routes', false)````
(Example from https://github.com/hanami/hanami/blob/master/lib/hanami/loader.rb#L219)

See http://ruby-doc.org/core-2.2.0/Module.html#method-i-const_defined-3F for details on ```const_defined?```

**Comment by jodosha** [comment]
@pascalbetz Great catch! Would you mind to create a PR to fix this issue? Thanks!

**Comment by pascalbetz** [comment]
@jodosha here you go:-)
