### ISSUE TITLE
Generated view spec

### ISSUE THREAD

**Issue by TiteiKo** [hanami/hanami#639]
Hi all,

I was wondering why the default test in the generated view spec looks like this:

```ruby
# ...
let(:exposures) { Hash[foo: 'bar'] }
# ...

it 'exposes #foo' do
  view.foo.must_equal exposures.fetch(:foo)
end
```

As this test will pass no matter what, wouldn't it be better to have a test like

```ruby
# ...
let(:exposures) { Hash[] }
# ...

it('renders') { rendered }
```

It ensures that the view renders, which is imho the view equivalent of the action test "it is successful". The actual test being always successful, it's easy to forget to actually test the view.

This is really not critical or even important, just a thought 😄

**Comment by vladdypwnz** [comment]
Minimalistic. I like it.

**Comment by jodosha** [comment]
@TiteiKo Hi 😄  The reason why we have that filled hash is to demonstrate how to pass exposures and how to use them. Having that stupid example teaches how to do without the need of reading the guides to unit test a view.

That being said, I'm not thrilled by this specific solution. If we can teach how to use exposures in unit tests in a better way, I'm absolutely open to change it. Just open a PR if you have ideas 😄  /cc @vladdypwnz
