### ISSUE TITLE
Application configuration double-executed

### ISSUE THREAD

**Issue by fidothe** [hanami/hanami#643]
Application configurations are double-executed when running `hanami server`.  The first time is when https://github.com/hanami/hanami/blob/master/lib/hanami/commands/server.rb#L25 runs, and the second by starting the app (https://github.com/hanami/hanami/blob/master/lib/hanami/commands/server.rb#L33 or https://github.com/hanami/hanami/blob/master/lib/hanami/commands/server.rb#L35).

This produces the double-middleware behaviour reported in #638.

I'll add a simple reproducing app shortly.

If this is a bug, then the root cause seems to be that there's an implicit assumption that `Hanami::Loader#load_configuration!` is memoized and subsequent calls will not re-execute the already-loaded configuration.

**Comment by jodosha** [comment]
@fidothe Hello. This is fixed by https://github.com/hanami/hanami/commit/4de8fd5ba80f14f38ddccee3ad0a696cef5b3bb3, which will be merged soon.

**Comment by fidothe** [comment]
@jodosha fabulous, thanks!

**Comment by jodosha** [comment]
As #657 was merged, we can close this too.
