### ISSUE TITLE
Issue with load_paths

### ISSUE THREAD

**Issue by dikond** [hanami/hanami#646]
Hello everyone :v:

We've encountered some odd behavior when trying to configure our application. At the moment, I am not sure how `load_paths` works. Does it load files immediately or not?

So in the `class Application < Hanami::Application` I had to add `require_relateve` per each `include` under `controller.prepare`, whereas my friend doesn't `require` these modules and it works just fine. We have the same versions of gems and ruby, both of us uses `rbenv`. The main difference is that he uses macbook and I am a laptop with derivative of Ubuntu 14.04 as OS. 

The folders that get loaded:
```ruby
load_paths << [
  'helpers',
  'controllers',
  'views'
]
```

The problem code looks like:
```ruby
controller.prepare do
  # require_relative 'controllers/authentication'
  # require_relative 'controllers/authorize'
  # require_relative 'controllers/csrf_protection'

  include Web::Controllers::Authorize
  include Web::Controllers::Authentication
  include Web::Controllers::CsrfProtection
  expose :flash
end
```

Those are all modules, which mix some common behaviour. They do not `require` or `load` anything. If I'll remove those `require_relative` I'll get `NameError: uninitialized constant Web::Controllers::Authorize` when running `bundle exec hanami s`. So that my server doesn't even start.

We checked this on the other machines with same results. On the macbook everything is ok, on ubuntu distros the same problem. 

I've created a gist of our [Gemfile.lock](https://gist.github.com/dikond/7ae4b86fcb0073b014df1fcbdc10dd7d) and a [stack trace](https://gist.github.com/dikond/3b4745dcbcd3508ed3d8358a72788a66).

**Comment by cllns** [comment]
Are you both using `HANAMI_ENV=development`? Can you try with `HANAMI_ENV=production`?

**Comment by dikond** [comment]
Originally, we've tried with `bundle exec hanami s`. I've also tried as you suggested - the result is the same.

**Comment by kkolotyuk** [comment]
I have the almost the same problem but with other files. I'm on 14.04 (also tried on 16.04). My colleges with macbooks don't have this problem.

**Comment by TrevorBramble** [comment]
Another data point, co-worker and I are experiencing the same difference in the _opposite_ direction. Works without errors on my Linux, but hits uninitialized constant on his Mac. I suspect this has to do with how files and directories are ordered on the systems, either by the OS or by Ruby when recursing through the directories given to `load_path`, so with that in mind here's some more info.

Our scenario has a shared module as shown in the [example guide](http://hanamirb.org/guides/actions/share-code/), `apps/web/controllers/authentication.rb`, and the (alphabetically) first file in the directory `apps/web/controllers/authentication/handler.rb` is where the application bombs on his machine with an unsatisfied reference to the shared module's constant.

We're both using MRI 2.3.1, Hanami 0.8.0.

**Comment by cllns** [comment]
It looks like [`load_paths` calls `Dir.glob`](https://github.com/hanami/hanami/blob/113eeb41df8e9c5b8d763b2a6e40d68e9ff61885/lib/hanami/config/load_paths.rb#L16), which is [apparently different on different operating systems](http://stackoverflow.com/a/5529966).

Can someone try:
```
gem "hanami", github: "cllns/hanami", branch: "sort-load-paths"
```

Let me know if it works and I'll open a PR 💖

**Comment by kkolotyuk** [comment]
@cllns it helps me!
