### ISSUE TITLE
Hanami::Utils::Hash#symbolize! does not handle arrays

### ISSUE THREAD

**Issue by greggilbert** [hanami/hanami#653]
I'm not sure if `symbolize!` is supposed to be in or if it's deprecated or what, but it doesn't handle nested arrays. Consider:

```
test = {
  'foo' => [
     {
       'bar' => 'baz'
     },
     {
       'bat' => 'quux'
     }
  ]
}
hashed = Hanami::Utils::Hash.new test
hashed.symbolize!
```

I'd expect `hashed` to have [`:bar`] and `[:bat]`, but they remain as strings.

**Comment by jodosha** [comment]
@greggilbert This is fixed now, but not released yet. Please notice that since now on you should use `Utils::Hash#deep_symbolize!` for deep symbolization. `Utils::Hash#symbolize!` will only symbolize the top level keys.

**Comment by jodosha** [comment]
@greggilbert An update: I had to revert that fix, because it was breaking Hanami::Entity. I'm afraid we can't support this case for now. Sorry.

**Comment by greggilbert** [comment]
Oof. Alright then, no worries. Thanks anyway.
