### ISSUE TITLE
Custom generators

### ISSUE THREAD

**Issue by beauby** [hanami/hanami#659]
What is the recommended way to add custom generators for Hanami as part of a gem?

**Comment by cllns** [comment]
This might help: https://github.com/davydovanton/hanami-scaffold/blob/master/lib/hanami.rb

**Comment by beauby** [comment]
Yeah I've seen that. However the problem with that approach is that depending on the order in which `hanami` and `hanami-scaffold` are added to the load path, `require hanami` may or may not load the `hanami-scaffold` `hanami.rb`. 
Moreover, this approach does not allow multiple gems to define new generators.

**Comment by jodosha** [comment]
I'm thinking of a CLI rewriting after 1.0, because the current implementation is messy.
Adding custom (sub)commands, and custom generators will be in the scope of the project.
