### ISSUE TITLE
Consider marking generated tests as skipped/pending

### ISSUE THREAD

**Issue by smaximov** [hanami/hanami#660]
This primarily applies to the "action" generator.

When running Hanami generators, they are usually generate some tests as well. And while the [setup part](https://github.com/hanami/hanami/blob/8ed4acba0ca268ba6c78f74c4a01e4a7c4a49118/lib/hanami/generators/action/view_spec.rspec.tt#L4-L7) of these tests is great, the [actual test](https://github.com/hanami/hanami/blob/8ed4acba0ca268ba6c78f74c4a01e4a7c4a49118/lib/hanami/generators/action/view_spec.rspec.tt#L9-L11) is pretty useless. Futhermore, since these tests silently pass, it's very easy to forget about them.

The solution is to mark generated tests as pending/skipped. It requires trivial changes: add the calls to `skip` to the test example blocks with an explaination why these tests are skipped, e.g.: 

``` ruby
  it 'exposes #foo' do
    skip "This is an autogenerated test. Edit it or delete this file"
    view.foo.must_equal exposures.fetch(:foo)
  end  
```

to the tests' templates. Such tests are easy to spot in the output:

<details>
  <summary>(<strong>CLICK ME!</strong>) Minitest: <code>$ TESTOPTS="-v" rake test</code></summary>

```
Run options: -v --seed 53680

# Running:

Web::Views::Home::Index#test_0001_exposes #foo = 0.00 s = S
Web::Controllers::Home::Index#test_0001_is successful = 0.00 s = .

Finished in 0.001496s, 1336.7251 runs/s, 668.3625 assertions/s.

  1) Skipped:
Web::Views::Home::Index#test_0001_exposes #foo [/home/nameless/samples/hanami/foo_minitest/spec/web/views/home/index_spec.rb:11]:
This is an autogenerated test. Edit it or delete this file

2 runs, 1 assertions, 0 failures, 0 errors, 1 skips
```

</details>

<details>
<summary>(<strong>CLICK ME!</strong>) RSpec: <code>$ rake spec</code></summary>

```
/home/nameless/.rvm/rubies/ruby-2.3.1/bin/ruby -I/home/nameless/.rvm/gems/ruby-2.3.1@hanami/gems/rspec-core-3.5.4/lib:/home/nameless/.rvm/gems/ruby-2.3.1@hanami/gems/rspec-support-3.5.0/lib /home/nameless/.rvm/gems/ruby-2.3.1@hanami/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
.*

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Web::Views::Home::Index exposes #foo
     # This is an autogenerated test. Edit it or delete this file
     # ./spec/web/views/home/index_spec.rb:9


Finished in 0.0013 seconds (files took 0.93006 seconds to load)
2 examples, 0 failures, 1 pending
```

</details>

What do you think about it?

**Comment by cllns** [comment]
I like this idea!

**Comment by jodosha** [comment]
I like it. What the rest of @hanami/core-team @hanami/contributors think?

**Comment by AlfonsoUceda** [comment]
yes, me too 👍

**Comment by pascalbetz** [comment]
+1

**Comment by theCrab** [comment]
Yes +1

**Comment by TiteiKo** [comment]
I wouldn't put the `or delete this file` wording, but something more like `Edit it and add your own tests`, to not openly suggest to people to delete test files, but instead to give them incentive to actually write tests.

**Comment by davydovanton** [comment]
awesome idea 👍

**Comment by theCrab** [comment]
This is done.

**Comment by AlfonsoUceda** [comment]
Closing by #664
