### ISSUE TITLE
Force SSL includes default port in redirect

### ISSUE THREAD

**Issue by createdbypete** [hanami/hanami#666]
Experienced in Hanami v0.8.

### Scenario

When the `force_ssl` option is set but `port` and `HANAMI_PORT` are not set the [port passed to `Hanami::Router`](https://github.com/hanami/hanami/blob/0.8.x/lib/hanami/loader.rb#L240) is the default (`2300`) this causes the result http => https redirect to have the port `2300` which causes the response to hang.

See `curl` output below:

```
$ curl -sv http://a-force-ssl-site.com
* Rebuilt URL to: http://a-force-ssl-site.com/
*   Trying x.x.x.x...
* Connected to a-force-ssl-site.com (x.x.x.x) port 80 (#0)
> GET / HTTP/1.1
> Host: a-force-ssl-site.com
> User-Agent: curl/7.49.1
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Date: Tue, 15 Nov 2016 01:33:29 GMT
< Location: https://a-force-ssl-site.com:2300/
< Content-Length: 0
< Connection: keep-alive
<
* Connection #0 to host a-force-ssl-site.com left intact
```

Setting the port to `443` for the production environment resolves issue although this conflicts with [generator comment]( https://github.com/hanami/hanami/blob/0.8.x/lib/hanami/generators/app/application.rb.tt#L49-L53) which also appears to suggest that the port may be figured out by the scheme however, [this does not appear to be the case](https://github.com/hanami/hanami/blob/0.8.x/lib/hanami/environment.rb#L326-L328).

>URI port used by the routing system to generate absolute URLs
>Argument: An object coercible to integer, default to 80 if the scheme is http and 443 if it's https
>This SHOULD be configured only in case the application listens to that non standard ports

**Comment by cllns** [comment]
😈

**Comment by joelvh** [comment]
Is the proper way to setup Hanami on Heroku to set `HANAMI_PORT` explicitly? When `force_ssl` is set to `true` and I don't specify a port, it seems to redirect to the Heroku-assigned port (on their internal network). When I set the `port` option in my Hanami configuration explicitly to 443, there's a redirect loop that includes the port 443 in the `Location` redirect URL.

In my setup, I use `force_ssl` with no `port` specified and the solution to work on Heroku for me was to set `HANAMI_PORT = 443`, but this seems redundant. Am I missing something?

**Comment by joelvh** [comment]
For completeness, I am referring to the `PORT` environment variable as the Heroku-assigned port. Without `HANAMI_PORT` set, the forced redirect included port 4334, which seemed to be coming from `PORT` (assigned by Heroku for internal port mapping).
