### ISSUE TITLE
Allow for messages to be passed to custom error pages

### ISSUE THREAD

**Issue by nicosuave** [hanami/hanami#668]
As much as I appreciate the ability to set a custom error page template for [each status code](http://hanamirb.org/guides/views/custom-error-pages/), sometimes I find myself needing more granularity.

I would like to expose a view method with the message passed into `#halt` from the controller action.

I am aware that I can effectively accomplish the same thing by:
- calling `status` instead of `halt`
- setting an instance variable with error message
- short circuiting the controller action

**Comment by jodosha** [comment]
@nicosuave Hi, can you please describe in terms of code what do you mean? I'm not 100% sure of have grasped what you have in mind.

**Comment by AlfonsoUceda** [comment]
Hi @nicosuave, could you provide an example as @jodosha said? Thanks!

**Comment by AlfonsoUceda** [comment]
I'm going to close this issue because there isn't answer.
