### ISSUE TITLE
Consider generating a migration when generating a model

### ISSUE THREAD

**Issue by beauby** [hanami/hanami#670]
Generating a model (via `$ hanami generate model foo`) currently generates an entity along with a repository (but no migration). However, repository schema inference expects a corresponding table to exist, so generating a model effectively leaves the app in broken state (unable to boot).

**Comment by jodosha** [comment]
What the rest of @hanami/core-team @hanami/contributors think?

If we're going to implement this, we should also consider to add a `--skip-migration` flag.

**Comment by beauby** [comment]
Having it generate a migration by default (if corresponding table does not already exist), and exposing a `--skip-migration` option seems like the way to go. :+1:

**Comment by cllns** [comment]
I think generating a migration by default is a good idea (along with `--skip-migration`).

Do we want to leave them blank, or should we allow attributes to be passed as well?

For example: ```hanami generate model Person name age:integer``` (where `name` is a string by default). I'm in favor of that, but happy to leave that feature to future work, and just add a blank migration for now :)

**Comment by theCrab** [comment]
I would leave them blank, but put an example structure in the file as a comment.

**Comment by beauby** [comment]
@cllns I don't feel strongly about the auto-creation of attributes (it's clearly a nice feature to have, but it's not _that_ important), so I'd vote for leaving it to future work (talking about future work, it would be nice to have a place listing some wanted non-core/easy to implement features for new contributors).

**Comment by jodosha** [comment]
What I'd do is:

```shell
bundle exec hanami generate model book
```

Which will generate this migration:

```ruby
Hanami::Model.migration do
  change do
    create_table :books do
      primary_key :id

      column :created_at, DateTime, null: false
      column :updated_at, DateTime, null: false
    end
  end
end
```

Thoughts?

**Comment by theCrab** [comment]
I think that is a better improvement @jodosha

**Comment by yjukaku** [comment]
I just opened a PR that implements @jodosha 's suggestion of a basic 'create_table' migration, but I agree with @cllns that eventually Hanami should add the ability to specify attributes as well.  It's just so useful, and helps when building quickly (especially if going off of an entity diagram that you've already written).  

For example, at the start of a project, I often spend a day or two whiteboarding all of the models I expect an app to need, along with various attributes.  Then I sit down and start generating models (using Rails `rails g model user name:string age:integer email:string:unique ...`).  I would hate to have to  type those manually by hand in multiple places, if I'm generating a dozen or so models at the same time.

**Comment by jodosha** [comment]
@yjukaku Thanks again for that PR. When you can, please have a look at my comments.

My suggestion is to take baby steps here. Let's make this to work, then we can add attributes as CLI arguments.

---

> For example, at the start of a project, I often spend a day or two whiteboarding all of the models I expect an app to need, along with various attributes. Then I sit down and start generating models (using Rails rails g model user name:string age:integer email:string:unique ...). I would hate to have to type those manually by hand in multiple places, if I'm generating a dozen or so models at the same time.

I respect your way to work, but we want to discourage this waterfall planning. We put in place strong tools for BDD/TDD and agile iterations.

**Comment by yjukaku** [comment]
You're welcome!

I don't agree that this encourages waterfall planning, but yes, lets get the current PR working before moving on to attributes generation. 👍

**Comment by katafrakt** [comment]
> I would hate to have to type those manually by hand in multiple places

I wonder what you mean by multiple places. If I'm not wrong, you only have to write it in the migration itself. I wouldn't ever fully trust autogenerated migration anyway, so I have to check them before committing and running. This sounds like a good time for writing actual fields there too.

I believe that specifying attributes list in the command is only useful if you use some kind of a scaffold to generate the forms and views. And I certainly hope that Hanami is not going to support anything like that :wink:
