### ISSUE TITLE
Consider adding `--api` option to generator.

### ISSUE THREAD

**Issue by beauby** [hanami/hanami#673]
It would basically remove the view and assets-specific generated code, but also the hard-dependency on `hanami-view` and `hanami-assets` in the generated Gemfile.

Modifications include: 
- not generating views, templates, and specs for those
- in the generated application, no configuration for views and assets, no `views/` in the load paths

**Comment by jodosha** [comment]
@beauby Generator for what?

**Comment by beauby** [comment]
@jodosha I meant for `$ hanami new`.

**Comment by mereghost** [comment]
Am I the only weird one that renders the JSON responses on the view layer? =/

**Comment by jodosha** [comment]
@beauby We just removed one architecture named "application", which was similar to your idea. But the burden of maintaining it, wasn't worth the effort.

After 1.0, we can decide to have another gem only focused to it.

**Comment by jodosha** [comment]
@mereghost 
> Am I the only weird one that renders the JSON responses on the view layer? =/

Nope, I'm delegating it to the view too. It's speculative to assume that all the devs won't use the view layer.

---

For now devs can generate a new app within a project, and threat it as an API.
