### ISSUE TITLE
Consider adding a centralized list of "good for new contributors" issues.

### ISSUE THREAD

**Issue by beauby** [hanami/hanami#674]
It would help engage the community and raise exposure. It could also link to issues on non-hanami but related projects (like ROM, rspec-hanami, etc.).

**Comment by davydovanton** [comment]
hey, what do you mean on this? You want to see list for people how want to contribute or list with helpful projects?

**Comment by beauby** [comment]
@davydovanton I meant a list of issues that the hanami maintainers want solved, and that are easy enough to tackle and not too high priority so that they can be left to new contributors.
I know that for the latter you're already keeping the [http://awesome-hanami.org/](http://awesome-hanami.org/) list ;).

**Comment by devonestes** [comment]
I think the way that this is handled for many projects is to have something like a `good_first_patch` label on certain open issues that maintainers leave for new contributors. That's typically easier to manage (from a maintainer's perspective) than keeping a separate list.

**Comment by davydovanton** [comment]
@beauby okay, I understand you. Now I'm working on my personal project which solves this problem. I hope I'll publish the first version of this project at the end of November.

But now you can check issues from all projects from hanami-awesome :)

@devonestes you're right 👍

**Comment by beauby** [comment]
@devonestes Agreed, though the centralization could take the form of an org-level GitHub project.

**Comment by mereghost** [comment]
Tagging the simple issues as `good-first-contribution` (or something like that) would help a lot with some minor effort (as there aren't that many issues open).

**Comment by mereghost** [comment]
@beauby Centralization could be even on hanami.org as all that is needed is query the github api for issues with the said tag on hanami organization's repos.

**Comment by devonestes** [comment]
@beauby @mereghost Yeah - along those lines, the easiest thing for the maintainers to do would probably be to just link to a GitHub search page (like this): https://github.com/search?l=&q=repo%3Ahanami%2Fhanami+repo%3Ahanami%2Fhelpers+repo%3Ahanami%2Fmodel+state%3Aopen+label%3Agood_first_patch&ref=advsearch&type=Issues&utf8=%E2%9C%93

**Comment by jodosha** [comment]
Hey folks, this is a link that we used to share on Twitter from time to time: http://bit.ly/hanami-help-wanted

This expands to https://github.com/search?l=&q=user:hanami+state:open+label:help-wanted&ref=advsearch&state=open&type=Issues

Indeed we have a `help-wanted` label across the repos of Hanami.

@davydovanton Isn't this the easiest way to solve this problem?
@cllns Where do we can place this link? (even without the bit.ly shortcut).

**Comment by davydovanton** [comment]
@jodosha good idea. I think we can put this link in to "community" section of site. Also I think we can write about some "help wanted" issues in mail. What do you think?

Also we can create special page with all issues (like gem status).

And the last idea. I told you about my project. We can use it for "help wanted" issues. But now this project is only prototype and I really want to make first production version at January

**Comment by jodosha** [comment]
> Also we can create special page with all issues (like gem status).

Does that would involve manual maintenance of a page from the website? Isn't it too much burden?

**Comment by cllns** [comment]
@jodosha `help-wanted` is not quite the same thing as `good-first-patch`. That is, `good-first-patch` should always have `help-wanted` too, but not all `help-wanted` will be good for first patches.

I think we should add `good-first-patch` as a tag. We can add a link to the `help-wanted` tag and then people can see which are good first patches there. Thoughts on that?

**Comment by jodosha** [comment]
@cllns Okay. @hanami/issues please join the discussion and take a decision.

**Comment by jodosha** [comment]
I mean, take a decision all together 😉

**Comment by AlfonsoUceda** [comment]
Folks I like the idea but do we need to be too granular? I mean we can do it an create a search like the bit.ly link we have for `help-wanted`, but usually issues with label `help-wanted` aren't critical so everyone can do it.

**Comment by beauby** [comment]
The exact way this is handled does not matter much. However, what's important is that those issues are easily identifiable and that a list of those is easily accessible. I'd vote for a distinct `good-for-new-contributors` tag rather than relying on the `help-wanted` one (because it clearly states that it will be easy and does not require in-depth knowledge of the framework). That, combined with an explicit mention on the `CONTRIBUTING.md` of each repo should be enough IMO.

**Comment by AlfonsoUceda** [comment]
@beauby 👍

**Comment by cllns** [comment]
Ok @TiteiKo is that good with you too? If it is, let's go for it!

**Comment by jodosha** [comment]
Pinging @hanami/community too. 😄

**Comment by rafaels88** [comment]
Well, taking for me, I tried to help once with an issue and I got in a trouble, because I was new and I had to know too much at that time about the framework to help in that issue. It would be awesome to have a tag like this.

**Comment by marionschleifer** [comment]
I totally agree. I am a junior programmer and I've been wanting to contribute to open source for some time. And it was almost impossible to find something that I could do. A tag like this would help many new programmers 👍

**Comment by TiteiKo** [comment]
@cllns Sorry for the delay, it's good for me yes! 👍

**Comment by davydovanton** [comment]
@marionschleifer I'm working on oss issue board for new developers (and junior too). You can find this project here:
http://ossboard.herokuapp.com

It's a simple prototype that's why is empty. But in my plans create the first version at the end of December. I think we can use this board for sharing tasks to new contributes.

@jodosha @cllns what do you think, will it helpful for us?

**Comment by cllns** [comment]
I like it @davydovanton! I've thought of making something similar :)

That site would use the `good-for-new-contributors` tag, right?

**Comment by davydovanton** [comment]
@cllns no, you need to create task by hands. But I'll add integration with github/gitlab issues (`import from` button)

**Comment by cllns** [comment]
@davydovanton Hm, why not just automatically sync (via a cronjob) using GitHub's API? (eventually, understand that's more work)

**Comment by jodosha** [comment]
I don't want to introduce dependencies for solving this trivial problem: wait for @davydovanton to finish his project, import issues, link from somewhere.

We'll also depend on the maintenance of that project for our contribution workflow.

We already have plenty of stuff to maintain.

---

My **actionable suggestion** is to ask @hanami/issues and @hanami/community **if** we need that special label, let's create it on GitHub across our repositories.

Then we can link this GH search from the website: https://github.com/search?l=&q=user:hanami+state:open+label:help-wanted&ref=advsearch&state=open&type=Issues

Which is the simplest solution for this problem.

If you agree, @hanami/issues or @hanami/community please take action.

**Comment by oana-sipos** [comment]
@jodosha I would (and can) create a label as @cllns suggested: 

> help-wanted is not quite the same thing as good-first-patch. That is, good-first-patch should always have help-wanted too, but not all help-wanted will be good for first patches.

**Comment by jodosha** [comment]
@oana-sipos Yes, I agree `help-wanted` isn't necessary good for first patches.

---

My suggestion for the label name is based on discoverability. It looks like `easy` is the preferred name in other OSS projects: https://github.com/search?utf8=%E2%9C%93&q=state%3Aopen+label%3Aeasy&type=Issues&ref=searchresults

For more inspiration, please have a look at https://github.com/MunGell/awesome-for-beginners

PS: can @hanami/community craft a PR over this repository ☝️ to add Hanami? Thanks 😄

**Comment by davydovanton** [comment]
@jodosha I added hanami org to this list
https://github.com/MunGell/awesome-for-beginners/pull/59

**Comment by davydovanton** [comment]
@jodosha okay, sorry for the haste 💛

**Comment by TiteiKo** [comment]
I agree on the "easy" label name. Please cast a 👍  or 👎  vote on this post, and I'll create the label in the projects on friday if it's agreed on.

**Comment by oana-sipos** [comment]
@davydovanton it seems your PR was rejected, would you like to resubmit? If needed, I can also take care of it. As you prefer.

**Comment by jodosha** [comment]
@oana-sipos Please go ahead 👍

**Comment by davydovanton** [comment]
@oana-sipos we need to create labels and add contribution file before. And yes, I agree with Luca, do it :)

**Comment by oana-sipos** [comment]
@davydovanton @jodosha indeed, I was reading as well the guidelines and thought of proposing so. I will take care of it on Friday, as soon as @TiteiKo will create the label.

**Comment by jodosha** [comment]
@oana-sipos Please also add a link from  `/community` section from our website.

https://github.com/search?utf8=%E2%9C%93&q=user%3Ahanami+state%3Aopen+label%3Aeasy&type=Issues&ref=searchresults

**Comment by TiteiKo** [comment]
The label is created in the repositories. 

@oana-sipos Feel free to make the PR ;)

@hanami/community Below are the links of the searches for the community page. I'll let you decide what's the best way to display the information there.

* https://github.com/hanami/hanami/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy
* https://github.com/hanami/controller/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy
* https://github.com/hanami/view/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy
* https://github.com/hanami/helpers/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy
* https://github.com/hanami/assets/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy
* https://github.com/hanami/mailer/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy
* https://github.com/hanami/model/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy
* https://github.com/hanami/validations/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy
* https://github.com/hanami/utils/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy
* https://github.com/hanami/router/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy

**Comment by oana-sipos** [comment]
@TiteiKo PR submitted: https://github.com/MunGell/awesome-for-beginners/pull/61

Thanks for the links. Indeed, need to put some thought into displaying the info :yin_yang:

**Comment by jodosha** [comment]
@oana-sipos @TiteiKo Any reason why the link I posted can't be used for our website and that PR? Just curios 🐈

**Comment by oana-sipos** [comment]
@jodosha it can be used, just thought it is cleaner this way. To be honest, did not realize there will be *this* many links :P so if your link is for the whole community, that sounds like a better deal actually. Thanks for pointing it out.

**Comment by TiteiKo** [comment]
@jodosha It can be used, yes! ✨  
I posted all the links so that people would know in which repositories the labels were created and forgot to put your link as a "this one takes all" link

**Comment by MunGell** [comment]
Hey guys,

The PR was merged, but it would be nice to add issues that are beginner-friendly, so you would fully qualify for the list. From this tread I understand that your label for beginner-friendly issues is `easy`.

Thanks!

**Comment by jodosha** [comment]
@MunGell Hi and thanks for merging that PR. We appreciate it!

We're in the process of changing how Hanami is managed, so bear with us for the time being. We're changing for the good and for new people around. 💚

**Comment by oana-sipos** [comment]
I added a link to our issues (labels `easy` and `help-wanted`) on our [Community page](http://hanamirb.org/community/). We'll also make sure to add more tickets with these labels, especially after the 1.0 release. Thanks all for contributing! 💙
