### ISSUE TITLE
Module under /lib is picked up as an app in 0.9 when it is referenced in routes

### ISSUE THREAD

**Issue by vidmantas** [hanami/hanami#681]
Hello,

I was trying to upgrade existing app from 0.8 to 0.9, but ran into the following exception:

```ruby
NameError: uninitialized constant Hanami::Config::Mapper::Youtrack
```
[full stacktrace](https://gist.github.com/vidmantas/a06f54ce4d0ef88eacf6d8d783d25fe2)

Problem is that `Youtrack` is just a plain module (for business logic) under `/lib`. A folder `/lib/youtrack` also exists.

It is possible to replicate the situation on the fresh Hanami app pretty easily: 

1. Add empty module in `/lib` and folder for it `/lib/{yourmodulename}`
2. Add a class under the module `/lib/{yourmodulename}/{yourclassname}`
3. Reference this class in `routes.rb`, e.g. for regexp
4. Fire up a server and go to any URL.

For simplicity, I've created a repo to demonstrate an issue: https://github.com/vidmantas/hanami-routes-bug-report/
Diff that is actually causing the issue: https://github.com/vidmantas/hanami-routes-bug-report/commit/9d5df70f4de072fc0c09552ab2ef5e936ca9c457

As you can see, my ruby version is 2.3.3 and Gemfile.lock is in the [repo](https://github.com/vidmantas/hanami-routes-bug-report/blob/master/Gemfile.lock).

Please let me know if I can help anyhow hunting down this problem!

**Comment by TiteiKo** [comment]
Your files just aren't loaded anywhere

How to fix:

in `config/environment.rb`:
```ruby
require_relative '../lib/unrelated'
```

in `lib/unrelated.rb`:
```ruby
module Unrelated
end

Hanami::Utils.require!("#{__dir__}/unrelated")
```

**Comment by vidmantas** [comment]
@TiteiKo yes that helped! Thanks a lot, seems like an overlook from me while migrating the files into the new format.
