### ISSUE TITLE
Project creation doesn't create a test database

### ISSUE THREAD

**Issue by serradura** [hanami/hanami#683]
Hello everyone, 

It's my first time using hanami! I've been following the [Getting Started guide](http://hanamirb.org/guides/getting-started/) to create my new project, and after I created it using the `--database=postgres` and wrote the [first test](http://hanamirb.org/guides/getting-started/#exploring-app-by-writing-our-first-test). I saw this error after executed `rake test`.

I'm using the 0.9.1 version.

```
~/.rvm/gems/ruby-2.3.2/gems/sequel-4.41.0/lib/sequel/adapters/postgres.rb:244:in `initialize': PG::ConnectionBad: FATAL:  database "notification_server_test" does not exist (Sequel::DatabaseConnectionError)
```

So, I started to search for how to make the database creation, and find [something](https://github.com/hanami/model/pull/200/files#r33655170). But, after using the `createdb` CLI, I tried the following command (I followed my Ruby instinct):

```
RACK_ENV=test bundle exec hanami create db
```

And everything works!

I don't know if it's the expected behavior, buts for my first touch with the tutorial I felt lost. So these are my questions:

1- Do this is a bug?
2- Do this is an opportunity to improve the documentation, adding the following command before say to the user execute the rake test.
`RACK_ENV bundle exec hanami create db`

I hope to help to improve a little this amazing project.

**Comment by jodosha** [comment]
@serradura Hi and thanks for opening this ticket.

No this isn't a bug, it's expected.
We support `RACK_ENV`, but the better way to do that is:

```shell
HANAMI_ENV=test bundle exec hanami db create
```

I understand that this can be confusing, so we should improve the Getting Started guide. Would you like to contribute?

/cc @hanami/issues @hanami/community

**Comment by Bounga** [comment]
Is this improvement to the "Getting Started Guide" still to be done? I'd be glad to help with this since I faced this problem too the first time I used Hanami. I figured the solution quickly as I'm an experienced Ruby developer but I think it can be confusing for new comers.

**Comment by jodosha** [comment]
@Bounga Please create it for the getting started guide and for the CLI database section. Thank you!

**Comment by Bounga** [comment]
@jodosha Here it is https://github.com/hanami/hanami.github.io/pull/282

Hope it will fit Hanami documentation style. Feel free to tell me what you want me to change / reword.

**Comment by jodosha** [comment]
@Bounga Thanks for that PR. Let's move the conversation over there. 😄
