### ISSUE TITLE
Heroku compatibility / incomplete boot via rackup.

### ISSUE THREAD

**Issue by beauby** [hanami/hanami#686]
I just did a deployment on Heroku, and the only issue I encountered was that Heroku by default starts the server via `$ bundle exec rackup config.ru -p $PORT`, which leads to the rather unexplicit `#<RuntimeError: Not loaded>` error upon each request. Hanami expects to be started via `$ bundle exec hanami server -p $PORT`. 

Is there a specific reason why Hanami would need a custom command to be started, rather than the standard rackup sequence?

Regardless, here is a quickfix for running Hanami apps on Heroku:

Simply create a `Procfile` at the root of your repository:
```ruby
web: bundle exec hanami server -p $PORT
```

**Comment by jodosha** [comment]
@beauby Thanks for reporting this. This problem has been fixed by https://github.com/hanami/hanami/pull/679, which should be released in a few days.

I'll keep this open for now.
