### ISSUE TITLE
:environment rake task broken in 0.9.1

### ISSUE THREAD

**Issue by igneus** [hanami/hanami#693]
The `:environment` task, [used as a custom task's prerequisite to load application environment](http://hanamirb.org/guides/projects/rake/), is broken in 0.9.1, as it depends on a non-existent task `:preload`.

**Comment by jodosha** [comment]
@igneus I'm sorry about this problem. We already [fixed it](https://github.com/hanami/hanami/pull/678) and planning to release it soon.

---

In the meantime, do this trick in your `Rakefile`

```ruby
# ...
task :preload do
end
```

In this way, Rake won't complain about it.

**Comment by igneus** [comment]
@jodosha Thanks.
