### ISSUE TITLE
config/environment.rb not requiring initializers nor files in load paths

### ISSUE THREAD

**Issue by beauby** [hanami/hanami#695]
While setting up hanami + sidekiq, I came across two hurdles:
+ requiring `config/environment.rb` does not load initializers (which may or may not be the right thing to do, but since sidekiq does not boot the app, but simply requires that file, it forces one to require the sidekiq config directly from `config/environment`)
+ requiring `config/environment.rb` does not load files in the load paths declared within apps.

@jodosha Any thoughts on this?

**Comment by jodosha** [comment]
@beauby It's by design. Boot process happens when `Hanami.boot` is invoked.

What's your configuration for Sidekiq? Can you please share? Thanks 😄

**Comment by beauby** [comment]
@jodosha I run sidekiq via `bundle exec sidekiq -C ./config/sidekiq.yml -r ./config/environment.rb`. 

The downside of the first point is that one cannot put their sidekiq configuration in an initializer (except if they choose to manually require it from a wrapper that requires `config/environment.rb` as well).

The downside of the second point is that if one stores their application-specific sidekiq workers in `apps/bookshelf/workers/foo_worker.rb`, those have to be explicitly required within a sidekiq wrapper as outlined above.

**Comment by AlfonsoUceda** [comment]
Folks what do you think it would be a good solution?

**Comment by jodosha** [comment]
I think we should generate a new file for that:

```ruby
# config/boot.rb
require_relative './environment'
Hanami.boot
```
