### ISSUE TITLE
file not found error / router bypassed

### ISSUE THREAD

**Issue by kaikuchn** [hanami/hanami#696]
Greetings, let me first state what a joy it has been to work with Hanami so far! Thank you all so much for putting in the time and effort to build something so grand!

Today, however, I've encountered a weird issue that is probably related to #480 #488 and their fixes #493 and #506. I also believe it or rather its solution to be conceptually related to #640.

I'm building an app called `notifications` and I want all of it's dynamic and static content to be scoped under `/notifications`. I therefore tried the following in my `config/routes.rb`:
```ruby
namespace :notifications do
  ...
end

### alternatively
mount Web::Application, at: '/notifications'
```

Either of which works fine until I also prefixed the assets in my `apps/web/application.rb` like this
```ruby
# frozen_string_literal: true
require 'hanami/helpers'
require 'hanami/assets'

module Web
  class Application < Hanami::Application
    configure do
      # ...
      assets do
        # ...
        prefix '/notifications/assets'
      end
      # ...
    end
    # ...
  end
end
```
After the first successful loading of a page the assets were written to the public directory and henceforth the router is bypassed and a file not found error is returned as http response.

I'd expect the existence of a folder in the public directory to not preclude the router's matching. Much less so when the full path cannot be resolved.

To reproduce this:
- run `hanami new filenotfound`
- cd into the new project and run bundle install
- run `echo "get '/hello/goodbye', to: ->(env) { [200, {}, ['Hello from Hanami!']] }" > apps/web/config/routes.rb`
- visit `http://localhost:2300/hello/goodbye` to check it works
- run `mkdir public/hello`
- visit `http://localhost:2300/hello/goodbye` again to now see the error

I'm using hanami 0.9.1. Here's my full [Gemfile.lock](https://gist.github.com/kaikuchn/814301d497218f3de0cf41366e9d7103).

**Comment by kaikuchn** [comment]
Digging into the source code I see that it has changed somewhat since the other issues were resolved.
[Here](https://github.com/hanami/hanami/blob/master/lib/hanami/static.rb#L46) you are explicitly passing in all folders contained in `public/` which -- as stated by the [rack/static docs](https://github.com/rack/rack/blob/master/lib/rack/static.rb#L13) -- results in _all_ requests where the path starts with those folders to be intercepted.

If instead you didn't pass any urls at all, then it seems like rack/static would only serve existing assets from the public folder. What I can say for sure is that my issue is resolved by [this change](https://github.com/kaikuchn/hanami/commit/c74a6539743a1cc27d55dc624d4185684cae1572):
```diff
diff --git a/lib/hanami/static.rb b/lib/hanami/static.rb
index 98bd00e..781b095 100644
--- a/lib/hanami/static.rb
+++ b/lib/hanami/static.rb
@@ -32,31 +32,10 @@ module Hanami
     # @api private
     HEADER_RULES = [[:all, { 'Cache-Control' => "public, max-age=#{MAX_AGE}" }]].freeze
 
-    # @since 0.8.0
-    # @api private
-    EXCLUDED_ENTRIES = %w(. ..).freeze
-
-    # @since 0.8.0
-    # @api private
-    URL_PREFIX = '/'.freeze
-
     # @since 0.6.0
     # @api private
     def initialize(app, root: Hanami.public_directory, header_rules: HEADER_RULES)
-      super(app, urls: _urls(root), root: root, header_rules: header_rules)
-    end
-
-    private
-
-    # @since 0.8.0
-    # @api private
-    def _urls(root)
-      return [] unless root.exist?
-
-      Dir.entries(root).sort.map do |entry|
-        next if EXCLUDED_ENTRIES.include?(entry)
-        "#{URL_PREFIX}#{entry}"
-      end.compact
+      super(app, root: root, header_rules: header_rules)
     end
   end
 end
```

Beyond that I'm unsure if this may break existing behaviour.

**Comment by TiteiKo** [comment]
I've stumbled upon this also, but there's a bigger picture here:

Most likely than not, in production, your webserver (apache/nginx) will be the one serving directly the content of `public/`, entirely bypassing the app server.

If we fix this issue, people will likely forget that in production, their endpoint won't be able to be served, and end up having to figure out why it works in dev and not in production...

That's just my thoughts, and I'd really like the input of @hanami/contributors in that!

**Comment by kaikuchn** [comment]
Yes, I'll not have rack serve my static assets in production. In fact I'm also not doing that in development and it works splendidly.

My problem is that `Rack::Static` is trying to serve my dynamic content when I have nginx proxy to Hanami. And that is because all my urls start with `notifications` which is a folder in `public/` and that folder is passed to `Rack::Static.new`.
So even if it is deemed that delegating to the file server middleware for nonexistent files is not a bug, I'd hope to get a hint how I can solve my problem without monkey patching hanami.

E.g., Is there a way for me to deactivate that middleware throughout all environments? It'd then force my colleagues to also configure nginx to serve assets, but that's okay.

**Comment by mereghost** [comment]
@kaikuchn First thing: you can disable the serving of static assets in development by setting the `SERVE_STATIC_ASSETS` variable on your `.env.development` to false (or by commenting the line).

That being said, I do think that we should support your use case. Would you like to submit a PR for the fix (since you already dug through it)?

**Comment by kaikuchn** [comment]
Thanks for the tipp! @mereghost 

I would love to submit a PR for that. But I'd need to check with you guys what the desired behaviour would be. Here's what I can imagine:

When serving assets via `Rack::Static` then **only existing assets** preclude the router. I.e., given only the asset `public/my_scope/assets/application.css` exists, then a request to `/my_scope/assets/application.css` would be served by `Rack::Static` while a request to `public/my_scope/assets/not-an-asset.css` would be handled by the router (e.g., returning a 404).

Is this acceptable/desirable?

**Comment by jodosha** [comment]
@kaikuchn Hi, I'm sorry about this problem. Thank you for this detailed explanation.

Can you please craft a PR with the patch above? Don't worry about tests and if the build breaks. I can help in the process of creating new tests for this case and try to make to work both.

If that is not possible, we'll keep the compatibility with the existing projects out there.
