### ISSUE TITLE
Failing to populate created_at without updated_at in entity

### ISSUE THREAD

**Issue by rafaels88** [hanami/hanami#697]
When I create an entity with `created_at` and `updated_at` fields, those two fields are populated automatically when it is persisted by its repository. But when I try the same thing without having `updated_at` field, `created_at` field is not populated.

### Example

**migration**

```ruby
Hanami::Model.migration do
  change do
    create_table :countries do
      primary_key :id

      column :name, String, null: false

      column :created_at, Time, null: false
    end
  end
end
```

**Entity**
```ruby
class Country < Hanami::Entity
end
```

**Repository**
```ruby
class CountryRepository < Hanami::Repository
end
```

**Error reproduction**

```ruby
cr = Country.new(name: "Czech Republic")
CountryRepository.new.create cr

Hanami::Model::NotNullConstraintViolationError: PG::NotNullViolation: ERROR:  null value in column "created_at" violates not-null constraint
DETAIL:  Failing row contains (1, Czech Republic, null).
```

**Stack**

ruby 2.3.3
hanami-model (0.7.0)
hanami (0.9.1)

**Comment by kaikuchn** [comment]
That is true and [documented](https://github.com/hanami/model/blob/8775b815edfaef38a1d98cdd83704bbcf2c553f9/README.md#timestamps). [Here](https://github.com/hanami/model/blob/8775b815edfaef38a1d98cdd83704bbcf2c553f9/lib/hanami/model/plugins/timestamps.rb#L27) is why it only works if both are present.

**Comment by rafaels88** [comment]
That's true. My fault for not search this before... thanks!
