### ISSUE TITLE
Rename "controllers" namespace to "actions"

### ISSUE THREAD

**Issue by florish** [hanami/hanami#698]
Being new to Hanami, I've been going through the Getting Started guide. I noticed a pattern in how my `bookshelf` repository is organized:

* Code in `lib/entities` extends `Hanami::Entity`
* Code in `lib/repositories` extends `Hanami::Repository`
* Code in `apps/web/views` extends `Web::View`

Except for one folder:

* Code in `apps/web/controllers` extends `Web::Action` (not `Web::Controller`)

I also noticed some extra attention in the Getting Started guide to explain the terminology around controllers and actions (emphasis mine):

> The terminology of controllers and actions **might be confusing**, so let's clear this up: actions form the basis of our Hanami applications; controllers are mere modules that group several actions together. So while the "controller" is conceptually present in our project, in practice we only deal with actions.

This lead me to thinking: why not rename `controllers` to `actions` in the `apps` context to avoid this confusion?

To be sure, I do appreciate the choice of the term "controller" as being a familiar concept. It is the C in MVC, and for people like me with a background in Ruby on Rails development, using this term might ease the transition to Hanami.

On the other hand, Hanami is already using different terms for the Model layer in MVC: `entities` and `repositories` (not `models`). This did not strike me as odd while working my way through building my first Hanami app. And as for people coming from Rails, it might even be better _not_ to use the term "controller", as Hanami's approach is different with each action being a separate object.

I'm aware that a change like this probably involves quite some renaming throughout the code, and changes to guides and other documentation. Therefore, as much as I'd like to work on this, before changing any code, I'd like to hear from core contributors and other community members what they think.

I opened a new issue, as a search through existing issues did not return anything on this topic. This is my first issue for Hanami. Please let me know if this isn't the right place for this, or if any other information is needed.

**Comment by TiteiKo** [comment]
Hanami isn't loading files based on the name of the class like Rails. If you look at your application.rb file, you'll find the following:
```ruby
load_paths << %w(controllers views)
```

You could very well rename your `controllers/` folder to `actions/`, change the load path in application.rb and voilà! (note that generators would still create the files in `controllers/`)


I've had the same reflexion some time ago, and I agree with you (though @jodosha surely has his reasons on that naming), but I'm afraid this would be a groundbreaking change if we were to change it in the generators and all...

**Comment by cllns** [comment]
Thanks for opening this issue. You explained it very well 💯 

I think this would be a useful and logical change, but it'd require changing a lot of code. I could go either way :)

**Comment by jodosha** [comment]
The reason why we have controllers and not actions is simple: a controller is a Ruby module that includes a cohesive set of actions.

If we name it `Actions`, that would distort the definition above: actions are a set of cohesive actions. Which sounds odd IMO.
