### ISSUE TITLE
`hanami db` commands have no output

### ISSUE THREAD

**Issue by cllns** [hanami/hanami#701]
Running `bundle exec hanami db` with `create`, `prepare`, `drop`, `apply` or `migrate` don't output anything. 
Note: for other `db` commands: `console` doesn't apply, since it does its own thing, and `version` and `help` *do* output, since that's all they do.

It would be nice to have an output so the developer can know that something is actually happening, without having to check their DB manually.
```bash
% bundle exec hanami db prepare
Creating database `db/bookshelf_development.sqlite`...
Migrating database `db/bookshelf_development.sqlite`...
Done!
````
(or with `postgres://localhost/bookshelf_development` for postgres, etc.)

Thoughts?

**Comment by jodosha** [comment]
I agree.

This should be split between `hanami` and `hanami-model`. The latter for printing the output of the migrations.

**Comment by rafaels88** [comment]
@cllns @jodosha @mereghost I would like to try to resolve this issue. Do you folks think it is possible? (I mean, for who never contributed with code to Hanami yet).

**Comment by cllns** [comment]
@rafaels88 yes, go for it :) let me know if you need any help

**Comment by jodosha** [comment]
@rafaels88 My apologize, but I haven't noticed your comment until now. I already implemented it. https://github.com/hanami/model/pull/368

It would be great if you can review it.

/cc @cllns

**Comment by AlfonsoUceda** [comment]
Folks, I'm going to close this issue because now that command is verbose (much verbose) but at least is something.
