### ISSUE TITLE
Code reloading not work when repository file change

### ISSUE THREAD

**Issue by everpointer** [hanami/hanami#702]
When I make changes to repository file, code reloading doesn't work.
I have to manually restart the server to load latest code.

hanami version: 0.9.1
env: development mode

**Comment by cllns** [comment]
Which platform are you on? Does your Gemfile include: 
```
group :development do
  gem 'shotgun'
end
```?

**Comment by rafaels88** [comment]
I am having this problem too. Not only in Repository, but in all `/lib` files.

**Comment by everpointer** [comment]
Sorry for the late response cause I am in different time zones.
Platform: OS X El Capitan 10.11.5
Ruby version: 2.3.0p0

And I did include shotgun on my Gemfile.

**Comment by everpointer** [comment]
And I just upgrade ruby version to 2.3.3, still not work.

**Comment by jodosha** [comment]
During the 0.9 development I had the same problem, that **I think** I resolved with this: https://github.com/hanami/hanami/blob/master/lib/hanami/server.rb#L49

**Comment by jodosha** [comment]
@everpointer @rafaels88 I assume you are starting the server with `bundle exec hanami server`. Is that correct?

**Comment by everpointer** [comment]
@jodosha Yes, I do start server with `bundle exec hanami server`

Restarting server is annoying, So is there any hack way to make this temply work?

**Comment by rafaels88** [comment]
@jodosha yes! And every `/lib` file keeps not reloading at all =/

**Comment by jodosha** [comment]
Hey folks, would you mind to try if #713 works for you? Thanks 😄
