### ISSUE TITLE
Hanami does not configure or load the hanami-mailer as one of its components

### ISSUE THREAD

**Issue by mereghost** [hanami/hanami#703]
It seems since we released the 0.9 series, using a component model for loading dependencies that `hanami-mailer` stayed out of the load scheme.

It can be seem by creating a new app, generating a mailer and trying to deliver it. By default it should use `Mail::TestMailer` but it tries to use the `smtp` delivery method.

**Comment by mereghost** [comment]
A more detailed step by step to reproduce:

```
hanami version #=> 0.9.2

hanami new mailer_fail
bundle exec hanami g mailer HelloBug
bundle exec hanami console
```
That should give us all we need to reproduce the bug.

```
hanami> Hanami::Mailer.configuration
#=> #<Hanami::Mailer::Configuration:0x0000000304ca88 @namespace=Mailers, @root=#<Pathname:/tmp/mailer_fail>, @delivery_method=[:smtp, {}], @default_charset="UTF-8", @mailers=#<Set: {Mailers::HelloBug}>, @modules=[]>

hanami> Mailers::HelloBug.deliver
# => NoMethodError: undefined method `fetch' for nil:NilClass
        from /home/mereghost/.rvm/gems/ruby-2.4.0/gems/hanami-mailer-0.4.0/lib/hanami/mailer/dsl.rb:84:in `templates'
        from /home/mereghost/.rvm/gems/ruby-2.4.0/gems/hanami-mailer-0.4.0/lib/hanami/mailer.rb:324:in `__part?'
```
That error `NoMethodError` happens because the `Hanami::Mailer.load!` was never called at all. The `Mailer#templates` are never set and neither are mailer config block on a hanami application (evidenced by it defaulting to the `smtp` delivery method, when it should be `test`).

**Comment by iAmDaiveR** [comment]
Problems lives in **hanami/mailer**

I think that the code below (hanami/mailer) expects that the template directive (defined in Mailer's DSL) was already invoked by a concrete Mailer class implementation, which populates the @templates variable by your templates. And this expectation breaks the mail build process when the .template DSL method was not invoked:

The problem lives here:

https://github.com/hanami/mailer/blob/master/lib/hanami/mailer/dsl.rb#L80

```
def templates(format = nil) ## PROBLEM
  if format.nil?
    @templates = ::Hanami::Mailer::Rendering::TemplatesFinder.new(self).find
  else
    @templates.fetch(format, nil)
  end
end
```

And caused here:
Start: https://github.com/hanami/mailer/blob/master/lib/hanami/mailer.rb#L280
Continue: https://github.com/hanami/mailer/blob/master/lib/hanami/mailer.rb#L322

start:

```
def build
  Mail.new.tap do |m|
    ....
    ### PROBLEM
    m.html_part = __part(:html)
    m.text_part = __part(:txt)
    #### PROBLEM
    .....
    m.delivery_method(*Hanami::Mailer.configuration.delivery_method)
  end
end
```

continue:

```
## format is nil => good luck
def __part?(format)
  @format == format ||
    (!@format && !self.class.templates(format).nil?)
end
```

Steps:
1) `@format` is nil
2) `.templates` was not invoked (@templates == nil)
3) `__part?(:txt/:html)` invocation
4) `@format == format || (!@format && !self.class.templates(format).nil?) `
transforms to (:txt for example):
`nil == :txt || (!nil && !self.class.templates(:txt).nil?)`

where `self.class.templates` fails on `@templates.fetch` (`@templates` was not prepopulated => `@templates == nil`)

BUT May be I'm wrong.

**Comment by iAmDaiveR** [comment]
@mereghost Ah :) You already resolved this problem in your PR :)

**Comment by AlfonsoUceda** [comment]
@iAmDaiveR thanks for that but there is a PR fixing this problem https://github.com/hanami/hanami/pull/705 check to see the fix.
