### ISSUE TITLE
Form helper should probably escape values read from entities

### ISSUE THREAD

**Issue by kwando** [hanami/hanami#709]
I'm creating an edit form for an entity and I'm using the Hanami form helper. When it reads values from my entity it does __not__ htmlescape the value for the ```value``` attribute. This is breaking my form if a entity contains a quote (```"```) for instance.

I expecting the value to be escaped for me when using the form helper.

Hanami 9.2

Edit: apparently the form helper does no escaping of value attributes at all, not even when read from the params hash.. which I'll consider a security concern.

**Comment by jodosha** [comment]
@kwando Thanks for reporting this. We'll have a look.

**Comment by davydovanton** [comment]
hello, @kwando I reproduced this bug.
![screenshot 2017-01-13 01 25 10](https://cloud.githubusercontent.com/assets/1147484/21910914/36590ed0-d92f-11e6-92dc-09ca1ccf8dc8.jpeg)

Thanks for the report. I'll fix this :)

**Comment by davydovanton** [comment]
okay, I created PR, @jodosha and @hanami/core, please take a look on it 🌟

**Comment by davydovanton** [comment]
@kwando hey, I created fix, could you try it? (you need to install hanami-helpers from master branch for this)
