### ISSUE TITLE
hanami-head app failed to bundle install

### ISSUE THREAD

**Issue by joneslee85** [hanami/hanami#710]
Step to reproduce:
```
$ ruby -v # => 2.3.3
$ hanami -v  # => 0.9.2 (I could reproduce with HEAD too)
$ bundle -v # => 1.13.7

$ hanami new fancy_app --hanami-head=true
$ cd fancy_app && bundle install

Resolving dependencies....
Your bundle requires gems that depend on each other, creating an infinite loop. Please remove either gem 'rack' or
gem 'thin' and try again.
```

**Comment by dikond** [comment]
I've met the same problem when cloned `hanami-controller` and tried `bundle install`.

When I comment-out `gem 'hanami-router'` in `Gemfile` it doesn't complain. I've also cloned `hanami-router` and bundle install'ed it, and there were no issues. It is weird.

**Comment by davydovanton** [comment]
hey, I think it's a problem rack2 update for hanami-controllers. I'll look on this today 👍

**Comment by davydovanton** [comment]
@dikond could you delete rack dependency from hanami controller gemspec file and try to bundle it?

**Comment by dikond** [comment]
@davydovanton hey, just checked - it works.

**Comment by davydovanton** [comment]
@dikond without rack dependency, yep? :)

**Comment by dikond** [comment]
yeah :)

**Comment by AlfonsoUceda** [comment]
folks, it doesn't happen to me :S are you experiencing this problem yet?

**Comment by davydovanton** [comment]
@AlfonsoUceda I don't have this issue too but I think problem in rack 2 update 🤔

**Comment by AlfonsoUceda** [comment]
@joneslee85 have you experienced again this issue?

**Comment by joneslee85** [comment]
@AlfonsoUceda I still experience it

**Comment by mereghost** [comment]
I tried on a fresh system and could not reproduce it at all. Could your bundler be using a cached version of the gems with the messed dependencies?

**Comment by davydovanton** [comment]
agree with @mereghost. Maybe is rvm/rbenv issue?

**Comment by joneslee85** [comment]
It could be, for now I just close it. will report if it happens again
