### ISSUE TITLE
Hanami rewrite env variables from .env file

### ISSUE THREAD

**Issue by davydovanton** [hanami/hanami#712]
## The problem
When you have  EVN variable in `.env.*` file and try to set this variable from the shell you will have the variable value from the file.

## Reproduce
1. Create new hanami app
2. Add any variable to `.env.development` file (`echo "TEST_VALUE=" >> .env.development`)
3. Run console with new variable value  (`TEST_VALUE="TEST HERE" bundle exec hanami c`)
4. Call `ENV['TEST_VALUE']` in console (now it returns empty sting)

/cc @hanami/core

**Comment by gizotti** [comment]
@davydovanton I am halfway through this one. I just want to double check if the ENV var set on the shell has priority on any command that is being called, and not just `hanami c`.

**Comment by davydovanton** [comment]
@gizotti awesome work. Thank you 👍

**Comment by gizotti** [comment]
@davydovanton happy to help :)
