### ISSUE TITLE
hanami on Windows x64 - creating new project throws error: thor-0.19.4 actions.rb line 254

### ISSUE THREAD

**Issue by harbirg** [hanami/hanami#726]
Unable to run hanami on windows 10 using ruby 2.3.0 installed via https://rubyinstaller.org/ along with DevKit for native gems. 

When creating new project, thor gem gives an error. Has anyone else tried to use hanami on windows? I was able to get Sinatra working, but I really wanted to use Hanami. Can someone point me to what I should change to resolve the issue. 

D:\dev>hanami new bookshelf
      create  .hanamirc
      create  .env.development
      create  .env.test
      create  Gemfile
      create  config.ru
      create  config/environment.rb
      create  lib/bookshelf.rb
      create  public/.gitkeep
      create  config/initializers/.gitkeep
      create  lib/bookshelf/entities/.gitkeep
      create  lib/bookshelf/repositories/.gitkeep
      create  lib/bookshelf/mailers/.gitkeep
      create  lib/bookshelf/mailers/templates/.gitkeep
      create  spec/bookshelf/entities/.gitkeep
      create  spec/bookshelf/repositories/.gitkeep
      create  spec/bookshelf/mailers/.gitkeep
      create  spec/support/.gitkeep
      create  db/migrations/.gitkeep
      create  Rakefile
      create  spec/spec_helper.rb
      create  spec/features_helper.rb
      create  db/schema.sql
      create  .gitignore
         run  git init . from "."
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/actions.rb:254:in ``': No such file or directory - git init . (Errno::ENOENT)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/actions.rb:254:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/commands/new/abstract.rb:90:in `init_git'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/commands/new/container.rb:34:in `post_process_templates'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/generators/generatable.rb:31:in `process_templates'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/generators/generatable.rb:9:in `start'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/commands/new/abstract.rb:43:in `block in start'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/commands/new/abstract.rb:40:in `chdir'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/commands/new/abstract.rb:40:in `start'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/cli.rb:116:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/bin/hanami:5:in `<top (required)>'
        from C:/Ruby23-x64/bin/hanami:22:in `load'
        from C:/Ruby23-x64/bin/hanami:22:in `<main>'

D:\dev>hanami -v
v0.9.2

D:\dev>gem install hanami
Successfully installed hanami-0.9.2
Parsing documentation for hanami-0.9.2
Done installing documentation for hanami after 1 seconds
1 gem installed

**Comment by cllns** [comment]
Sorry you're having trouble! The trouble here is that you don't have `git`. We shouldn't require it, and [we're working on fixing that](https://github.com/hanami/hanami/pull/665).

Can you try installing git? https://git-scm.com/download/win

**Comment by harbirg** [comment]
Thanks for the quick turnaround. I installed git and I get further along as "hanami new bookshelf" command completes. But, as soon as i run "bundle exec hanami server" and access the website, the webserver crashes. I tried switching over to PUMA to see if it makes a difference but the result is the same. 

Does this log give you any clues as to why its crashing:

**WEBrick crash log**

D:\dev\bookshelf>bundle exec hanami server
[2017-02-06 15:20:09] INFO  WEBrick 1.3.1
[2017-02-06 15:20:09] INFO  ruby 2.3.3 (2016-11-21) [x64-mingw32]
[2017-02-06 15:20:09] INFO  WEBrick::HTTPServer#start: pid=3420 port=2300
[2017-02-06 15:20:43] ERROR NotImplementedError: fork() function is unimplemented on this machine
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:27:in `fork'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:27:in `call!'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:18:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/assets/static.rb:49:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/lint.rb:49:in `_call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/lint.rb:37:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/showexceptions.rb:24:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/commonlogger.rb:33:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/content_length.rb:15:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/handler/webrick.rb:88:in `service'
        C:/Ruby23-x64/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
        C:/Ruby23-x64/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
        C:/Ruby23-x64/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
[2017-02-06 15:20:43] ERROR NotImplementedError: fork() function is unimplemented on this machine
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:27:in `fork'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:27:in `call!'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:18:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/assets/static.rb:49:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/lint.rb:49:in `_call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/lint.rb:37:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/showexceptions.rb:24:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/commonlogger.rb:33:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/content_length.rb:15:in `call'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/handler/webrick.rb:88:in `service'
        C:/Ruby23-x64/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
        C:/Ruby23-x64/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
        C:/Ruby23-x64/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'

**PUMA crash log after adding puma to Gemfile**

D:\dev\bookshelf>bundle exec hanami server
*** SIGUSR2 not implemented, signal based restart unavailable!
*** SIGUSR1 not implemented, signal based restart unavailable!
*** SIGHUP not implemented, signal based logs reopening unavailable!
Puma starting in single mode...
* Version 3.7.0 (ruby 2.3.3-p222), codename: Snowy Sagebrush
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:2300
Use Ctrl-C to stop
2017-02-06 15:23:48 -0800: Rack app error handling request { GET / }
#<NotImplementedError: fork() function is unimplemented on this machine>
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:27:in `fork'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:27:in `call!'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:18:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/assets/static.rb:49:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/lint.rb:49:in `_call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/lint.rb:37:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/showexceptions.rb:24:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/commonlogger.rb:33:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/content_length.rb:15:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puma-3.7.0/lib/puma/configuration.rb:226:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puma-3.7.0/lib/puma/server.rb:578:in `handle_request'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puma-3.7.0/lib/puma/server.rb:415:in `process_client'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puma-3.7.0/lib/puma/server.rb:275:in `block in run'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puma-3.7.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
2017-02-06 15:23:48 -0800: Rack app error handling request { GET /favicon.ico }
#<NotImplementedError: fork() function is unimplemented on this machine>
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:27:in `fork'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:27:in `call!'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:18:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/assets/static.rb:49:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/lint.rb:49:in `_call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/lint.rb:37:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/showexceptions.rb:24:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/commonlogger.rb:33:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/content_length.rb:15:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puma-3.7.0/lib/puma/configuration.rb:226:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puma-3.7.0/lib/puma/server.rb:578:in `handle_request'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puma-3.7.0/lib/puma/server.rb:415:in `process_client'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puma-3.7.0/lib/puma/server.rb:275:in `block in run'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puma-3.7.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

**Comment by cllns** [comment]
Looks like same issue as: http://stackoverflow.com/questions/1844188/shotgun-gem-explodes-when-starting-a-sinatra-app-on-windows

`shotgun` is a soft-dependency of Hanami, so you can remove it from your `Gemfile`. Instead, try `restart` for code-reloading? https://github.com/vais/restart (so you'd run `restart hanami server` each time)

**Comment by harbirg** [comment]
Cheers! Thanks for your help. It works after removing shotgun. I will look into shotgun gem and if I need it for my development. 

Closing this issue, notes for other users attempting to run Hanami on windows:
1. Make sure Git is installed
2. remove 'shotgun' GEM

**Comment by cllns** [comment]
awesome! the git dependency should be gone soon
