### ISSUE TITLE
It will be nice to comment that 'unsafe-eval' needed for vue.js in application.rb

### ISSUE THREAD

**Issue by mytram** [hanami/hanami#729]
Hi, 

I was trying to use vue.js with hanami. I basically copied over built js files for hanami to serve them. However, at the beginning, it appeared as if the vuejs scripts stopped half way mysteriously whilst the same approach would work with rails 5. After some digging, I found that rails didn't have the content-security-policy header by default compared with hanami. 

I found out that 'unsafe-eval' was needed for vuejs to do its work. I will be nice to add some comments in the apps/web/application.rb below: 

```  
 # Inline JavaScript is NOT allowed. To enable it, please use:
 # "script-src 'unsafe-inline'".

```
For instance, 

```
# For some javascript frameworks, such as vuejs, 'unsafe-eval' needs to be enabled for eval(), function() to work. 
# Here are the details: 
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src
```

Just a suggestion that may save other people's time. 

Many thanks, 

Mytram.

**Comment by davydovanton** [comment]
@mytram hey, could you update issue? :)

**Comment by mytram** [comment]
@davydovanton Hi, I was just adding. accidentally hit some key before I finished :) Thanks

**Comment by davydovanton** [comment]
@mytram good proposal. I [added](https://github.com/ossboard-org/ossboard/blob/master/apps/web/application.rb#L234) this policy too (and spend some time for this) 👍

Could you create PR with updated comments? 😊

**Comment by mytram** [comment]
@davydovanton , no problems. Will do. Thanks

**Comment by jodosha** [comment]
@mytram I discovered that this is already documented. Please see https://github.com/hanami/hanami/pull/731#issuecomment-283114410

**Comment by cllns** [comment]
@jodosha This and #731 should not have been closed. There's [a difference between `unsafe-inline` and `unsafe-eval`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src). `unsafe-inline` allows inline scripts, but not **not** `eval` (and similar) functions. `unsafe-eval` allows inline function to use `eval` and similar.

[Vue.js uses `new Function()`](https://vuejs.org/v2/guide/installation.html#CSP-environments), which is a `eval`-type function.

**Comment by jodosha** [comment]
@cllns @mytram Okay. Can we replace these [two lines](https://github.com/hanami/hanami/blob/master/lib/hanami/generators/app/application.rb.tt#L205-L206) with something similar to this?

```ruby
# Content Security Policy can block the execution of your JavaScript code, including your framework.
# See http://hanamirb.org/guides/security/content-security-policy
```

The idea is to have just to lines to link to a more detailed guide that we can expand from time to time with informations about the several frameworks.

**Please note that this page doesn't exist yet in our website.**

**Comment by mytram** [comment]
@jodosha, I am good with your change. It seems that googling "hanami vuejs" returns this issue on the top. I think my original purpose, hoping to save others' time, is already fulfilled :-). Also  I picked up setting up hanami+vuejs again and I may write an article on that. That will probably be more helpful to people with similar interest. 

Thanks a lot

**Comment by iJackUA** [comment]
For anyone searching solution to connect Vue.js HMR and Hanami
these configs fixed all issues with inline JS + CSS and hot reload via WS 
my **webpack-dev-server uses port 3500** (change it according to your settings)

```ruby
# /apps/web/application.rb

security.content_security_policy %{
...
        script-src 'self' 'unsafe-eval' http://localhost:3500;
        connect-src 'self' ws://localhost:3500 http://localhost:3500;
...
      }
```
