### ISSUE TITLE
Generate project in folder

### ISSUE THREAD

**Issue by cllns** [hanami/hanami#736]
Right now, a hanami project is created in a new folder named based on the project. This is good for the vast majority of cases, but I think the command should be more flexible, to optionally allow other locations.

For example:
```
hanami new test_app test_app2
```
would create a `test_app` project in a new `test_app2` folder, that folder doesn't already exist. (This is the real usage I tried and it didn't work)

&

```
hanami new test_app .
```
would create a `test_app` project in the current folder, assuming the folder is empty.

&

```
mkdir test_app2 
touch test_app2/hello
hanami new test_app test_app2
# PROMPT: The folder 'test_app2' already has file(s) in it, are you sure you want to create a new hanami project in test_app2? Y/N?
```

I think the prompting is important, since we don't want to add a bunch of files to a folder based on a user's typo. A simpler solution could be to skip the prompt and only allow hanami projects to be created in folders that are empty.

Here's what the USAGE would look like, when running `hanami new --help`
```
Usage:
  hanami new PROJECT_NAME [PATH]
```

Note: this is proposed for `v1.1`, not `v1.0`.

Do people think this would be a useful feature, to improve developer experience?

**Comment by davydovanton** [comment]
I think it will be useful for me and other developers 👍 
Because sometimes I need to create project with one name and other dir name.

**Comment by AlfonsoUceda** [comment]
thanks @cllns I think it makes sense but after 1.0 we will rewrite CLI interface removing Thor and making it more flexible.

**Comment by jodosha** [comment]
Lemme play the _grumpy cat_ ™️ here: do we need this? Can this be solved by manual intervention from a developer?

Creating a project in the current directory is it so common? It was introduced to add a deliverability mechanism for a current Ruby project. Aka add some web wrapper around your Ruby library. Which I don't know how much is it common.

</grumpy-cat>

---

We can add this change, if it won't complicate too much the implementation of the rewritten CLI.

**Comment by mereghost** [comment]
I'm with @jodosha here. How often do you need this functionality? Why? Is this the common use case? Is there an easy way to circumvent the need for more code? 

What would we do if $PWD already has a directory of the same name? And git repo?

While it might help some cases, I don't think that it's *that common* to warrant the extra maintenance burden and having to deal with these edge cases.

**Comment by jodosha** [comment]
@cllns WDYT?

**Comment by cllns** [comment]
I don't think it's a very common workflow. But, more importantly, I think this functionality is what developers will expect from a command line utility. 

I agree it's not worth adding a lot of code to support this minor use-case. 
I think it'll be just a few extra lines of code, in [`lib/hanami/commands/new/abstract.rb`](https://github.com/hanami/hanami/blob/master/lib/hanami/commands/new/abstract.rb#L39) plus specs :)

**Comment by TiteiKo** [comment]
I think it's already implemented, isn't it ? https://github.com/hanami/hanami/blob/master/lib/hanami/commands/new/abstract.rb#L110

**Comment by jodosha** [comment]
@TiteiKo At this point, I'm not sure if it's still working or not. 😄

**Comment by jodosha** [comment]
Folks, the question is: do we want this feature or not?

If yes:

If it's already implemented we should add tests for it, so during the CLI rewrite it won't get lost.
If it isn't already implemented, we should make it happen.

If not:

We should remove dead code.

@hanami/core what's your opinion?

**Comment by AlfonsoUceda** [comment]
It can be added with the rewrite of CLI, so let makes this happen.

**Comment by mereghost** [comment]
I have a radical opinion on how we could tackle this: we could wait and see if the userbase requests this feature. 

And from what I understood from @davydovanton example he would need something more along this line (please correct me if I'm wrong):  `hanami new awesomesauce --dirname not-so-awesome`, which to be honest, seems to make sense.

**Comment by jodosha** [comment]
My opinion is:

```shell
hanami new bookshelf
mv bookshelf bookshelf-directory
```

Am I missing something?

I'd like to hear one last honest opinion from @cllns and @davydovanton.

If you think this can be really useful for devs or if the lack of this feature will block them, please tell us. If my opinion reduces the problem to something too simple, and we need this feature, just speak up and it will make to happen.

Thank you all! 🌸

**Comment by cllns** [comment]
It won't block people, but I think it's useful. It should be simple to implement. I think it's what people would expect, from other CLI utilities, like: `git clone git://... dir_name`

Your workflow works well (and it's simple enough), but it won't work if there is already a `bookshelf` folder that has files in it that you want to keep.

**Comment by jodosha** [comment]
Closing as stale. @cllns feel free to reopen if you want to sponsor this feature.
