### ISSUE TITLE
Custom logger

### ISSUE THREAD

**Issue by spectator** [hanami/hanami#738]
Hi,

What do you think on providing some sort of extension points for Hanami logger or ability to set your own logger?

For example, it is common need to include request id in your logs and Hanami default logger doesn't include that.

```
[app] [INFO] [2017-02-27 16:53:22 -0800] e52a809f-4ed7-4e1a-81df-f739bf9cd713 HTTP/1.1 POST 200 127.0.0.1 /graphql  63 0.017878
```

`e52a809f-4ed7-4e1a-81df-f739bf9cd713` is request id.

For now I had to override `CommonLogger#log` in order to add that.

```ruby
  HTTP_X_REQUEST_ID = 'HTTP_X_REQUEST_ID'.freeze

  def log(env, status, header, began_at)
    now    = Time.now
    length = extract_content_length(header)

    msg = Hash[
      uuid:    env[HTTP_X_REQUEST_ID],
      http:    env[HTTP_VERSION],
      verb:    env[REQUEST_METHOD],
      status:  status.to_s[0..3],
      ip:      env[HTTP_X_FORWARDED_FOR] || env[REMOTE_ADDR],
      path:    env[SCRIPT_NAME] + env[PATH_INFO],
      query:   env[QUERY_STRING],
      length:  length,
      elapsed: now - began_at
    ]

    logger = @logger || env[RACK_ERRORS]
    # Standard library logger doesn't support write but it supports << which actually
    # calls to write on the log device without formatting
    if logger.respond_to?(:write)
      logger.write(msg)
    else
      logger.info(msg)
    end
  end
```

**Comment by jodosha** [comment]
@spectator Hi this completely makes sense. This supposed to be part of `v1.0.0.beta1`, but for some reason I skipped this extension.

**Comment by gizotti** [comment]
@jodosha I am already working on #756, so I would be more than happy to keep working on the logger and implement these extensions if nobody is working on this yet.

**Comment by jodosha** [comment]
@gizotti We have #768, but thank you anyway 👍

**Comment by TiteiKo** [comment]
Close by #768
