### ISSUE TITLE
Don't mount Hanami::CommonLogger if Hanami.logger is nil

### ISSUE THREAD

**Issue by jodosha** [hanami/hanami#744]

**Comment by sandelius** [comment]
@jodosha I've fix this but have no idea where to put my tests :)

**Comment by jodosha** [comment]
@sandelius Please go ahead with the fix, I'll take care of the tests. Are you able to provide a PR in the next couple of days? We want to ship beta3 soon. Thank you.

**Comment by sandelius** [comment]
@jodosha I can do it later today but I would really love to add a test as well. Would a unit or integration be the better option?

I'm trying to "learn" how you guys write, and place, your tests so I can contribute more.

**Comment by jodosha** [comment]
@sandelius I asked to provide only the fix implementation, but not the tests because I recognised we didn't had an integration test for `hanami server` logging.

With https://github.com/hanami/hanami/commit/3b435ae1c65afa2aaa3fcbec9c0bfee98b7b6cf4 I added an integration testing for logging. Please use it as a starting point for testing your fix.
