### ISSUE TITLE
Wrong CI status

### ISSUE THREAD

**Issue by davydovanton** [hanami/hanami#750]
We have errored tests (like this https://travis-ci.org/hanami/hanami/jobs/210778507#L1273), but travis shows that build was passed. I think it's a bug. WDYT?

**Comment by b264** [comment]
This is the build running on `jruby-head` and `jruby-9.1.6.0` which both allow failures in the build.  It's an FYI only in case official support for these languages is added, these are likely things that will need addressing.  Its source is https://github.com/hanami/hanami/blob/506a35e5262939eb4dce9195ade3268e19928d00/.travis.yml#L22-L23

**Comment by davydovanton** [comment]
okay. Please open this build: https://travis-ci.org/hanami/hanami/builds/210778505
after that open this (2.3.3 ruby) job: https://travis-ci.org/hanami/hanami/jobs/210778506
and you'll see that it's not a jruby problem

**Comment by mereghost** [comment]
Closing as it's not relevant anymore.
