### ISSUE TITLE
First mailer config rejects any further mods

### ISSUE THREAD

**Issue by ixti** [hanami/hanami#757]
Let's start with [initial](https://github.com/hanami/hanami/blob/master/lib/hanami/generators/application/container/config/environment.rb.tt) (leaving relevant parts only) configuration hanami generates for us:

``` ruby
Hanami.configure do
  mailer do
    root 'lib/example/mailers'
    delivery :test
  end

  environment :production do
    mailer do
      delivery :smtp, address: ENV['SMTP_HOST'], port: ENV['SMTP_PORT']
    end
  end
end
```

In this configuration, `mailer` block inside of `environment :production` will be silently ignored. And as result `delivery :test` will be applied to all environments. The reason is that once `mailer` block is called, all further calls will be silently ignored due to `put_if_absent` [under the hood](https://github.com/hanami/hanami/blob/master/lib/hanami/configuration.rb#L94-L96).

The only way to make mailer work right now is to ensure that you call it in environment specific block first:

``` ruby
Hanami.configure do
  environment :production do
    mailer do
      root 'lib/example/mailers'
      delivery :smtp, address: ENV['SMTP_HOST'], port: ENV['SMTP_PORT']
    end
  end

  mailer do
    root 'lib/example/mailers'
    delivery :test
  end
end
```

Notice that `root` needs to be duplicated, as only one of those blocks will be called in fact, so each of them needs to contains full configuration.

**Comment by jodosha** [comment]
@ixti Thanks for reporting this. I'm gonna write a patch for it.

**Comment by ixti** [comment]
Awesome! Thanks!
