### ISSUE TITLE
Error: hanami new admin --architecture=app

### ISSUE THREAD

**Issue by ZhangHanDong** [hanami/hanami#764]
```
$ hanami new admin --architecture=app

/home/vagrant/.rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/hanami-1.0.0/lib/hanami/commands/new/app.rb:111:

in `realpath': No such file or directory @ realpath_rec - 

/home/vagrant/.rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/hanami-1.0.0/lib/hanami/generators/application/app (Errno::ENOENT)
```

**Comment by cllns** [comment]
Hi @ZhangHanDong. Thanks for checking out Hanami! Sorry you ran into this issue. We actually don't support the `app` architecture anymore, just the `container` architecture.

We have an open pull request to fix this, so you wouldn't see this option: https://github.com/hanami/hanami/pull/737

Going to close this but thanks for reporting! 🌸

**Comment by ZhangHanDong** [comment]
@cllns how to generate another_web in apps ?

**Comment by cllns** [comment]
@ZhangHanDong `hanami generate app admin` (sorry, I notice that's what you were trying to do. now I see it)

It's confusing, but the `app` architecture was just a single app as a Hanami project. We still have apps, they're just within the project (what we called `container`)

**Comment by ZhangHanDong** [comment]
@cllns I see.  Thanks for your reply.
