### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by thelastinuit** [hanami/hanami#765]
Hey guys, 

Awesome work!

This is sort of bias but here you have our two possible cents.

We usually develop with docker at The Clowder. So we already love your project and we dockerized it like right now. 

Here's a link for those who might or might not like the idea of developing with docker:
[Docker!](https://github.com/TheClowder/docker-hanami)

If this is not your thing, just close it! 

Many thanks for you hard work,
Myself.

**Comment by joneslee85** [comment]
@thelastinuit can you please share it on https://discourse.hanamirb.org/ instead? The GH issues are not meant for general information sharing purpose. Thanks for writing in.

**Comment by cllns** [comment]
@thelastinuit thanks for implementing and sharing this!

I think this would be **great** on http://awesome-hanami.org/

If you open a PR in this repo https://github.com/davydovanton/awesome-hanami it should get merged :D

**Comment by thelastinuit** [comment]
oh great! Thanks!

**Comment by davydovanton** [comment]
@thelastinuit Yep, absolutely agree with @cllns. Good job 👍
