### ISSUE TITLE
Example on website won't work if not using Ruby 2.3.1 locally

### ISSUE THREAD

**Issue by welkie** [hanami/hanami#766]
Hello,

I was curious to try Hanami out now that it's at its 1.0.0 release (great work, devs :+1: ), so I followed the steps on the home page where it has the three sections for "Download", "Develop", and "Deploy". Unfortunately, since I wasn't using Ruby 2.3.1 locally (I use RVM and I'm on 2.4.1 right now), I wasn't able to run the ```bundle``` command locally and therefore a Gemfile.lock file wasn't generated. This caused Heroku to fail to compile.

Changing the line echoed into the Gemfile from:

```ruby
ruby '2.3.1'
```

to:

```ruby
ruby '2.4.1'
```

solves this.

I end up having it run no problem by stringing the commands together as:

```bash
hanami new bookshelf --database=postgresql \
  ; cd bookshelf && echo "ruby '2.4.1'" >> Gemfile && bundle \
  ; git add . && git commit -m "Initial commit" \
  ; heroku apps:create \
  ; heroku config:add SERVE_STATIC_ASSETS=true \
  ; git push heroku master \
  ; heroku run bundle exec hanami db migrate \
  ; heroku open
```

Anybody running those commands locally as they follow along with the instructions on the home page needs to make sure they're echoing their local version of Ruby into the Gemfile before running ```bundle```, or maybe just not bother at all with that step, letting Heroku compile it as they will. Perhaps that should be documented?

**Comment by joneslee85** [comment]
@welkie `bundler` was not shipped by default in any Ruby installation, I speculate that you forget install `bundler`.

I think it is a good idea to update the doc to include `gem install bundler` step

**Comment by cllns** [comment]
@joneslee85 [I tried that](https://github.com/hanami/hanami.github.io/pull/221) but @jodosha notified me that `bundler` is a dependency of `hanami` (as it should be), so that shouldn't be the issue.

I think the only issue here is that @welkie had `2.4.1` installed but not `2.3.1`? And therefore installed `hanami` for `2.4.1` but not `2.3.1` (which bundler wants to use).

Ideally we shouldn't specify the ruby version, and just use whatever supported version they have, to avoid this issue (and provide the best user experience 😄) 

[Heroku says](https://devcenter.heroku.com/articles/ruby-versions):
```
The default Ruby for new apps, will be one minor version behind the most recent one. For instance, when Ruby 2.4.0 comes out, Ruby 2.3.x will become the default.
```

So maybe we can get rid of that line entirely? Heroku will throw a warning but I think that's OK, since people can specify their own version at that point?

Another option is to use `ruby -e 'puts RUBY_VERSION'` instead of hard-coding a version, but that will likely cause confusion for someone using, say, `2.0.0`, since the Gemfile will be invalid. (because `hanami` _currently_ requires `2.3+`)

**Comment by welkie** [comment]
I had bundler installed. When I ran ```bundle``` it said something along the lines of "the gemfile says 2.3.1 but your Ruby version is 2.4.1.

**Comment by cllns** [comment]
Thanks! Then yes, I think it's true that "the only issue here is that @welkie had 2.4.1 installed but not 2.3.1".

@welkie Can you try the instructions again, without specifying the ruby version at all? It should work, although you'll see a Heroku warning telling you to specify the ruby version.


Came up with a couple more robust ways of getting the version number, though I think they're too complicated for this.
```
ruby -e 'puts ["2.3", "2.4"].include?("2.3") ? RUBY_VERSION : raise("Install Ruby 2.3 or 2.4")'
```
or
```
ruby -e 'puts Gem::Version.new(RUBY_VERSION) > Gem::Version.new("2.3") ? RUBY_VERSION : raise("Install Ruby 2.3+")'
```

If not-specifying the ruby version at all works, that's the best option, in my opinion.

**Comment by welkie** [comment]
Unfortunately omitting it doesn't work. :( I tried it without the echoing Ruby version to Gemfile step and I got:

```
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/Rack
remote: -----> Using Ruby version: ruby-2.2.6
remote: -----> Installing dependencies using bundler 1.13.7
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        Warning: the running version of Bundler (1.13.7) is older than the version that created the lockfile (1.14.6). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
remote:        Fetching gem metadata from https://rubygems.org/........
remote:        Fetching version metadata from https://rubygems.org/..
remote:        Fetching dependency metadata from https://rubygems.org/.
remote:        hanami-utils-1.0.0 requires ruby version >= 2.3.0, which is incompatible with
remote:        the current version, ruby 2.2.6p396
remote:        Bundler Output: Warning: the running version of Bundler (1.13.7) is older than the version that created the lockfile (1.14.6). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
remote:        Fetching gem metadata from https://rubygems.org/........
remote:        Fetching version metadata from https://rubygems.org/..
remote:        Fetching dependency metadata from https://rubygems.org/.
remote:        hanami-utils-1.0.0 requires ruby version >= 2.3.0, which is incompatible with
remote:        the current version, ruby 2.2.6p396
remote:  !
remote:  !     Failed to install gems via Bundler.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to 
```

**Comment by cllns** [comment]
Damn! Thanks for checking

Looks like Heroku's docs are wrong then, if they're using `2.2` and not `2.3` (since `2.4` is out) 😕

**Comment by welkie** [comment]
I got it working. :)

It works when you run bundle and **then** add the ruby version to the Gemfile. You get to specify higher than the Heroku default Ruby so that Hanami works, and the Gemfile.lock is present so Heroku's build process knows what to do:

```bash
hanami new bookshelf --database=postgresql \
  ; cd bookshelf && bundle && echo "ruby '2.4.1'" >> Gemfile \
  ; git add . && git commit -m "Initial commit" \
  ; heroku apps:create \
  ; heroku config:add SERVE_STATIC_ASSETS=true \
  ; git push heroku master \
  ; heroku run bundle exec hanami db migrate \
  ; heroku open
```

**Comment by jodosha** [comment]
@welkie Hi, I'm happy that you made it working. Thank you all. 👍
