### ISSUE TITLE
Upgrading from 0.9.2 to 1.0, `mailers` folder required

### ISSUE THREAD

**Issue by kaikuchn** [hanami/hanami#767]
Hey folks,

I've just updated my app from 0.9.2 to 1.0 and it was a breeze! :heart:
There was only one slight hiccup, I did not have a `mailers` folder even though my `config/environment.rb` file includes sections for mailers. This was not a problem in 0.9.2 but the app would crash now when one has mailers configured but no `mailers` folder in `lib/[YOUR_APP]/`.

I realise it is rather weird to have mailers configured and no `mailers` folder. In case it was an intentional change to now require the `mailers` folders presence, my suggestion would be to give a hint in the upgrade guide that this may cause trouble. [Here](https://gist.github.com/kaikuchn/1ca0f8346813f1b83e32e855254f3bd7)'s the corresponding stack trace users will see.

Best regards,
Kai

**Comment by jodosha** [comment]
@kaikuchn Hi, would you be so kind to add a PR here to add that missing step? Thank you very much! https://github.com/hanami/hanami.github.io/pulls
