### ISSUE TITLE
Allow to start only specific hanami apps

### ISSUE THREAD

**Issue by davydovanton** [hanami/hanami#778]
I think one of the killer features of hanami is isolated applications. That's why I believe that it will be awesome if we allow options for start hanami server only with specific apps. Something like this:
```
$ hanami s --only=api
$ HANAMI_APPS=account hanami s
```

## Why is so important? 

With this feature, we will scale our monolith hanami application by domain-specific servers. For example:

1. Set only API cluster independent of main web app
2. Display admin (or analytic) apps only in private network only 

## Progress

I [created a simple commit](https://github.com/hanami/hanami/commit/4bf099f3bc8add02b2718ae98580b7aeb1eee849) with `HANAMI_APPS` logic, and if it is reasonable, I can continue work on it.

WDYT @hanami/core?

/cc @beauby

**Comment by beauby** [comment]
As discussed, I :+1: the idea. Not sure about the implementation though. I'd suggest something along the lines of:
```ruby
# config/environment.rb
require 'bundler/setup'
require 'hanami/setup'
require 'hanami/model'
require_relative '../lib/bookshelf'
require_relative '../apps/web/application' if Hanami::Utils.application_enabled?(:web)
require_relative '../apps/api/application' if Hanami::Utils.application_enabled?(:api)

Hanami.configure do
  mount Web::Application, at: '/' if Hanami::Utils.application_enabled?(:web)
  mount Api::Application, at: '/api' if Hanami::Utils.application_enabled?(:api)
  # ...
end
```

where `application_enabled?` is something along the lines of:
```ruby
def application_enabled?(app_name)
  return true unless ENV.key?('HANAMI_APPS')
  ENV['HANAMI_APPS'].split(',').include?(app_name.to_s)
end
```

**Comment by davydovanton** [comment]
Closed
