### ISSUE TITLE
Clever description of adding new body parsers and new formats

### ISSUE THREAD

**Issue by deemytch** [hanami/hanami#779]
Suppose I want to add an parser for say msg_pack format.
I found two places where it is described:
1. Here is not clear, where to place those pieces of code.
https://github.com/hanami/router#custom-parsers
2. Description here is different from previous and not working
http://hanamirb.org/guides/actions/parameters/#body-parsers
with `NameError: uninitialized constant Proxy::Application::MsgPackParser`

system: archlinux x64, ruby 2.4.1p111, hanami 1.0.0

Steps to reproduce:

1. `hanami new proxy -d postgresql --application-name=proxy --template=haml --test=rspec --hanami-head`
2. create lib/msg_pack_parser.rb with
```ruby
class MsgPackParser
  def mime_types
    %w[application/msgpack binary/msgpack application/x-msgpack]
  end
  def parse(body)
    MessagePack.unpack(body)
  end
end
```
3. edit apps/proxy/application.rb adding to configure block
```ruby
configure do
  body_parsers :json, MsgPackParser.new
```
4. `bundle exec hanami generate action proxy root#index`
5. adding `get '/', to: 'root#index'` to apps/proxy/config/routes.rb
6. `bundle exec hanami server -p2300 --host=0.0.0.0`

I'm not sure that is a bug in Hanami, but maybe docs are missing something?

**Comment by davydovanton** [comment]
@deemytch hey, did you require your parser file to `apps/proxy/application.rb` file?

**Comment by deemytch** [comment]
There are at least 3 points where I can add  `require_relative my_parser` but I think this have to be added to wiki.
At the end I added require directive to the `lib/proxy.rb` and got bug#780, hehe.

**Comment by beauby** [comment]
Related to this: it might be worth introducing a way for gems to register new body parsers that could be referred to by name, i.e.:
```ruby
configure do
  body_parsers :foo # Instead of MyGem::FooBodyParser.new
  # ...
end
```

Currently this is doable by piggy-backing on the Hanami namespace, but it's far from a clean solution.

**Comment by jodosha** [comment]
@deemytch Hi, it looks like Ruby gets confused by how the class is referenced. I've got two questions for you:

  1. What's the **complete** class name of `MsgPackParser`? Is it namespaced?
  2. If it's **not** namespaced, what happens if you do: `body_parsers :json, ::MsgPackParser`? (Note the `::` prefix)

**Comment by jodosha** [comment]
@deemytch Do you have any news about this? Thanks in advance.

**Comment by deemytch** [comment]
Hi, just had veery busy at work, sorry. Will check that next week.

**Comment by jodosha** [comment]
Closing as stale. @deemytch Feel free to comment an update in the future.
