### ISSUE TITLE
Need utf-8 out of the box

### ISSUE THREAD

**Issue by deemytch** [hanami/hanami#780]
archlinux x64, ruby 2.4.1p111, hanami v1.0.0

```bash
hanami new stub -d postgresql --application-name=stub --template=haml --test=rspec
cd stub
bundle install --path=vendor/bundle
bundle exec hanami server -p2300 --host=0.0.0.0
```
Sending POST with postman:
header: "Content-Type: application/xml"
```xml
<?xml version="1.0" encoding="utf-8"?>
<request>
    <Opcode>1</Opcode>
    <Customer>
    	<firstName>Йоанн</firstName>
	<lastName>Сидоренко</lastName>
    </Customer>
</request>
```
Answer is:

> 
> Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT
> 	stub/vendor/bundle/ruby/2.4.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:76:in `format_error'
> 	stub/vendor/bundle/ruby/2.4.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:52:in `proceed_as_parent'
> 	stub/vendor/bundle/ruby/2.4.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:28:in `call!'
> 	stub/vendor/bundle/ruby/2.4.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:18:in `call'
> 	stub/vendor/bundle/ruby/2.4.0/gems/hanami-1.0.0/lib/hanami/assets/static.rb:49:in `call'
> 	stub/vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/lint.rb:49:in `_call'
> 	stub/vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/lint.rb:37:in `call'
> 	stub/vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/show_exceptions.rb:23:in `call'
> 	stub/vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/handler/webrick.rb:86:in `service'
> 	/usr/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
> 	/usr/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
> 	/usr/lib/ruby/2.4.0/webrick/server.rb:290:in `block in start_thread'

Sending with curl:
```bash
curl -X POST -d 'А мама мыла аРаму' http://localhost:2300/
```
Answer is:

> 
> [2017-05-08 13:22:23] ERROR Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT
> 	(erb):252:in `concat'
> 	(erb):252:in `block in pretty'
> 	(erb):249:in `each'
> 	(erb):249:in `pretty'
> 	/usr/lib/ruby/2.4.0/erb.rb:896:in `eval'
> 	/usr/lib/ruby/2.4.0/erb.rb:896:in `result'
> 	stub/vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/show_exceptions.rb:96:in `pretty'
> 	stub/vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/show_exceptions.rb:32:in `rescue in call'
> 	stub/vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/show_exceptions.rb:23:in `call'
> 	stub/vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/handler/webrick.rb:86:in `service'
> 	/usr/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
> 	/usr/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
> 	/usr/lib/ruby/2.4.0/webrick/server.rb:290:in `block in start_thread'

**Comment by davydovanton** [comment]
@hanami/core WDYT?

**Comment by kaikuchn** [comment]
What's your `echo $LANG` @deemytch ?

**Comment by deemytch** [comment]
Very interesting. I made a repo https://github.com/deemytch/hanamistub
```bash
$ echo $LANG
ru_RU.UTF-8
$ which ruby
/usr/bin/ruby
$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
```

**Comment by kaikuchn** [comment]
Okay, I cloned that repository, I specified my local postgresql as the database url and prepared the db using `hanami db prepare`. I then started the server using `bundle exec hanami s`.
Now:
```
❯ curl -X POST -d 'А мама мыла аРаму' http://localhost:2300/

```
gives me a blank response.

I do see some warnings in the server logs:
```
Haml::TempleEngine: Option :disable_escape is invalid
Haml::TempleEngine: Option :disable_escape is invalid
Haml::TempleEngine: Option :disable_escape is invalid
[proxy] [INFO] [2017-05-09 14:31:48 +0200] HTTP/1.1 POST 405 ::1 /  - 0.00514
```

**Comment by deemytch** [comment]
Ok. I forgot about `db prepare`. I did it, and got
```bash
$ bundle exec hanami server -p2300 --host=0.0.0.0
Puma starting in single mode...
* Version 3.8.2 (ruby 2.4.1-p111), codename: Sassy Salamander
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:2300
Use Ctrl-C to stop
Haml::TempleEngine: Option :disable_escape is invalid
Haml::TempleEngine: Option :disable_escape is invalid
Haml::TempleEngine: Option :disable_escape is invalid
[proxy] [INFO] [2017-05-09 16:03:50 +0300] HTTP/1.1 POST 405 127.0.0.1 /  - 0.004816262
```

**Comment by kaikuchn** [comment]
So everything works for you?
It is weird that you did not get a `Hanami::Model::Error: PG::ConnectionBad: FATAL:  database "proxy_development" does not exist` error when you forgot to run `db prepare`. Did the database exist but with different settings? I.e., when you drop it now and curl your server, do you get the correct `ConnectionBad` error?

**Comment by mereghost** [comment]
It seems that rack was trying to render the error about the missing database and including the utf-8 payload on the message and it was failing miserably.

**Comment by mereghost** [comment]
As it's solved, closing this.
