### ISSUE TITLE
Error when db/migrations folder is not present

### ISSUE THREAD

**Issue by arni1981** [hanami/hanami#785]
Steps to reproduce:
1. Manually remove `db/migrations` folder.
2. Run `bundle exec hanami g model user`

Fails with this error message:

> Errno::ENOENT: No such file or directory @ realpath_rec - /home/arni1981/www/hanami/sandbox/db/migrations

**Comment by arni1981** [comment]
Perhaps I should have filed this in Hanami::Model, since it seems to boil down to this line 

[](https://github.com/hanami/model/blob/master/lib/hanami/model/configuration.rb#L75)

**Comment by artofhuman** [comment]
@cllns What behavior for this issue. If we don't have migrations directory which setup in the config, should we create this directory or use project root?

**Comment by cllns** [comment]
@arni1981 I think this belongs here, actually, since it's a generator problem.

@artofhuman I think we should create the `db/migrations/` folder, if it doesn't exist.

**Comment by jodosha** [comment]
Fixed by #809
