### ISSUE TITLE
Initializers don't load

### ISSUE THREAD

**Issue by jarosluv** [hanami/hanami#787]
Hey, guys!

I don't certainly sure what's happend, but it's pretty strange that files in new Hanami project under `config/initializers` doesn't load.

How to reproduce:
1. `hanami new foo`
2. `cd foo`
3. `bundle`
4. `echo 'puts "FOO"' > config/initializers/foo.rb`
5. `hanami server` doesn't show anything. `Ctrl-C`
6. Add line `require_relative "./initializers/foo.rb"` to top of `config/environment.rb` 
7. `hanami server` shows `FOO`

Hanami 1.0.0

**Comment by Morozzzko** [comment]
Same thing happened with my pet project a month ago. 
Used the `require_relative` workaround, worked like a charm.

I used to believe it was an intentional design decision. Not sure now though.

**Comment by jarosluv** [comment]
I saw code and it must be done automatically from the box, as I understand.

**Comment by mereghost** [comment]
Without the require, do you get the output when opening a console? Same with doing a simple request to the root url?

**Comment by jarosluv** [comment]
@mereghost 

In both cases I see "FOO" even without require.

**Comment by mereghost** [comment]
Yeah. It's our "code reloading" feature biting us again. On it.

**Comment by jodosha** [comment]
@jarosluv Can you please confirm that isn't working because of _code reloading_? What happen if you start the server with `bundle exec hanami server --no-code-reloading`? Does it work as expected?

**Comment by jarosluv** [comment]
@jodosha 

Yes, I confirm that server with `--no-code-reloading` starts properly as expected (string `FOO` outputs in terminal).

**Comment by jodosha** [comment]
Would you give this gem a try? https://github.com/jodosha/hanami-reloader
This is an alternative to `shotgun`. I'm using it from more than a month and seems to work decently.
