### ISSUE TITLE
Do you want some magic?

### ISSUE THREAD

**Issue by jarosluv** [hanami/hanami#788]
Hi, folks!

I've found the most strange behavior of Hanami and I hasten to share with you.

As a new Hanami user, I think that app must be loaded through `boot.rb` file.
This is not true. The start of app loading don't touch `boot.rb` and is located in the `config.ru` file. Okay, I think `boot.rb` used in another cases. I'll deal with it later.

Go further.

I see that environment required in this file `config.ru`. Exactly what is needed. 

**Okay, but let's try to comment this line `require "./config/environment"`. I expect that application should stop correctly loading. And what I see? I see that nothing fail. Why? Because Hanami requires environment implicitly under the hood, here `/lib/hanami/environment.rb`.**

Is it normal?
What I need to do, if I have logic that must be loaded before Hanami?

**Comment by jodosha** [comment]
@jarosluv Hi. Which logic do you need to run before Hanami?

**Comment by jarosluv** [comment]
@jodosha 

I want to preinitialize I18n. But certainly I can do this in `environment.rb`. Nonetheless, the question is different. There is sick moment with **explicitly** requiring of `environment.rb`. It's no sense, since it already **implicitly** loaded from the Hanami gem internals.

**Comment by jodosha** [comment]
@jarosluv Can you please share that code of that initialize I18n? I mean all the Ruby files involved.

I think you hit a problem that I want to fix.

**Comment by jarosluv** [comment]
@jodosha 

```ruby
# config/initializers/i18n.rb

I18n.load_path = Dir[Hanami.root.join("config/locales/**/*.{yml,rb}")]
I18n.default_locale = "ru"
I18n.backend.load_translations
```

For now, I also use this code in `config/environment.rb`:
```ruby
Dir["./config/initializers/*.rb"].each { |file| require file }
```

But issue with initializers about something else, I describe the problem here  https://github.com/hanami/hanami/issues/787

This issue about strange requiring of `environment.rb`.

**Comment by jodosha** [comment]
@jarosluv 

Initializers are meant to be loaded as last thing during the boot process. In my understanding, you want to load that file, **before** the boot process. Is it correct?

**Comment by jarosluv** [comment]
@jodosha 

Yes, my first idea was the same. May be I had wring intentions, but current behaviour of booting Hanami is bewildering. Why we require `./config/environment` explicitly, if we already require it in Hanami sources?

**Comment by AlfonsoUceda** [comment]
ping @jodosha ☝️
