### ISSUE TITLE
Run command-line utilities from subfolders

### ISSUE THREAD

**Issue by cllns** [hanami/hanami#803]
In #790, @mbajur accidentally ran `hanami` commands from a subfolder, rather than their main hanami directory.

I think we should allow hanami commands in any subfolder of the main project folder.

This will require traversing up the folder hierarchy, looking for a Hanami project, and running the command from there.

This should be done *after* the `hanami-cli` integration is complete, I think.

**Comment by AlfonsoUceda** [comment]
@cllns do you think it worths it?

**Comment by cllns** [comment]
Yea! It shouldn't be too complicated. When running commands, make sure `Gemfile` (or `gems.rb`) exists, if not, move to parent folder and repeat.

**Comment by jodosha** [comment]
@cllns I reflected for long time on this: I don't think it's worth the effort.

The solution is to make sure that the paths are always relative to the current directory of execution and interpolate accordingly. That would increase the complexity of our testing suite.

Alson, imagine support tickets here: "this command doesn't work", then we should figure out which was the directory where the developer ran that said command.

AFAIK we have only one case, which can be easily "fixed" by telling people to run commands from the root of the project.

**Comment by jodosha** [comment]
@cllns Feel free to reopen if you think we should implement this in the future. For now we can't make it in 1.1.0. Thank you. 💚
