### ISSUE TITLE
Improve connection string parsing

### ISSUE THREAD

**Issue by olistik** [hanami/hanami#805]
As per the [PostgreSQL documentation](https://www.postgresql.org/docs/9.6/static/libpq-connect.html):

> ## 32.1.1.2. Connection URIs
> [..] Components of the hierarchical part of the URI can also be given as parameters. [..]

Given `DATABASE_URL` from `.env.development`:

```
DATABASE_URL="postgresql://localhost/bookshelf_development?user=deployer&password=pass"
```

When I invoke the `db console` command I get prompted for a password and if I enter one I can see that the user has not been considered too (`olistik` is my system user):

```
$ bundle exec hanami db console
Password:
psql: FATAL:  password authentication failed for user "olistik"
```

meaning that the query parameters are ignored.

Is this expected?
Should we parse the connection string as per the PG documentation?

**Comment by AlfonsoUceda** [comment]
Hi @olistik thanks for opening the issue, I think we can handle both scenarios. I think this is not supported because we aren't aware of that behaviour.

Would you like to open a PR to add this new behaviour? Meanwhile you can use `user`, `password` and `port` the "host part".

**Comment by jodosha** [comment]
Implemented by https://github.com/hanami/model/pull/441
