### ISSUE TITLE
builtin javascript compressor produce errornous output

### ISSUE THREAD

**Issue by badoet** [hanami/hanami#810]
to repro:

run hanami assets precompile  with a javascript that have axios.js
when trying to compile this part:
```
module.exports = function isAbsoluteURL(url) {
  return /^([a-z][a-z\d\+\-\.]*:)?\/\//i.test(url);
};
```
it will produce: 
```
e.exports=function(e){return/^([a-z][a-z\d\+\-\.]*:)?\/\})
```
and this will fail
when i try out with uglifier, it will produce
```
t.exports=function(t){return/^([a-z][a-z\d\+\-\.]*:)?\/\//i.test(t)}}
```

help please?

**Comment by kaikuchn** [comment]
Hi @badoet,

thanks for reporting this. Any reason you're not using uglifier during asset precompilation?
See the [guide](http://hanamirb.org/guides/assets/compressors/) on how to use other compressors than the builtin one.

The [builtin js compressor](https://github.com/hanami/assets/blob/master/lib/hanami/assets/compressors/builtin_javascript.rb) is a [copy](https://github.com/hanami/assets/blob/master/lib/hanami/assets/compressors/jsmin.rb) of the unmaintained [JSMin gem](http://github.com/rgrove/jsmin).
I don't know if it makes sense to fix bugs in it. I guess this will have to be discussed.

In the meantime, I'd suggest that you switch to another compressor if at all possible.

**Comment by badoet** [comment]
hi @kaikuchn,
thanks for the quick reply
we were dockerizing the app so as much as possible trying to keep it light by not installing nodejs into that container image. for now we resolve this issue by pre compressing it using webpack so as not to rely on hanami for the compression. so we comment out the javascript_compressor in the application.rb and hanami will only be used to generate the fingerprinted file during hanami precompile.
hopefully this info will help someone who encounter the same problem.
i will close this issue for now.

**Comment by jodosha** [comment]
@badoet The `:builtin` compressor is just a quick/bogus algorithm that is not efficient. Do you know that you can use YUI, Uglify, or Google Closure compressors for Javascript?
http://hanamirb.org/guides/1.0/assets/compressors/#javascript
