### ISSUE TITLE
android browser support?

### ISSUE THREAD

**Issue by badoet** [hanami/hanami#819]
We are getting this following error on the android 2.3 default browser
![screen shot 2017-08-16 at 3 55 14 pm](https://user-images.githubusercontent.com/527102/29353101-a485b23a-829b-11e7-80a4-60da37041d56.png)

just want to check if this is a known issue for hanami on older android browser?

**Comment by Edwardzyc** [comment]
I am pretty sure this is a server-side issue. I don't see how a missing template issue would be related to the browser

**Comment by AlfonsoUceda** [comment]
Hi @badoet, I'm with @Edwardzyc it seems a server side issue related with rendering a xml file, are you requesting xml views from your android browser?

**Comment by AlfonsoUceda** [comment]
Closing
