### ISSUE TITLE
Generating View Spec?

### ISSUE THREAD

**Issue by cllns** [hanami/hanami#831]
Right now, when you generate a controller action, you get a view, and an associated view spec.

It has one expectation, that is just an example. (It's [pending](https://github.com/hanami/hanami/pull/664), which is fine)
```ruby
RSpec.describe Web::Views::Books::Index do
  let(:exposures) { Hash[foo: 'bar'] }
  let(:template)  { Hanami::View::Template.new('apps/web/templates/books/index.html.erb') }
  let(:view)      { described_class.new(template, exposures) }
  let(:rendered)  { view.render }

  it 'exposes #foo' do
    pending 'This is an auto-generated test. Edit it and add your own tests.'

    # Example
    expect(view.foo).to eq exposures.fetch(:foo)
  end
end
```

I don't think this example provides any value for the users.
Whatever you add to the `exposures` hash becomes **automatically** available as a method on the view.

For example, we can add a new key/value pair to our exposures. Let's say `hello: "WORLD"` 

```ruby
RSpec.describe Web::Views::Books::Index do
  let(:exposures) { Hash[foo: 'bar', hello: "WORLD"] }
  let(:template)  { Hanami::View::Template.new('apps/web/templates/books/index.html.erb') }
  let(:view)      { described_class.new(template, exposures) }
  let(:rendered)  { view.render }

  it 'exposes #foo' do
    pending 'This is an auto-generated test. Edit it and add your own tests.'

    # Example
    expect(view.foo).to eq exposures.fetch(:foo)
    expect(view.hello).to eq exposures.fetch(:hello)
  end
end
```
It doesn't test any behavior on the object under test. 

Therefore, I don't think it's worthwhile to generate this expectation for users.
I propose we leave the `let` statements, to help set up the object, but get rid of the `it 'exposes #foo'` example.

Furthermore, should we call them "exposures"? It seems like a more appropriate name is `locals`, for the view? They're called exposures at the action level, not the view level.

Thoughts? cc/ @hanami/core

**Comment by AlfonsoUceda** [comment]
@cllns maybe we can set that spec as pending, in any case that test is useless.
