### ISSUE TITLE
Proposal: hanami routes check command

### ISSUE THREAD

**Issue by unhappychoice** [hanami/hanami#842]
I'm currently using a rake command below although I know it's not a clean code :sob:

https://gist.github.com/unhappychoice/3e76bbcdbc49ed42a4f0e87f3c9c6ca7

This command checks each routes has an appropriate action file  and vice versa.
Can this be a command like `hanami routes check`?

**Comment by jodosha** [comment]
@unhappychoice Hi, is this a command to verify that all the routes are resolving to an existing action?

Eg.

```ruby
get "/books", to: "missing#action"
```

In that case `Web::Controllers::Missing::Action` isn't an existing action. Is my understanding correct? If not, can you please provide an example of a route that **won't** pass your check? Thanks.

**Comment by unhappychoice** [comment]
It's correct as one example, I think.
I supposed that check should be fail with two patterns below.

#### Route has no defined actions
in `apps/web/config/routes.rb`
```
get "/books", to: "books#index"
```

and "Web::Controllers::Books::Index" is **not** defined.

and cli will say `Web::Controllers::Books::Index is not defined. `

#### Actions has no defined routes

in `apps/web/config/routes.rb`
```
# empty
```

and "Web::Controllers::Books::Index" is defined somewhere.

and cli will say `Web::Controllers::Books::Index is defined but no route is using it`

**Comment by unhappychoice** [comment]
I realized that there are possibilities that modules or classes not used by routes are defined under `Web::Controllers` namespace.
So, `2` case is not good, maybe.

**Comment by jodosha** [comment]
@unhappychoice Yeah, I agree that case 2 isn't good.

I'd like to suggest you a solution. Instead of adding this check command in the core, would you like to write a gem plugin for Hanami? It should provide a command like `hanami routes check` and return the response of it.

Here's an example how how to do it: https://github.com/jodosha/hanami-reloader

**Comment by unhappychoice** [comment]
OK, I will do that 👀 
Thank you for your response 👍
