### ISSUE TITLE
Hanami routes error in 1.1

### ISSUE THREAD

**Issue by m45t3r** [hanami/hanami#848]
I am preparing my application from Hanami 0.9 to 1.1. When trying to run in Hanami 1.1.rc1:
```
$ bundle exec hanami routes
```

I get the following error:
```
Component not resolved: `logger'.
Resolved components are: environment
```

I also got the same error in Hanami 1.1beta1 and beta3, and also in Hanami 1.0. However our application does not run in Hanami 1.0 since we depend on Custom Loggers feature (and this is the reason why we skipped Hanami 1.0 migration).

A reduced example of our `apps/api/application.rb` file:
```ruby
module API
  class Application < Hanami::Application
    ...
    configure do
        set_logger Hanami.logger
        middleware.use ::App::Middlewares::RequestLogger, Hanami.logger
    end
    ...
  end
end
```

And our `config/environment.rb`:
```ruby
Hanami.configure do
  ...
  environment :development do
    logger ::Logger.new(STDOUT)
  end

  environment :test do
    logger ::Logger.new("log/test.log")
  end

  environment :production do
    logger ::Logger.new(STDOUT)
  end
  ...
end
```

So is there something missing here?

**Comment by jodosha** [comment]
@m45t3r Hi and thanks for reporting this problem.

First question: `set_logger` what is that about? 😄 

Can you please generate a new project with Hanami 1.1.0.rc1? Then copy and paste the contents of `config/environment.rb` from the new project to yours. **Don't try to add the custom logger yet**. What happens when you `bundle exec hanami routes`?

I'm trying to isolate the problem: if it's the custom logger that doesn't work or if something else.

**Comment by m45t3r** [comment]
Thanks @jodosha, I think there was a `set_logger` for older versions of Hanami, removed.

I removed all the apps from `config/environment.rb` and it seems to work, so the problem seems to be in the `apps/*/application.rb` files. Investigating.

**Comment by m45t3r** [comment]
Minimal example to reproduce the issue, in `apps/api/application.rb`:
```ruby
module API
  class Application < Hanami::Application
    ...
    Hanami.logger
    ...
  end
end

**Comment by m45t3r** [comment]
@jodosha Any update on this issue?

I can explain why we need to call `Hanami.logger` in our `apps/*/application.rb`. With the following code:

```ruby
module Admin
  class Application < Hanami::Application
    ...
    configure do
        middleware.use ::App::Middlewares::RequestLogger, ::Logger.new(STDOUT)
    end
    ...
  end
end
```

We get log lines like this for a single request (in this case trying to access `/admin/sessions/new` path):

```
INFO [2017-10-25T21:20:21-02:00] [request_id=2a245fcc-0c25-4131-a83a-07f59b16dfcc] Started GET "/admin/sessions/new" for 127.0.0.1
INFO [2017-10-25T21:20:21-02:00] [request_id=2a245fcc-0c25-4131-a83a-07f59b16dfcc] Completed 200 in 0.085766112
INFO [2017-10-25T21:20:21-02:00]  {:http=>"HTTP/1.1", :verb=>"GET", :status=>"200", :ip=>"127.0.0.1", :path=>"/admin/sessions/new", :length=>"2352", :params=>{}, :elapsed=>0.092916037}
127.0.0.1 - - [25/Oct/2017:21:20:21 -0200] "GET /admin/sessions/new HTTP/1.1" 200 2352 0.0937
```
With the following code:

```ruby
module Admin
  class Application < Hanami::Application
    ...
    configure do
        middleware.use ::App::Middlewares::RequestLogger, ::Logger.new(STDOUT)
    end
    ...
  end
end
```
We get the following lines in the log:
```
INFO [2017-10-25T21:26:37-02:00] [request_id=9bf5e639-2197-4a32-adf4-5456320c7324] Started GET "/admin/sessions/new" for 127.0.0.1
INFO [2017-10-25T21:26:37-02:00] [request_id=9bf5e639-2197-4a32-adf4-5456320c7324] Completed 200 in 0.043934389
INFO [2017-10-25T21:26:37-02:00] [request_id=9bf5e639-2197-4a32-adf4-5456320c7324] {:http=>"HTTP/1.1", :verb=>"GET", :status=>"200", :ip=>"127.0.0.1", :path=>"/admin/sessions/new", :length=>"2352", :params=>{}, :elapsed=>0.051206202}
127.0.0.1 - - [25/Oct/2017:21:26:37 -0200] "GET /admin/sessions/new HTTP/1.1" 200 2352 0.0522
```

The difference is subtle but important: we can now which `request_id` originated the HTTP params.

**Comment by m45t3r** [comment]
Found a workaround:
```
module Admin
  class Application < Hanami::Application
    ...
    configure do
        Hanami::Components.resolve("logger")
        middleware.use ::App::Middlewares::RequestLogger, Hanami.logger
    end
    ...
  end
end
```

**Comment by jodosha** [comment]
@m45t3r Sorry for taking so long.

We're not going to resolve the logger for `hanami routes`, as it's not a general requirement for that command.

---

To fix your app, IMO you shouldn't use private API, as it will likely change in the future.
Here's how you can safely do it:

```ruby
# config/environment.rb
BOOKSHELF_LOGGER = ::Logger.new($stdout)

Hanami.configure do
  # ...
  environment :development do
    logger BOOKSHELF_LOGGER
  end
end
```

And

```ruby
# apps/web/application.rb

middleware.use ::App::Middlewares::RequestLogger, BOOKSHELF_LOGGER
```

**Comment by m45t3r** [comment]
Thanks @jodosha, I concur that using a private API is not ideal, and your workaround works, so I am going to use it for now.
