### ISSUE TITLE
Mailer generator - options template output is broken

### ISSUE THREAD

**Issue by cllns** [hanami/hanami#851]
In a new app, with `1.1.0.rc1`, running: 

`bundle exec hanami generate mailer blah --from=fromuser@example.com --to=touser@example.com`

Generates:
```
class Mailers::Boo
  include Hanami::Mailer

  from    fromuser@example.com
  to      touser@example.com
  subject 'Hello'
end
```

Which isn't valid Ruby. Instead, we should put the email addresses inside string quotes.

Also, adding one level of quotes doesn't fix it either. You have to do:
`bundle exec hanami generate mailer blah --from="'fromuser@example.com'" --to="'touser@example.com'"` in order to get it to work properly (or switch the order of the nested quotes).

**Comment by AlfonsoUceda** [comment]
Fixed by #854
