### ISSUE TITLE
Generate a `bin/setup` command script as part of app generation

### ISSUE THREAD

**Issue by jdickey** [hanami/hanami#852]
Related to, but not identical to, #676.

This would introduce behaviour analogous to Rails, dry-web-roda, and several other frameworks in languages including but not limited to Ruby.

There ought to be a standardised-format script to install and bundle Gems, set the database into a known initial state, etc. By being database-aware, it would defend against newbies paying too-literal attention to the current [*Getting Started*](http://hanamirb.org/guides/1.1/getting-started/) guide's description (if not recommendation) of PostgreSQL as a database server. To successfully run a freshly-generated Hanami app which uses PostgreSQL, one must first run `createdb app_name_development`, where `app_name` is (obviously) replaced by your actual app name.

By doing so, we also leave more open the possibility of bundling with [binstubs](https://bundler.io/v1.15/man/bundle-binstubs.1.html), which would support use of, e.g., `bin/rake` rather than `bundle exec rake`, hence touching on #676. Bundler by default puts binstubs into a `./bin` directory.

**Comment by AlfonsoUceda** [comment]
@jdickey it makes sense ;) you are welcome if you want to create the PR.

**Comment by jodosha** [comment]
I added the `help-wanted` label and closing this proposal because of the idle conversation. If someone wants to take responsibility for this enhancement, please make it happen.
