### ISSUE TITLE
Custom error page not rendered when an exception is raised inside view or template sections.

### ISSUE THREAD

**Issue by AlfonsoUceda** [hanami/hanami#865]
The original bug was opened by @cveneziani in https://github.com/hanami/view/issues/138 but that bug belongs to hanami gem.

When an exception is raised inside view or template section, we don't display the custom error template so the application will render the exception with the backtrace.

**Comment by graywolf** [comment]
Will be fun when exception raised in custom error page template triggers usage of custom error page template :)

**Comment by AlfonsoUceda** [comment]
@graywolf why? did you think in stack level too deep?

**Comment by graywolf** [comment]
I just ment it could get in a loop so some precautions should be taken that it doesn't happen.

**Comment by AlfonsoUceda** [comment]
@graywolf thanks for the hint :P at least I tested in local and an error is displayed, I'll create a test to avoid regressions.
