### ISSUE TITLE
No documented way to supress error pages

### ISSUE THREAD

**Issue by graywolf** [hanami/hanami#874]
Only thing related to error pages I managed to find in the guides is this http://hanamirb.org/guides/views/custom-error-pages/ , but it talks only about how to make own custom error page. However there is no mention of how to ignore error pages (ideally just for one action) and draw normal page but with different http code than 200.

**Comment by graywolf** [comment]
Hm, to sum up my research into this, it doesn't seem possible at the moment. I solved it by monkey-patching `Hanami::RenderingPolicy` with this code:

    def render_status_page?(action, response)
      additional_successful_statuses = []
      if action.respond_to?(:additional_successful_statuses)
        additional_successful_statuses = action.additional_successful_statuses
      end
      RENDERABLE_FORMATS.include?(action.format) &&
        !(SUCCESSFUL_STATUSES.to_a + additional_successful_statuses).
          include?(response[STATUS])
    end

and my action now looks defines this:

    def additional_successful_statuses
      [403]
    end

seems to work just fine. Would something like this me accepted into Hanami
if I put together a pull request with this?

**Comment by davydovanton** [comment]
hey, thanks for this issue. Could you provide example when you need to use web page with different http status?

**Comment by graywolf** [comment]
Sure, in my case it's a login form. On failed login I want to return 403 (since login failed, everything obviously wasn't OK, so 200 seems misleading), but at the same time I want to render the form again with prefilled username and stuff.That's just not possible atm in hanami.(technically, I could probably move the login form to separate app and make it's 403 error page same template as the login form; just a thought I had right now, should probably work? while a workaround, doesn't seem like /right way/ to do it)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Anton DavydovSent: Friday, January 12, 2018 01:29To: hanami/hanamiReply To: hanami/hanamiCc: W.; AuthorSubject: Re: [hanami/hanami] No documented way to supress error pages (#874)hey, thanks for this issue. Could you provide example when you need to use web page with different http status?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/hanami/hanami","title":"hanami/hanami","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/hanami/hanami"}},"updates":{"snippets":[{"icon":"PERSON","message":"@davydovanton in #874: hey, thanks for this issue. Could you provide example when you need to use web page with different http status?"}],"action":{"name":"View Issue","url":"https://github.com/hanami/hanami/issues/874#issuecomment-357106387"}}}

**Comment by jodosha** [comment]
@graywolf Hi, you wrote:

> On failed login I want to return 403 (since login failed, everything obviously wasn't OK, so 200 seems misleading), but at the same time I want to render the form again with prefilled username and stuff.That's just not possible atm in hanami

This is possible: http://hanamirb.org/guides/1.1/actions/control-flow/#http-status

**Comment by graywolf** [comment]
@jodosha not working for me :/ my code looks like this:

	# frozen_string_literal: true

	module Web::Controllers::Login
	  class NoSuchActiveUser < StandardError; end
	  class WrongPassword < StandardError; end
	  class NotAdmin < StandardError; end

	  class Do
		include Web::Action

	#    def additional_successful_statuses
	#      [403]
	#    end

		def redirect_on_success(user_id)
		  session[:user_id] = user_id
		  redirect_to '/admin', status: 303
		end

		def validate_user!(u, password)
		  raise NoSuchActiveUser unless u
		  raise WrongPassword unless u.verify_password password
		  raise NotAdmin unless u.admin
		end

		def call(params)
		  username = params.[](:user)&.[](:username)
		  password = params.[](:user)&.[](:password)

		  u = User.by_username username

		  validate_user! u, password

		  redirect_on_success u.id
		rescue NoSuchActiveUser, WrongPassword
		  handle_auth_error
		rescue NotAdmin
		  handle_auth_error 'You do not have enough permissions to proceed.'
		end

		expose :error_msg

		private

		def handle_auth_error(msg = 'Invalid credentials.')
		  @error_msg = msg
		  self.status = 403
		  self.body = Web::Views::Login::Form.render(exposures)
		end
	  end
	end

But I still get the error page. I see in the documentation that it should work but I have no idea why it does not :/

**Comment by jodosha** [comment]
@graywolf Why are you assigning the body like this?

```ruby
self.body = Web::Views::Login::Form.render(exposures)
```

**Comment by graywolf** [comment]
Because I have to actions `Web::Controllers::Login::Form` which displays the form and `Web::Controllers::Login:Do` which performs the validations and logs user in (this is the one posted above). So I want to reuse the view for `Web::Controllers::Login::Form`, so I render it like this. It seems to work fine (except for the need to override the `SUCCESSFUL_STATUSES` to include 403)...

**Comment by graywolf** [comment]
I've tried it and that not the case, even when I replace the assigment with just `self.body = 'test'` I do get the error page.

**Comment by jodosha** [comment]
@graywolf Thanks for getting back. Can you please create a demo app over GitHub? Because I can't reproduce the problem.

If you want to reuse the same form, you can:

  1. `hanami generate action sessions#new`
  1. `hanami generate action sessions#create`
  1. Edit action and view like this:

```ruby
module Web::Controllers::Sessions
  class Create
    include Web::Action

    def call(params)
      if user = login(params)
        session[:user_id] = user.id
        redirect_to routes.root_path
      else
        self.body = 401
      end

       private

       def login(params)
          # ...
       end
    end
  end
end
```

```ruby
module Web::Views::Sessions
  class Create
    include Web::View
    template "sessions/new"
  end
end
```

**Comment by graywolf** [comment]
Repro is here: https://github.com/graywolf/repro_for_hanami_874

I think the trick to trigger the problem is setting both `self.status` and `self.body`.

However your suggested approach seems like reasonable way to solve this :)

**Comment by jodosha** [comment]
@graywolf Thanks for your demo app. That isolates well what you mean.

To me this isn't a bug.

Response body set in action is meant to bypass the render of the view.
Setting a non successful status code in the action, triggers the rendering of an error page.

The error page sees the custom body as a message instead of the default HTTP message. In your case, instead of `403 Forbidden`, it uses `403 test'.

**Comment by graywolf** [comment]
But when I just set the status code, normal page is rendered. Shouldn't it also render error page?
