### ISSUE TITLE
Hanami::Action::Flash#[] doesn't work as expected

### ISSUE THREAD

**Issue by graywolf** [hanami/hanami#877]
In action:

```ruby
...
flash[:error] = 'Error message.'
...
```

in template

```ruby
<%= flash[:error] %>
```

what is rendered

```plaintext
{:error=>"Error message."}
```

I would argue that what user (at least me) expects is just

```plaintext
Error message
```

**Comment by graywolf** [comment]
Workaround:

```erb
<div class="flash-messages">
  <% %i{error notice success}.each do |type| %>
	<% if flash[type] %>
	  <div class="flash-message-<%= type %>"><%= flash[type][type] %></div>
	<% end %>
  <% end %>
</div>
```

**Comment by graywolf** [comment]
So the actual issue here is using the flash message in the same request as it was setted. However, that should be supported? Or not?

**Comment by davydovanton** [comment]
hey, thanks for the report. Could you create a simple app with this problem? I tried to reproduce this problem but for me flash works as expected 🤔

**Comment by graywolf** [comment]
Will put one together.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Anton DavydovSent: Friday, January 12, 2018 01:27To: hanami/hanamiReply To: hanami/hanamiCc: W.; AuthorSubject: Re: [hanami/hanami] Hanami::Action::Flash#[] doesn't work as expected (#877)hey, thanks for the report. Could you create a simple app with this problem? I tried to reproduce this problem but for me flash works as expected 🤔

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/hanami/hanami","title":"hanami/hanami","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/hanami/hanami"}},"updates":{"snippets":[{"icon":"PERSON","message":"@davydovanton in #877: hey, thanks for the report. Could you create a simple app with this problem? I tried to reproduce this problem but for me flash works as expected 🤔 "}],"action":{"name":"View Issue","url":"https://github.com/hanami/hanami/issues/877#issuecomment-357106149"}}}

**Comment by graywolf** [comment]
Cannot reproduce on latest hanami.
