### ISSUE TITLE
Additional Settings Adapters (Other Than dotenv)

### ISSUE THREAD

**Issue by jfelchner** [hanami/hanami#888]
I see that you all have a soft dependency on `dotenv`.  Even to the extent that support for it is hard-coded in the codebase.  I maintain [chamber](https://github.com/thekompanee/chamber/wiki) and I'd love to write an integration for Hanami so that Hanami users don't have to do anything to make settings automatically load.  But after looking at the codebase, I can't quite see where that hook would happen.  This would need to happen before any configuration or initializers loaded.  Around the same time that [this happens](https://github.com/hanami/hanami/blob/master/lib/hanami/environment.rb#L489).

Thoughts?

**Comment by AlfonsoUceda** [comment]
cc @jodosha

**Comment by AlfonsoUceda** [comment]
Hi @jfelchner, I'd like to have Chamber integrated with Hanami, I've used and it's very useful. With Hanami 1.

**Comment by jodosha** [comment]
@jfelchner Thanks for getting in touch.

How does `chamber` works with env vars? Specifically, does it turns settings from the YAML file into `ENV` vars? From the code over GH, I didn't find an easy answer. Thanks.

**Comment by jfelchner** [comment]
One of Chamber’s defining features (besides being able to [encrypt settings](https://github.com/thekompanee/chamber/wiki/Encryption-Basics) with one or more project RSA keys) is that it allows you to use rich types for your settings (`FalseClass` instead of the `String` `”false”`).

So, Chamber will [_override_ a YAML setting](https://github.com/thekompanee/chamber/wiki/Environment-Variables) with a value in your ENV ([potentially with coercion](https://github.com/thekompanee/chamber/wiki/Environment-Variable-Coercions)), but all Chamber users [access their settings](https://github.com/thekompanee/chamber/wiki/Accessing-Settings) via `Chamber.env` instead of via `ENV`.

You can see a gem comparison matrix [here](https://github.com/thekompanee/chamber/wiki/Gem-Comparison).

**Comment by jodosha** [comment]
> Chamber users access their settings via Chamber.env instead of via ENV.

Because we're talking about adapters here (`dotenv`, `chamber`), they should be swappable. That means `Chamber.env` couldn't be a solution for Hanami users.

For instance, `ENV` is standard abstraction to access env vars. I guess you have your good reasons to not use `ENV` directly.

What do you suggest instead for Hanami?

**Comment by jfelchner** [comment]
@jodosha of course ENV is the standard for accessing environment variables.  But environment variables are not the best solution for application configuration.

For example, what if you want an environment variable that is a boolean?  What if you want to share your environment variables with other developers (including sensitive information that you can't check in)?
