### ISSUE TITLE
Generate better paths for non-RESTful actions

### ISSUE THREAD

**Issue by cllns** [hanami/hanami#901]
@Pistos [reported](https://gitter.im/hanami/chat?at=5a89d875888332ee3a9dc491) that when generating non-RESTful (resourceful) routes like:
```
hanami generate action web 'session#sign_out'
```

The resulting route is unexpected:
```ruby
          GET, HEAD  /session                       Web::Controllers::Session::SignOut
```

We should consider changing this so that when non-RESTful routes are generated, the path joins the controller name and the action name, with a slash, rather than just using the controller name. So in this case, the generated path would be `/session/sign_out`.

(This isn't a great example, since `sign_out` can, and should, be a resourceful route to `Sessions::Destroy` but, in general, there are some times when people might need to generate non-resourceful routes, and we should generate a path that's not surprising.)

I don't see this as a high priority, since we encourage people to use resourceful routes whenever possible, but I think it'd be a nice enhancement. Thoughts @hanami/core @Pistos @kaikuchn?

**Comment by Pistos** [comment]
In my app, I will indeed use a `DELETE /session` route, but nevertheless, there will probably be times that people will want `controller#endpoint` to map to `/controller/endpoint`.

In the current code, if you execute `hanami generate action web 'controller#action_one'` and `hanami generate action web 'controller#action_two'` it actually creates two lines in the route file for the same route.

**Comment by jodosha** [comment]
Implemented by https://github.com/hanami/hanami/issues/901
