### ISSUE TITLE
Extraneous require 'hanami/model' ?

### ISSUE THREAD

**Issue by malin-as** [hanami/hanami#902]
Hi,

While tinkering with a Sequel-only replacement for `hanami-model` (which would provide the missing `hanami db` commands), I noticed a problem when trying to load the environment in this way:
```ruby
env = Hanami::Environment.new
env.require_application_environment
```
This is because of a `require 'hanami/model'` at line 3 of `config/environment.rb` which was generated with the project. It looks like that line is not necessary because `bundler` will load the necessary gems anyway.

Is it safe to remove that line from the template used for a new project generation (in which case I can submit a PR)?

**Comment by sandelius** [comment]
I dont't think Hanami calls `Bundler.require` but use `setup`. That means you have to require all the gems you listed in your `Gemfile`.

This is IMO a good design that will help you see what dependencies you actually have loaded.

**Comment by malin-as** [comment]
I understand, after asking this question I realised that `hanami` and `hanami-model` are more coupled than I thought, so this question is in the end not very relevant. Thank you nonetheless :)

**Comment by jodosha** [comment]
@malin-as Can you please help me to understand the problem here?

What happens for when your **don't** include `hanami-model` in `Gemfile` **and remove** the `require 'hanami/model'` line?

Does the server/console still start for you? Thanks.

**Comment by malin-as** [comment]
@jodosha it works well when I remove both, I just hadn't cleaned the project correctly when removing `hanami-model`.
