### ISSUE TITLE
Having `--skip-view` by default for some apps

### ISSUE THREAD

**Issue by malin-as** [hanami/hanami#911]
Hi,

I think it could be really useful if one could specify that by default, the generated actions for an app should not create the view, for instance for a RESTful API that replies with JSON messages. It could be called like so:

    $ hanami g app api --no-view

The setting would be stored in a configuration file, though I'm not sure which one and whether or not to track it in git, since this is for convenience on the command line only.

And maybe there could be a new `--create-view` option to actually create the view for the few odd cases where it could make sense (implying that all the view and template files are still generated at app creation time).

**Comment by AlfonsoUceda** [comment]
Hi @malin-as 

This is an interesting setting for building apps for APIs as you said. We're going to think in this.

Thanks!

**Comment by jodosha** [comment]
@malin-as Hi, thanks for this proposal. IMO this is the classic example where we potentially increase the complexity of the internals to support a feature that only needs to save a few keystrokes. It's a pass for me 👎 .
