### ISSUE TITLE
Enable dotenv loading according to behaviour with rails

### ISSUE THREAD

**Issue by nerdinand** [hanami/hanami#916]
Recently I tried to use `.env.local` and `.env.development.local` files to add local-specific environment configurations according to the documentation of dotenv at https://github.com/bkeepers/dotenv#what-other-env-files-can-i-use.

This did not work and it was not immediately obvious to me why. The reason is of course that this loading order of dotenv files only applies to `dotenv-rails`, not to `dotenv` in general.

I'd really like to see the same behaviour in hanami as for rails. The code to accomplish this could be copied from https://github.com/bkeepers/dotenv/blob/master/lib/dotenv/rails.rb#L58.

Alternatively, maybe there could be a hanami-dotenv gem that implements this behaviour or this could be implemented in a more generic way in dotenv itself, not favouring Rails over other frameworks.

What do you think?

**Comment by nerdinand** [comment]
Just noticed that this has been suggested before: https://discourse.hanamirb.org/t/hanami-2-0-ideas/306/31

Any thoughts @jodosha?

**Comment by jodosha** [comment]
@nerdinand Yes, it was already discussed, and I agree.

What I think it should happen is to collect several pieces of experiences and provide an unified solution, not just jump into the conclusion making `.local` file to work. It has to be an organic change.

**Comment by lfmalves** [comment]
Admin, I believe this discussion is duplicated and the topic should be closed

**Comment by jodosha** [comment]
@lfmalves You're right. Closing in favor of https://github.com/hanami/hanami/issues/1003
