### ISSUE TITLE
Adding a --skip-route option to action generator

### ISSUE THREAD

**Issue by cveneziani** [hanami/hanami#919]
The same way we have a `--skip-view` option:

```
--[no-]skip-view # Skip view and template, default: false
```

I was wondering if it could be a good idea to add a `--skip-route` option to the action generator:

```
--[no-]skip-route # Skip route, default: false
```

Maybe it's just me. Here is how I plan my features:

- First, I build the route and deduce a possible action
- I directly write it down in the routes file
- Then, I generate the action
- Which "forces" me to go back to the routes file to remove the automatically generated route

What do you think?

**Comment by jodosha** [comment]
@cveneziani Hi and thanks for this proposal. Can the `--url` option rescue the day?

```shell
hanami g action web users#show --url=/u/:id
```

That is designed specifically to not have to edit the route afterwards. 😉

**Comment by cveneziani** [comment]
I don't think the `--url` option could rescue the day when using `resources`.

### Use case example

First I implement the listing of all books. My routes looks like this: 

```
resources :books, only: [:index]
```

Then, I want to implement the show page of a book. 
When generating the action, with the `--url` option:

```
hanami generate action web books#show --url=/books/:id
``` 

I will end up with the following routes:

```
resources :books, only: [:index]
get '/books/:id', to: 'books#show'
```

I'll still have to edit the route afterwards in order to get:

```
resources :books, only: [:index, :show]
```

### On the workflow

On a side note, as for me, it's not natural to generate the route when generating the action.

When I'm about to implemement a feature: first, I design the route and then deduce the action. So I tend to first edit my routes, run a `hanami routes` to check everything is okay. And finally, I generate the action.

Maybe I'm just an oddball :sweat_smile:
