### ISSUE TITLE
Allow missing views or templates folder

### ISSUE THREAD

**Issue by cllns** [hanami/hanami#920]
Using `1.2.0.rc2`:
```
hanami new blahtest
cd blahtest
bundle install
HANAMI_ENV=test bundle exec hanami db prepare
bundle exec rake # works fine
rm -rf apps/web/templates
bundle exec rake # errors out
```

This is the error:
```
# /Users/sean/.gem/ruby/2.5.0/gems/hanami-view-1.2.0.rc2/lib/hanami/view/configuration.rb:189:in `realpath': No such file or directory @ realpath_rec - /Users/sean/dev/blahtest/apps/web/templates (Errno::ENOENT)
```

A similar error happens for removing `app/web/views` too. 

Removing `app/web/controllers` also causes a similar problem, but it's less likely someone would remove the controllers folder, whereas delegating the views and templates to a separate front-end app is more common. Note that removing `app/web/assets` works fine.

Note that the `rm -rf` is only removing the `.gitkeep` file, so it's just about the folder existing. Not sure if we should handle this at the `hanami/hanami` level (this repo) or inside `hanami/view`.

This is a pretty easy thing to fix (creating the folder), so I don't think it's a blocker for 1.2.

**Comment by davydovanton** [comment]
@cllns did you try to remove `view` folder from `load_paths` array? (`apps/app_name/applications.rb`). Our view require templates that's why if you want to drop templates - you need to drop view too 🤔

**Comment by AlfonsoUceda** [comment]
@cllns did you check @davydovanton's suggestion?

**Comment by cllns** [comment]
@davydovanton Yes, that does seem to work. I think it'd be better to either: show a helpful error about `load_paths`, or just silently work without the folder existing yet. What do you think?

(I got this error from `git clone`-ing a Hanami project that didn't have the `.gitkeep` file in those folder, though it didn't use `views` or `templates`)

**Comment by jodosha** [comment]
@cllns 

> I think it'd be better to either: show a helpful error about load_paths

👍 

> or just silently work without the folder existing yet. What do you think?

👎 Because that just makes the `load_paths` settings useless.

**Comment by jodosha** [comment]
Closing this ticket due to inactivity. @cllns Feel free to reopen and take ownership for it. Thanks.
