### ISSUE TITLE
Problems with dotenv 2.3.0

### ISSUE THREAD

**Issue by citizen428** [hanami/hanami#924]
**Problem:**
Just initialize a new project with Hanami v1.2.0, installed the gems and got the following error when running `bundle exec hanami server`:

```
.../dotenv-2.3.0/lib/dotenv/parser.rb:33:in `call': wrong number of arguments (given 1, expected 2) (ArgumentError)
```

**Potential cause:**
I checked, dotenv 2.3.0 was released after Hanami 1.2.0 and potentially introduced some change that leads to this behavior. 

**Solution:**
I modified the Gemfile to depend on a 2.2. release of dotenv, everything works as expected now with dotenv 2.2.2.

**Comment by hirokiraj** [comment]
Maybe it will help - after short investigation - problem occurs as new version of dotenv (2.3.0 - released 2 days ago), changed initializer for parser, difference can be seen here:

old: https://github.com/bkeepers/dotenv/blob/e388215d69fbf55e8031d8524edf9db22eb66c03/lib/dotenv/parser.rb#L35

new: 
https://github.com/bkeepers/dotenv/blob/master/lib/dotenv/parser.rb#L33

Change was made with fix:
https://github.com/bkeepers/dotenv/commit/7f82f73420bb46a06bb3a3e2052c3b3a1f34a0f5

Current hanami release `1.2.0` still calls parser with just one argument:
https://github.com/hanami/hanami/blob/master/lib/hanami/env.rb#L59

**Comment by spica831** [comment]
Hello,
I was suffering from the same thing
So I modified the dotenv itself
Since it has already been merged already, it got in a state to move once

https://github.com/bkeepers/dotenv/blob/master/lib/dotenv/parser.rb#L33

**Comment by citizen428** [comment]
Thanks @jodosha, so either stay with 2.2. or upgrade to 2.4.

**Comment by tommyalvarez** [comment]
@citizen428 the error is still happening in 2.4.0 and Rails 5.1.5.

**Comment by cllns** [comment]
@tommyalvarez This is the issue tracker for Hanami, which doens't have anything to do with Rails. If you're seeing problems still, you might want to open an issue in `dotenv-rails` (first I'd double-check with `bundle show dotenv` to ensure your project is actually using `2.4.0`)

**Comment by tommyalvarez** [comment]
@cllns my bad I read the issue in google and came directly here without seeing the repo.

**Comment by cllns** [comment]
@tommyalvarez No worries, it happens! Hope you figure the issue out. (And check out [Hanami](http://hanamirb.org/guides/1.2/getting-started/) when you get a chance 😉)

**Comment by joelvh** [comment]
FYI dotenv 2.5.0 just went out, which makes this backwards-compatible: https://github.com/bkeepers/dotenv/pull/345
