### ISSUE TITLE
Add option to run rubocop auto-correct after generating new files

### ISSUE THREAD

**Issue by jwsloan** [hanami/hanami#927]
After generating a set of files, it would be nice for those to comply with the consuming application's rubocop settings. It seems like this could work pretty well by just running `bundle exec rubocop -a`, also passing in the list files generated. 

I can pretty easily run rubocop after generating the files, but it would be handy to be able to target only the newly generated files. 

I'd love to jump in with a PR to make it happen if it's something you'd consider. And any tips you have for how you'd like to see such a thing accomplished would be great.

**Comment by cllns** [comment]
:+1: Should be able to leverage `Hanami::CLI`'s `after` callback: https://github.com/hanami/cli#callbacks

I think we'll have issues with some things that Rubocop doesn't automatically fix though, like long-lines. For example, this happens in `let` blocks in specs a lot, since we generate them with the `{ }` block syntax instead of `do / end` :/

**Comment by jodosha** [comment]
@jwsloan Thanks for the idea, but I'm against it 👎 .

I'm a heavy user of Rubocop, at work, on personal projects. The plans for Hanami are to make both the internal code and generated code to be compliant with Rubocop.

That being said, I don't won't to enforce Rubocop on the Hanami end users.

---

As @cllns mentioned, you can use CLI callbacks and build a small integration for it. Here's how to do: http://hanamirb.org/guides/1.2/command-line/plugins/#hook-into-existing-command

**Comment by jwsloan** [comment]
Thanks for the input, @jodosha! I didn't mean to force folks to use Rubocop. I just meant to make it an option. Thanks for the link. I'll look into just making a separate plugin that does it.

**Comment by jodosha** [comment]
@jwsloan Thanks for understanding. 😄

**Comment by jwsloan** [comment]
You're welcome, @jodosha! While I have your attention... ;) 
Any chance you'd be willing to come speak at https://southeastruby.com/ about Hanami? @timriley spoke about http://dry-rb.org/ there last year, and it would be an awesome followup to have you this year! :)
