### ISSUE TITLE
I don't think `[INSERT EMAIL ADDRESS]` is valid email address 

### ISSUE THREAD

**Issue by graywolf** [hanami/hanami#929]
Our Code of Conduct ( https://github.com/hanami/hanami/blob/master/CODE_OF_CONDUCT.md ) in section `Enforcement` contains this (snippet):

    ... may be reported by contacting the project team at [INSERT EMAIL ADDRESS]. ...

That's not that useful `^_^`

**Comment by jodosha** [comment]
@graywolf Thanks for reporting this. I just fixed it.
