### ISSUE TITLE
Allow plugins to inject their own settings

### ISSUE THREAD

**Issue by jodosha** [hanami/hanami#930]
Allow plugins to inject their own settings in project configuration.

```ruby
# config/environment.rb

Hanami.configure do
  # ...
  development do
    plugins.webconsole do
      allowed_ips << ["172.18.0.0/16"]
    end
  end
end
```

It should introduce a `#plugins` proxy method to yield a block for a specific plugin.
The plugin on its own side, will provide an object to be yielded in that context.

```ruby
# lib/hanami/webconsole/plugin.rb (hanami-webconsole gem)
Hanami.plugin do
  # ...
  settings(:webconsole, Hanami::Webconsole::Configuration.new)
end
```

---

Ref https://github.com/hanami/webconsole/issues/4

**Comment by iJackUA** [comment]
At the first glance, I like how it looks and what possibilities it opens.
Would it work also on upper level of config (not under env block)? Like this
```ruby
Hanami.configure do
# ...
  plugins.webconsole do
      allowed_ips << ["172.18.0.0/16"]
  end
# ...
  development do
     # ...
  end
end
```

The only thing, I am not sure about loading order. Blocks `Hanami.plugin do` starts at the very beginning during Gemfile initialization right? And add blocks to plugins registry. So config objects would be available, but real configuration configuration values woud "come a bit later" when `config/environment.rb` would be evaluated.

I am not sure at them moment would `allowed_ips` value from config be available at the moment when plugin needs it?

As I understand full code for `webconsole` plugin init would looks like this ?

```
# lib/hanami/webconsole/plugin.rb (hanami-webconsole gem)
Hanami.plugin do
  settings(:webconsole, Hanami::Webconsole::Configuration.new)
  middleware.use BetterErrors::Middleware              # <<< what if I need additional params in `use` for middleware init ?
  BetterErrors.application_root = Hanami.root.to_s
  BetterErrors::Middleware.allow_ip! '172.18.0.0/16'  # <<< I need to read config values right here ?
end
```
Would it really work?
Or maybe 2 steps plugin init process required?
At the beginning initialize Configuration objects, that read config from Enviroment.rb (collect it into Config obejcts) and only after that to call all plugins blocks from registry. As I understand right now you do actually intialize Plugins at the very end of app load process, but Config should exist before that moment, am I right? https://github.com/hanami/hanami/blob/05e820d3bd47c5320c5d4a0cc495967db9a48214/lib/hanami/components/components.rb#L326

**Comment by mereghost** [comment]
@jodosha will the methods we use to initialize the framework (i.e. `requires`) be available to plugins?

**Comment by jodosha** [comment]
@mereghost 

> will the methods we use to initialize the framework (i.e. requires) be available to plugins?

Not in my plans. Do you have a need for it?

**Comment by jodosha** [comment]
Closing it as a stale discussion, due to the internal booting reworking based on `dry-container`.
