### ISSUE TITLE
Generate app regex only works with single quotes

### ISSUE THREAD

**Issue by cllns** [hanami/hanami#933]
Very very similar to #883.

That bug causes an error when generating a new app because the file that's expected to be there doesn't exist. In my case, the file does exist _and_ I have the `require_relative "../lib/writer_pages"`. 

The trouble is that the regex we use only looks for single quotes. Instead, we should look for single or double quotes. (I have a rubocop rule to always use double quotes, so this line was automatically 'corrected' for me.)

This won't be solved by the diff in #833. Instead, both the current regex, and the new `apps/` one should allow either single or double quotes.

**Comment by daphsta** [comment]
> This won't be solved by the diff in #833. Instead, both the current regex, and the new apps/ one should allow either single or double quotes.

Hi @cllns did you mean to refer to PR #883 instead , in the above?

**Comment by cllns** [comment]
Yes, sorry, I did mean that PR :)

Go for it! 🌸 ; I'd recommend working off `graywolf`'s `fix_generate_app` branch.
The way I'd do it is `git remote add graywolf git@github.com:graywolf/utils.git` then fetch it and check out the branch. It'll be merged soon. I'd do it now but I don't have the time right now to manually verify it's working. Else, you/we will have to update your PR once #883 is merged.

**Comment by daphsta** [comment]
Thanks @cllns, I'll do just that

**Comment by daphsta** [comment]
Hi @cllns , I've just noticed in https://github.com/hanami/hanami/pull/883 , the regex should match double quotes?

```
def inject_require_app(context)
  content     = "require_relative '../apps/#{context.app}/application'"
  destination = project.environment(context)

  req_regex = /^\s*require .*$/
  rel_regex = /^\s*require_relative .*$/
```

Also, I have found out why I keep running into this error when running the specs for `spec/integration/cli/generate/app_spec.rb`

```
Failure/Error: fail "#{cmd} failed:\n#{out.read}" # rubocop:disable Style/SignalException

     RuntimeError:
       /Users/yiingshan/Documents/Web project/hanami/script/setup failed:
     Shared Example Group: "a new app" called from ./spec/integration/cli/generate/app_spec.rb:24
     # ./vendor/cache/devtools-647f77fb3027/lib/hanami/devtools/integration/silently.rb:17:in `silently'
     # ./vendor/cache/devtools-647f77fb3027/lib/hanami/devtools/integration/bundler.rb:37:in `block in setup'
     # /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.2/lib/bundler.rb:297:in `block in with_clean_env'
     # /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.2/lib/bundler.rb:540:in `with_env'
     # /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.2/lib/bundler.rb:297:in `with_clean_env'
     # ./vendor/cache/devtools-647f77fb3027/lib/hanami/devtools/integration/bundler.rb:55:in `with_clean_env'
     # ./vendor/cache/devtools-647f77fb3027/lib/hanami/devtools/integration/bundler.rb:36:in `setup'
     # ./vendor/cache/devtools-647f77fb3027/lib/hanami/devtools/integration/bundler.rb:163:in `block (2 levels) in <top (required)>'
```

I had to run `sudo ./script/setup` in order for the script to install the gems without permission errors. However, when I run `rspec` on `spec/integration/cli/generate/app_spec.rb`, it fails at the step where the setup script is run. I am unsure how to get around this permission issue that is preventing me from running tests in my local machine. Do you have any suggestion how to get around this?

**Comment by jodosha** [comment]
The problem has been fixed. https://github.com/hanami/hanami/pull/937#pullrequestreview-189041706
