### ISSUE TITLE
Support .env files

### ISSUE THREAD

**Issue by jodosha** [hanami/hanami#96]
Support `.env` files in order to load configurations into ENV variables.
This is a [well known](http://12factor.net/config) and large used best practice.

This is a proposal to support multiple environments and put those files under `config/`. We should have a general file `.env` that is the master of all the configurations. Then we should have per environment settings.

```
# ...
config/
  .env             # general
  .env.development # environment specifics overloads
  .env.test
```

The idea is to use a `dotenv` gem for this.
### Example

```
# config/.env.development
DATABASE_URL="postgres://localhost/bookshelf_development"
```

```
# config/.env.test
DATABASE_URL="postgres://localhost/bookshelf_test"
```

``` ruby
module Bookshelf
  class Application < Lotus::Application
    configure do
      adapter type: :sql, uri: ENV['DATABASE_URL']
    end
  end
end
```

**Comment by jandudulski** [comment]
I know that it is already merged but just to reconsider the topic I'll propose another approach - [ENVied](https://github.com/eval/envied/). The only thing it does is to "eat" the ENV but with coercion (no more problems to handle booleans) and setting required keys (so app won't start until all required keys are there).

And it's up to dev how it populate the `ENV` which is fine - one will use [rbenv-vars](https://github.com/sstephenson/rbenv-vars), others dotenv or anything else.

**Comment by jodosha** [comment]
@jandudulski Thanks for your suggestion but I don't think it's a good idea.

Dotenv, uses a UNIX compatible syntax. This makes applications deployable in all the contexts and we could decide to bypass it entirely if the server will load `.env` before the application is started.

UNIX standards > Ruby DSLs.

Another point is that about dependencies: [Dotenv](https://rubygems.org/gems/dotenv) doesn't have runtime dependencies. [ENVied](https://rubygems.org/gems/envied) will bring: `coercible`, `descendants_tracker` and `thread_safe`.

**Comment by jandudulski** [comment]
The issue is that dotenv and ENVied resolves two different problems.

dotenv loads variables from the file into the `ENV`
ENVied allows you to setup list of required variables to been setup in the application and coerce to types. And I think that framework itself shoudn't care how to populate `ENV` but how to handle it.
