### ISSUE TITLE
Command line arguments are ignored when using environment in plugins initialization.

### ISSUE THREAD

**Issue by Sickphilosopher** [hanami/hanami#960]
We using plugin:

```
group :plugins do
  gem 'hanami-webpack', git: 'https://github.com/Sickphilosopher/hanami-webpack.git'
end
```

Plugin calls Hanami.env when loaded. (https://github.com/Sickphilosopher/hanami-webpack/blob/aab739d1a92eacc573c1b1232483c359dfcff1b1/lib/hanami/webpack.rb#L7)

We run 'hanami s -p 3000'
Expected: server starts with port 3000
Actual: server starts with the standard port 2300

When we call Hanami.env, the Components ['environment'] is filled and when it is reinitialized in command#call it is not overwritten.
And when we call environment in server.rb, it's default one.

environment.object_id:

"in hanami.rb (.env):"
46925592240600
"in command (.call):"
46925595649520
"in server (._ extract_options)"
46925592240600

Gemfile.lock: https://gist.github.com/Sickphilosopher/352c93102b4cc0a8b3f1590d5abb273f

**Comment by AlfonsoUceda** [comment]
Hi @Sickphilosopher can you tell us how we can reproduce this? I've tested in a fresh hanami app (v1.3.0) and it works fine, my steps:

- Create a fresh `hanami` app
- Generate binstubs for `hanami` command.
- Add `hanami-webpack` to application's Gemfile as a plugin:
```
group :plugins do
  gem 'hanami-webpack', git: 'https://github.com/Sickphilosopher/hanami-webpack.git'
end
```
- Follow steps 3 and 4 from `hanami-webpack`'s README
```
3. Copy the base Webpack config webpack.config.sample.js and package.sample.json on your app root (removing the .sample in the name).
4. Run npm install.
```
- Run `bundle exec hanami s` and I see port 2300
- Run `bundle exec hanami s -p 3000` and I see port 3000

**Comment by Sickphilosopher** [comment]
Hi, @AlfonsoUceda, i updated hanami-webpack and now it works as expected. But i wrote some hacks for this.
You can install old version and reproduce issue.

```
group :plugins do
  gem 'hanami-webpack', git: 'https://github.com/Sickphilosopher/hanami-webpack.git', ref: 'aab739d1a92eacc573c1b1232483c359dfcff1b1'
end

```

This should works.

**Comment by jodosha** [comment]
@Sickphilosopher I'm sorry about this problem, can you please point me to the specific "hacks" that you used to make it to work again? Thanks.

**Comment by Sickphilosopher** [comment]
I removed all `Hanami.env` usages in plugin loading.
