### ISSUE TITLE
NameError: uninitialized constant only in production from sidekiq

### ISSUE THREAD

**Issue by kchoiinfluitive** [hanami/hanami#970]
I'm currently running into an issue when using sidekiq + hanami where sidekiq cannot find the worker class only in production. 

`NameError: uninitialized constant <class name>`

Fullstack trace for record: 
```
[GEM_ROOT]/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:261 :in `const_get`
[GEM_ROOT]/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:261 :in `block in constantize`
[GEM_ROOT]/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:259 :in `each`
[GEM_ROOT]/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:259 :in `inject`
[GEM_ROOT]/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:259 :in `constantize`
[GEM_ROOT]/gems/activesupport-4.2.10/lib/active_support/core_ext/string/inflections.rb:66 :in `constantize`
[GEM_ROOT]/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:127 :in `block in process`
[GEM_ROOT]/gems/sidekiq-4.2.10/lib/sidekiq.rb:35 :in `block in <module:Sidekiq>`
[GEM_ROOT]/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:126 :in `process`
[GEM_ROOT]/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:82 :in `process_one`
[GEM_ROOT]/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:70 :in `run`
[GEM_ROOT]/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:17 :in `watchdog`
[GEM_ROOT]/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:26 :in `block in safe_thread`
```
This is not reproducible consistently but only happens sometimes. Is there a way for us to add something like `config.autoload_paths` within hanami project?

**Comment by kchoiinfluitive** [comment]
I start like that and it doesn't help.

**Comment by jodosha** [comment]
@kchoiinfluitive Where does `activesupport` is coming from? Is it a `sidekiq` dependency?

Which is the value of `<class name>`?

**Comment by kchoiinfluitive** [comment]
i added it as a gem in our gemfile. class name is in `<project-name>/lib/<project-name>/workers/injector_worker.rb`

**Comment by jodosha** [comment]
@kchoiinfluitive You should make sure that ActiveSupport isn't using _constant autoloading_.

**Comment by cllns** [comment]
@kchoiinfluitive If you can upgrade Sidekiq to v5, I think that should fix this issue. They [removed monkey patching](https://github.com/mperham/sidekiq/pull/3474) after `v4.2.10`
