### ISSUE TITLE
Broken links to http://hanamirb.org/guides/

### ISSUE THREAD

**Issue by sharipov-ru** [hanami/hanami#980]
There are [lots of templates or examples with broken links](https://github.com/hanami/hanami/search?q=http%3A%2F%2Fhanamirb.org%2Fguides&unscoped_q=http%3A%2F%2Fhanamirb.org%2Fguides) to guides pages like:

http://hanamirb.org/guides/assets/compressors
http://hanamirb.org/guides/projects/code-reloading

All `http://hanamirb.org/guides/*` pages return 404 Page Not Found right now.

Is it possible to redirect 'em to https://guides.hanamirb.org without modifying all hanami repositories ?

**Comment by jodosha** [comment]
@sharipov-ru I think we should replace them in the code.
