### ISSUE TITLE
Update URL to Hanami guides in default welcome template

### ISSUE THREAD

**Issue by leo-generali** [hanami/hanami#998]
Hey there 👋!

I've been playing around with Hanami for a couple of days and I've been really enjoying it. 

On the main [welcome page template, the link](https://github.com/hanami/hanami/blob/439df9759040c2f7352bcb49898c3bebd37ccfe7/lib/hanami/templates/welcome.html.erb#L41) to the Hanami guides sends to http://hanamirb.org/guides/. The page then automatically redirects to https://guides.hanamirb.org/ within 5 seconds. 

Could we update the link on the main welcome template to go directly to https://guides.hanamirb.org/ or is there a reason traffic is being sent to http://hanamirb.org/guides?

**Comment by cllns** [comment]
@leo-generali We used to host the guides and the website in the same repo and on the domain, but we've since split them. We'd welcome this change to avoid the re-direct. Good find :)

Let me know if you want to tackle this, or if someone else should take it. Thanks!

**Comment by leo-generali** [comment]
@cllns happy to tackle this! I'll get something whipped up.

**Comment by leo-generali** [comment]
@cllns all done! let me know how it looks :)
